[CmdletBinding()]
param([string]$RepoRoot='')

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(!$RepoRoot){$RepoRoot=Split-Path -Parent $PSScriptRoot};$RepoRoot=(Resolve-Path $RepoRoot).Path
. (Join-Path $RepoRoot 'tests/fixture-test-common.ps1')
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Evidence.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.AtomicWrite.psm1') -Force
$taskScript=Join-Path $RepoRoot 'scripts/task.ps1';$script:passes=[Collections.Generic.List[string]]::new();$script:failures=[Collections.Generic.List[string]]::new();$script:unavailable=[Collections.Generic.List[string]]::new()
function Check($Condition,$Pass,$Fail){if($Condition){$script:passes.Add($Pass)}else{$script:failures.Add($Fail)}}
function Snapshot($Root){$items=@(Get-ChildItem -LiteralPath $Root -Force -Recurse);$entries=[Collections.Generic.List[string]]::new();foreach($item in @($items|Where-Object{$_.PSIsContainer})){$entries.Add('D|'+$item.FullName)};foreach($hash in @($items|Where-Object{-not$_.PSIsContainer}|Get-FileHash -Algorithm SHA256)){$entries.Add('F|'+$hash.Path+'|'+$hash.Hash)};return @($entries|Sort-Object)}
function Same($Before,$After,$Pass,$Fail){Check (@(Compare-Object @($Before) @($After)).Count -eq 0) $Pass $Fail}
function Start-Cli($Workspace,[string[]]$Arguments,$Fault='',$FaultBeforeFirstClaim='',$DelayBeforeFirstClaim=''){$old=$env:HARNESS_PROTOCOL;$oldFault=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP;$oldPreclaim=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM;$oldDelay=$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS;try{$env:HARNESS_PROTOCOL='v2';if($Fault){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP=$Fault}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP -ErrorAction Ignore};if($FaultBeforeFirstClaim){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM=$FaultBeforeFirstClaim}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM -ErrorAction Ignore};if($DelayBeforeFirstClaim){$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS=$DelayBeforeFirstClaim}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS -ErrorAction Ignore};return Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $taskScript -Arguments ($Arguments+@('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$Workspace))}finally{if($null-eq$old){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$old};if($null-eq$oldFault){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP=$oldFault};if($null-eq$oldPreclaim){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM=$oldPreclaim};if($null-eq$oldDelay){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS=$oldDelay}}}
function Complete-Cli($Handle){if(-not$Handle.Process.WaitForExit(30000)){$Handle.Process.Kill($true);throw 'CLI timeout'};$r=[pscustomobject]@{ExitCode=$Handle.Process.ExitCode;StdOut=$Handle.StdOut.GetAwaiter().GetResult().Trim();StdErr=$Handle.StdErr.GetAwaiter().GetResult().Trim()};$Handle.Process.Dispose();return $r}
function Invoke-Cli($Workspace,[string[]]$Arguments,$Fault='',$FaultBeforeFirstClaim='',$DelayBeforeFirstClaim=''){return Complete-Cli (Start-Cli $Workspace $Arguments $Fault $FaultBeforeFirstClaim $DelayBeforeFirstClaim)}
function Read-Output($Result){if($Result.StdOut){return $Result.StdOut|ConvertFrom-Json -Depth 50 -DateKind String};return $null}

function Write-Contract($Workspace,$TaskId){
    $body=[ordered]@{schema_version='requirement-contract/v1';task_id=$TaskId;goal="Verify $TaskId.";acceptance=@('Required behavior passes.');in_scope=@('v2 Evidence');out_of_scope=@('v1 TEST');product_constraints=@('No false pass.');product_decisions=@();unresolved_product_decisions=@();source_authority=@('current-user-message')}
    $contract=[ordered]@{};foreach($key in $body.Keys){$contract[$key]=$body[$key]};$contract.digest=Get-HarnessSha256Text -Content ($body|ConvertTo-Json -Depth 30 -Compress)
    $relative="contracts/$TaskId.json";$path=Join-Path $Workspace $relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllText($path,(($contract|ConvertTo-Json -Depth 30)+"`n"),[Text.UTF8Encoding]::new($false))
    return [pscustomobject]@{Path=$relative;Digest=$contract.digest}
}
function Write-JsonFile($Workspace,$Relative,$Value){$path=Join-Path $Workspace $Relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllText($path,(($Value|ConvertTo-Json -Depth 40)+"`n"),[Text.UTF8Encoding]::new($false))}

function New-EvidenceFixture($Workspace,$TaskId,$ContractDigest,$Mode){
    $recordRelative=".harness/evidence/$TaskId-$Mode.txt";$recordPath=Join-Path $Workspace $recordRelative
    [void][IO.Directory]::CreateDirectory((Split-Path -Parent $recordPath));[IO.File]::WriteAllText($recordPath,("$Mode`n"),[Text.UTF8Encoding]::new($false));$digest='sha256:'+((Get-FileHash $recordPath).Hash.ToLowerInvariant())
    $satisfied=@();$notVerified=@();$blocked=@();$gaps=@();$conclusion=$Mode
    if($Mode -in @('pass','false-pass','dirty')){$satisfied=@('AC-1');$conclusion='pass'}elseif($Mode-ceq'fail'){$satisfied=@('AC-1')}elseif($Mode-ceq'blocked'){$blocked=@('AC-1');$gaps=@([ordered]@{id='AC-1';status='blocked';reason='external dependency'})}else{$notVerified=@('AC-1');$gaps=@([ordered]@{id='AC-1';status='not-verified';reason='not run'});$conclusion='partial'}
    if($Mode-ceq'blocked'){$record=[ordered]@{type='inspection';method='external-check';result='blocked';executed_at=[DateTimeOffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest=$digest;covers=@()}}
    elseif($Mode-ceq'partial'){$record=[ordered]@{type='inspection';method='manual-check';result='partial';executed_at=[DateTimeOffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest=$digest;covers=@()}}
    else{$exitCode=if($Mode-in @('fail','false-pass')){7}else{0};$record=[ordered]@{type='command';command="fixture-$Mode";cwd='.';exit_code=$exitCode;executed_at=[DateTimeOffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest=$digest;covers=@('AC-1')}}
    $document=[ordered]@{schema_version='evidence/v1';task_id=$TaskId;task_version=3;contract_digest=$ContractDigest;revision=('dirty:'+'0'*64);records=@($record);coverage=[ordered]@{satisfied=$satisfied;not_verified=$notVerified;blocked=$blocked};gaps=$gaps;conclusion=$conclusion}
    $inputRelative="evidence-inputs/$TaskId-$Mode.json";Write-JsonFile $Workspace $inputRelative $document
    $document.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $Workspace -ContractDigest $ContractDigest -Evidence $document -EvidenceInputPath $inputRelative -EvidenceOutputPath "docs/tasks/$TaskId/evidence.json";Write-JsonFile $Workspace $inputRelative $document
    return [pscustomobject]@{Path=$inputRelative;Document=$document;RecordPath=$recordRelative}
}
function Start-TaskVerifying($Workspace,$TaskId,$ContractPath,[switch]$Activate){$args=@('create','-TaskId',$TaskId,'-Contract',$ContractPath,'-AsJson');if($Activate){$args+= '-ActivateCurrent'};$created=Invoke-Cli $Workspace $args;$running=Invoke-Cli $Workspace @('transition','-TaskId',$TaskId,'-ExpectedVersion','1','-To','running','-AsJson');$verifying=Invoke-Cli $Workspace @('transition','-TaskId',$TaskId,'-ExpectedVersion','2','-To','verifying','-AsJson');if($created.ExitCode-or$running.ExitCode-or$verifying.ExitCode){throw "failed to prepare verifying task: $TaskId"}}

$repoBefore=@(& git -C $RepoRoot status --porcelain --untracked-files=all);$temp=Join-Path ([IO.Path]::GetTempPath()) ('v2-evidence-'+[guid]::NewGuid().ToString('N'));$workspace=Join-Path $temp 'workspace';$outside=Join-Path $temp 'outside';[void][IO.Directory]::CreateDirectory($workspace);[void][IO.Directory]::CreateDirectory($outside);$runningOnWindows=[System.Environment]::OSVersion.Platform-eq[System.PlatformID]::Win32NT
[IO.File]::WriteAllText((Join-Path $workspace '.gitignore'),".assistant/runtime/`n.harness/evidence/`nevidence-inputs/`ndocs/tasks/*/evidence.json`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $workspace 'source-evidence.json'),"{}`n",[Text.UTF8Encoding]::new($false));$runtimeCaseProbe=$null;if($runningOnWindows){$runtimeCaseProbe=Join-Path $workspace '.Assistant\Runtime\case-probe.txt';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $runtimeCaseProbe));[IO.File]::WriteAllText($runtimeCaseProbe,"baseline`n",[Text.UTF8Encoding]::new($false))}
$contracts=@{};$taskIds=@('pass-task','case-task','tracked-record-task','tracked-input-task','short-task','unsafe-index-task','false-pass-task','stale-task','fail-task','blocked-task','partial-task','dirty-task','escape-task','digest-task','crash-task','preclaim-task','writer-preclaim-task','alias-task')
foreach($taskId in $taskIds){$contracts[$taskId]=Write-Contract $workspace $taskId}
git -C $workspace init -q;git -C $workspace config user.email harness@example.invalid;git -C $workspace config user.name Harness;git -C $workspace config core.autocrlf false;git -C $workspace add .;if($runningOnWindows){git -C $workspace add -f -- '.Assistant/Runtime/case-probe.txt'};git -C $workspace commit -qm baseline;$head=(git -C $workspace rev-parse HEAD).Trim()
$volumeAlias=$null
if($runningOnWindows){$root=[IO.Path]::GetPathRoot($workspace);$volumeOutput=@(& mountvol.exe $root /L 2>&1|ForEach-Object{[string]$_});$volumeExit=$LASTEXITCODE;$volumeMatch=[regex]::Match(($volumeOutput-join"`n"),'(?i)\\\\\?\\Volume\{[0-9a-f-]{36}\}\\');if($volumeExit-ne0-or-not$volumeMatch.Success){$script:unavailable.Add('Evidence volume alias fixture unavailable: mountvol did not return a volume GUID')}else{$volumeAlias=$volumeMatch.Value+$workspace.Substring($root.Length);if(-not(Test-Path -LiteralPath $volumeAlias -PathType Container)){$script:failures.Add('Evidence volume alias path does not exist')}}}else{$script:unavailable.Add('Evidence volume alias fixture requires Windows')}
foreach($file in @('scripts/lib/Harness.Evidence.psm1','scripts/lib/Harness.TaskState.psm1','scripts/task.ps1','tests/verify-v2-evidence.ps1')){$path=Join-Path $RepoRoot $file;$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($path,[ref]$tokens,[ref]$errors)|Out-Null;Check (@($errors).Count-eq 0) "$file parses" "$file parse failed";Check (Test-FileHasUtf8Bom $path) "$file has UTF-8 BOM" "$file lacks UTF-8 BOM"}
$exports=@(Get-Command -Module Harness.Evidence|Select-Object -ExpandProperty Name|Sort-Object);Check (@(Compare-Object @('Get-HarnessEvidenceRevision','Resolve-HarnessEvidence') $exports).Count-eq 0) 'Evidence exports are exact' 'Evidence exports drifted';$evidenceResolve=Get-Command Resolve-HarnessEvidence -Module Harness.Evidence;Check (-not$evidenceResolve.Parameters.ContainsKey('PinnedRevision')) 'Evidence revision override is module-private' 'Evidence public API exposes a pinned-revision bypass'
$evidenceSource=Get-Content -LiteralPath (Join-Path $RepoRoot 'scripts/lib/Harness.Evidence.psm1') -Raw -Encoding utf8;Check ($evidenceSource-match 'Environment\.Keys'-and$evidenceSource-match "-like 'GIT_\*'"-and$evidenceSource-match "GIT_CONFIG_NOSYSTEM'\] = '1'"-and$evidenceSource-match "GIT_CONFIG_GLOBAL'\]"-and$evidenceSource-match "GIT_ATTR_NOSYSTEM'\] = '1'"-and$evidenceSource-match "'config','--includes','--get-regexp','\^filter\\\.'"-and$evidenceSource-match "core\.fsmonitor=false"-and$evidenceSource-match "'--ignore-submodules=none','--no-ext-diff','--no-textconv','--binary'") 'Evidence Git inspection isolates config and disables clean/external diff drivers' 'Evidence Git inspection can inherit caller controls, filters, or external diff drivers'
foreach($taskId in $taskIds){Start-TaskVerifying $workspace $taskId $contracts[$taskId].Path -Activate:($taskId-ceq'pass-task')}

$passEvidence=New-EvidenceFixture $workspace 'pass-task' $contracts['pass-task'].Digest 'pass';Check ($passEvidence.Document.revision-ceq$head) 'clean Evidence binds the current commit' 'clean Evidence revision is stale';$gitPoisonNames=@('GIT_DIR','GIT_WORK_TREE','GIT_INDEX_FILE','GIT_EXTERNAL_DIFF');$savedGitPoison=@{};foreach($name in $gitPoisonNames){$savedGitPoison[$name]=[Environment]::GetEnvironmentVariable($name,[EnvironmentVariableTarget]::Process)};try{foreach($name in $gitPoisonNames){[Environment]::SetEnvironmentVariable($name,(Join-Path $outside "missing-$name"),[EnvironmentVariableTarget]::Process)};$poisonedCleanRevision=Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['pass-task'].Digest -Evidence $passEvidence.Document -EvidenceInputPath $passEvidence.Path -EvidenceOutputPath 'docs/tasks/pass-task/evidence.json'}catch{$poisonedCleanRevision='error:'+($_.Exception.Message)}finally{foreach($name in $gitPoisonNames){if($null-eq$savedGitPoison[$name]){Remove-Item -LiteralPath "Env:$name" -ErrorAction SilentlyContinue}else{[Environment]::SetEnvironmentVariable($name,[string]$savedGitPoison[$name],[EnvironmentVariableTarget]::Process)}}};Check ($poisonedCleanRevision-ceq$head) 'clean Evidence ignores caller-supplied Git repository and diff controls' "caller Git controls changed clean Evidence revision: $poisonedCleanRevision";$result=Invoke-Cli $workspace @('verify','-TaskId','pass-task','-ExpectedVersion','3','-Evidence',$passEvidence.Path,'-AsJson');$passResult=Read-Output $result
$artifact=Join-Path $workspace 'docs/tasks/pass-task/evidence.json';$status=Read-Output (Invoke-Cli $workspace @('status','-TaskId','pass-task','-AsJson'))
Check ($result.ExitCode-eq 0-and$passResult.conclusion-ceq'pass'-and$passResult.task.status-ceq'done'-and$passResult.pointer_action-ceq'cleared'-and-not(Test-Path (Join-Path $workspace '.assistant/runtime/current.json'))) 'pass Evidence closes active task and clears current' 'pass Evidence did not close active task'
Check ((Test-Path $artifact)-and('sha256:'+((Get-FileHash $artifact).Hash.ToLowerInvariant()))-ceq$passResult.evidence_digest-and$status.event_count-eq 5) 'pass Evidence artifact and audit events are durable' 'pass Evidence artifact or events are invalid'
Check (-not(Test-Path (Join-Path $workspace '.assistant/运行时'))-and-not(Test-Path (Join-Path $workspace 'docs/tasks/pass-task/test.md'))) 'Evidence does not write v1 runtime or test.md' 'Evidence changed v1 surfaces'
$caseEvidence=New-EvidenceFixture $workspace 'case-task' $contracts['case-task'].Digest 'pass';if($runningOnWindows){[IO.File]::WriteAllText($runtimeCaseProbe,"changed`n",[Text.UTF8Encoding]::new($false));$caseInputRelative='Case-Inputs/Case-Task-Pass.json';$caseExclusionVariant=$caseInputRelative.ToUpperInvariant();$caseEvidence.Path=$caseInputRelative;Write-JsonFile $workspace $caseInputRelative $caseEvidence.Document;$caseEvidence.Document.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['case-task'].Digest -Evidence $caseEvidence.Document -EvidenceInputPath $caseInputRelative -EvidenceOutputPath 'docs/tasks/case-task/evidence.json';Write-JsonFile $workspace $caseInputRelative $caseEvidence.Document;$caseVariantRevision=Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['case-task'].Digest -Evidence $caseEvidence.Document -EvidenceInputPath $caseExclusionVariant -EvidenceOutputPath 'docs/tasks/case-task/evidence.json';Check ($caseEvidence.Document.revision-ceq$head) 'Windows Evidence revision excludes case-variant runtime paths' 'case-variant runtime path made a clean Evidence revision dirty';Check ($caseVariantRevision-ceq$head) 'Windows Evidence exact exclusions are case-insensitive' 'case-variant Evidence input exclusion included its own file';$caseResult=Invoke-Cli $workspace @('verify','-TaskId','case-task','-ExpectedVersion','3','-Evidence',$caseInputRelative,'-AsJson');Check ($caseResult.ExitCode-eq0-and(Read-Output $caseResult).task.status-ceq'done') 'Windows Evidence input excluded itself from revision binding' "Evidence input self-exclusion failed: exit=$($caseResult.ExitCode) stderr=[$($caseResult.StdErr)]";[IO.File]::WriteAllText($runtimeCaseProbe,"baseline`n",[Text.UTF8Encoding]::new($false));Remove-Item -LiteralPath (Join-Path $workspace $caseInputRelative) -Force}else{$script:unavailable.Add('case-variant Evidence path fixture requires Windows')}
$trackedRecord=New-EvidenceFixture $workspace 'tracked-record-task' $contracts['tracked-record-task'].Digest 'pass';[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"changed tracked evidence`n",[Text.UTF8Encoding]::new($false));$trackedRecord.Document.records[0].evidence_path='source.txt';$trackedRecord.Document.records[0].digest='sha256:'+((Get-FileHash (Join-Path $workspace 'source.txt')).Hash.ToLowerInvariant());$trackedRecord.Document.revision=$head;Write-JsonFile $workspace $trackedRecord.Path $trackedRecord.Document;$gitApplication=@(Get-Command git -CommandType Application -ErrorAction Stop)[0];$gitTrue=Join-Path (Split-Path -Parent (Split-Path -Parent ([string]$gitApplication.Path))) 'usr/bin/true.exe';$externalDiff=$(if(Test-Path -LiteralPath $gitTrue -PathType Leaf){$gitTrue}else{Join-Path $outside 'missing-external-diff.exe'});$savedExternalDiff=[Environment]::GetEnvironmentVariable('GIT_EXTERNAL_DIFF',[EnvironmentVariableTarget]::Process);try{[Environment]::SetEnvironmentVariable('GIT_EXTERNAL_DIFF',$externalDiff,[EnvironmentVariableTarget]::Process);$trackedRecordRevision=Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['tracked-record-task'].Digest -Evidence $trackedRecord.Document -EvidenceInputPath $trackedRecord.Path -EvidenceOutputPath 'docs/tasks/tracked-record-task/evidence.json'}catch{$trackedRecordRevision='error:'+($_.Exception.Message)}finally{if($null-eq$savedExternalDiff){Remove-Item -LiteralPath 'Env:GIT_EXTERNAL_DIFF' -ErrorAction SilentlyContinue}else{[Environment]::SetEnvironmentVariable('GIT_EXTERNAL_DIFF',[string]$savedExternalDiff,[EnvironmentVariableTarget]::Process)}};Check ($trackedRecordRevision.StartsWith('dirty:',[StringComparison]::Ordinal)) 'modified tracked record evidence cannot be hidden by GIT_EXTERNAL_DIFF' "external diff control hid or broke the tracked record revision: $trackedRecordRevision";$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','tracked-record-task','-ExpectedVersion','3','-Evidence',$trackedRecord.Path,'-AsJson');Check ($result.ExitCode-eq2-and$result.StdErr-match'Evidence dirty revision is stale') 'tracked record cannot claim the clean HEAD revision' 'tracked record spoofed a clean HEAD revision';Same $snapshot (Snapshot $workspace) 'tracked record revision rejection is zero-write' 'tracked record revision rejection wrote state';[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false))
$filterRejected=$false;$infoAttributes=Join-Path $workspace '.git/info/attributes';try{[IO.File]::WriteAllText($infoAttributes,"source.txt filter=hide`n",[Text.UTF8Encoding]::new($false));git -C $workspace config --local extensions.worktreeConfig true;git -C $workspace config --worktree filter.hide.clean 'git show HEAD:source.txt';if($LASTEXITCODE-ne0){throw 'unable to configure clean-filter fixture'};[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"hidden by clean filter`n",[Text.UTF8Encoding]::new($false));try{[void](Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['tracked-record-task'].Digest -Evidence $trackedRecord.Document -EvidenceInputPath $trackedRecord.Path -EvidenceOutputPath 'docs/tasks/tracked-record-task/evidence.json')}catch{$filterRejected=$_.Exception.Message-match'unsupported Git clean filters'}}finally{git -C $workspace config --worktree --unset-all filter.hide.clean 2>$null;git -C $workspace config --local --unset-all extensions.worktreeConfig 2>$null;Remove-Item -LiteralPath $infoAttributes -Force -ErrorAction SilentlyContinue;[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false))};Check $filterRejected 'worktree-scoped Git clean filters fail closed before they can hide tracked changes' 'a worktree-scoped Git clean filter could influence Evidence revision binding'
$trackedInput=New-EvidenceFixture $workspace 'tracked-input-task' $contracts['tracked-input-task'].Digest 'pass';$trackedInput.Document.revision=$head;Write-JsonFile $workspace 'source-evidence.json' $trackedInput.Document;$trackedInputRevision=Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['tracked-input-task'].Digest -Evidence $trackedInput.Document -EvidenceInputPath 'source-evidence.json' -EvidenceOutputPath 'docs/tasks/tracked-input-task/evidence.json';Check ($trackedInputRevision.StartsWith('dirty:',[StringComparison]::Ordinal)) 'modified tracked Evidence input is bound into a dirty revision' 'modified tracked Evidence input was excluded as a clean HEAD';$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','tracked-input-task','-ExpectedVersion','3','-Evidence','source-evidence.json','-AsJson');Check ($result.ExitCode-eq2-and$result.StdErr-match'Evidence dirty revision is stale') 'tracked Evidence input cannot claim the clean HEAD revision' 'tracked Evidence input spoofed a clean HEAD revision';Same $snapshot (Snapshot $workspace) 'tracked Evidence input rejection is zero-write' 'tracked Evidence input rejection wrote state';[IO.File]::WriteAllText((Join-Path $workspace 'source-evidence.json'),"{}`n",[Text.UTF8Encoding]::new($false))
$shortEvidence=New-EvidenceFixture $workspace 'short-task' $contracts['short-task'].Digest 'pass';$shortEvidence.Document.revision=$head.Substring(0,7);Write-JsonFile $workspace $shortEvidence.Path $shortEvidence.Document;$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','short-task','-ExpectedVersion','3','-Evidence',$shortEvidence.Path,'-AsJson')
Check ($result.ExitCode-eq2-and$result.StdErr-match'schema') 'short commit revision is rejected' 'short commit revision was accepted';Same $snapshot (Snapshot $workspace) 'short revision rejection is zero-write' 'short revision rejection wrote state'
$unsafeEvidence=New-EvidenceFixture $workspace 'unsafe-index-task' $contracts['unsafe-index-task'].Digest 'pass'
try{
    git -C $workspace update-index --skip-worktree source.txt
    if($LASTEXITCODE-ne0){throw 'unable to set skip-worktree fixture'}
    [IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"hidden-change`n",[Text.UTF8Encoding]::new($false))
    $snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','unsafe-index-task','-ExpectedVersion','3','-Evidence',$unsafeEvidence.Path,'-AsJson')
    Check ($result.ExitCode-eq2-and$result.StdErr-match'unsafe Git index flags') 'unsafe Git index flags are rejected before clean Evidence can pass' 'unsafe Git index flags were accepted';Same $snapshot (Snapshot $workspace) 'unsafe index rejection is zero-write' 'unsafe index rejection wrote task state'
}finally{
    git -C $workspace update-index --no-skip-worktree source.txt
    [IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false))
}
$falsePass=New-EvidenceFixture $workspace 'false-pass-task' $contracts['false-pass-task'].Digest 'false-pass';$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','false-pass-task','-ExpectedVersion','3','-Evidence',$falsePass.Path,'-AsJson')
Check ($result.ExitCode-eq 2-and-not$result.StdOut-and$result.StdErr-match'declared=pass derived=fail') 'pass with nonzero command is rejected' 'nonzero command was accepted as pass';Same $snapshot (Snapshot $workspace) 'false pass rejection is zero-write' 'false pass rejection wrote state'

$stale=New-EvidenceFixture $workspace 'stale-task' $contracts['stale-task'].Digest 'pass';$stale.Document.contract_digest='sha256:'+('0'*64);Write-JsonFile $workspace $stale.Path $stale.Document;$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','stale-task','-ExpectedVersion','3','-Evidence',$stale.Path,'-AsJson')
Check ($result.ExitCode-eq 2-and$result.StdErr-match'contract_digest is stale') 'stale Contract digest is rejected' 'stale Contract digest was accepted';Same $snapshot (Snapshot $workspace) 'stale Contract rejection is zero-write' 'stale Contract rejection wrote state'
$badDigest=New-EvidenceFixture $workspace 'digest-task' $contracts['digest-task'].Digest 'pass';$badDigest.Document.records[0].digest='sha256:'+('0'*64);Write-JsonFile $workspace $badDigest.Path $badDigest.Document;$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','digest-task','-ExpectedVersion','3','-Evidence',$badDigest.Path,'-AsJson')
Check ($result.ExitCode-eq 2-and$result.StdErr-match'record digest mismatch') 'record digest mismatch is rejected' 'record digest mismatch was accepted';Same $snapshot (Snapshot $workspace) 'record digest rejection is zero-write' 'record digest rejection wrote state'
$escape=New-EvidenceFixture $workspace 'escape-task' $contracts['escape-task'].Digest 'pass';$escape.Document.records[0].evidence_path='../outside.txt';Write-JsonFile $workspace $escape.Path $escape.Document;$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','escape-task','-ExpectedVersion','3','-Evidence',$escape.Path,'-AsJson')
Check ($result.ExitCode-eq 2-and$result.StdErr-match'schema') 'record evidence path escape is rejected' 'record evidence path escape was accepted';Same $snapshot (Snapshot $workspace) 'record path rejection is zero-write' 'record path rejection wrote state'
[IO.File]::Copy((Join-Path $workspace $passEvidence.Path),(Join-Path $outside 'evidence.json'));$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','escape-task','-ExpectedVersion','3','-Evidence',(Join-Path $outside 'evidence.json'),'-AsJson')
Check ($result.ExitCode-eq 2-and$result.StdErr-match'escapes WorkspaceRoot') 'Evidence input path escape is rejected' 'Evidence input path escape was accepted';Same $snapshot (Snapshot $workspace) 'input path rejection is zero-write' 'input path rejection wrote state'

$failEvidence=New-EvidenceFixture $workspace 'fail-task' $contracts['fail-task'].Digest 'fail';$result=Invoke-Cli $workspace @('verify','-TaskId','fail-task','-ExpectedVersion','3','-Evidence',$failEvidence.Path,'-AsJson');$value=Read-Output $result
Check ($result.ExitCode-eq 0-and$value.conclusion-ceq'fail'-and$value.task.status-ceq'running'-and$value.task.version-eq 4) 'fail Evidence returns task to running' 'fail Evidence completed or stranded task'
$blockedEvidence=New-EvidenceFixture $workspace 'blocked-task' $contracts['blocked-task'].Digest 'blocked';$result=Invoke-Cli $workspace @('verify','-TaskId','blocked-task','-ExpectedVersion','3','-Evidence',$blockedEvidence.Path,'-AsJson');$value=Read-Output $result
Check ($result.ExitCode-eq 0-and$value.conclusion-ceq'blocked'-and$value.task.status-ceq'paused') 'blocked Evidence keeps task unfinished and paused' 'blocked Evidence reached a terminal state'
$partialEvidence=New-EvidenceFixture $workspace 'partial-task' $contracts['partial-task'].Digest 'partial';$result=Invoke-Cli $workspace @('verify','-TaskId','partial-task','-ExpectedVersion','3','-Evidence',$partialEvidence.Path,'-AsJson');$value=Read-Output $result
Check ($result.ExitCode-eq 0-and$value.conclusion-ceq'partial'-and$value.task.status-ceq'verifying'-and$value.task.version-eq 4) 'partial Evidence remains verifying' 'partial Evidence completed task'

$crashEvidence=New-EvidenceFixture $workspace 'crash-task' $contracts['crash-task'].Digest 'pass';$result=Invoke-Cli $workspace @('verify','-TaskId','crash-task','-ExpectedVersion','3','-Evidence',$crashEvidence.Path,'-AsJson') '1';$match=[regex]::Match($result.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$transactionId=if($match.Success){$match.Groups[1].Value}else{''}
Check ($result.ExitCode-eq 2-and$match.Success-and(Test-Path (Join-Path $workspace 'docs/tasks/crash-task/evidence.json'))-and(Test-Path (Join-Path $workspace ".assistant/runtime/failed-writes/$transactionId.json"))) 'Evidence fault leaves artifact and replay journal' 'Evidence fault did not journal partial write'
$postEvidenceDriftPath=Join-Path $workspace 'post-evidence-drift.txt';[IO.File]::WriteAllText($postEvidenceDriftPath,"later change`n",[Text.UTF8Encoding]::new($false));$replay=Invoke-Cli $workspace @('replay','-TransactionId',$transactionId,'-AsJson');$again=Invoke-Cli $workspace @('replay','-TransactionId',$transactionId,'-AsJson');$status=Read-Output (Invoke-Cli $workspace @('status','-TaskId','crash-task','-AsJson'))
Check ($replay.ExitCode-eq 0-and(Read-Output $replay).result-ceq'recovered'-and$again.ExitCode-eq 0-and(Read-Output $again).result-ceq'already-recovered'-and$status.task.status-ceq'done'-and$status.event_count-eq 5-and(Test-Path $postEvidenceDriftPath)) 'Evidence replay uses its pinned revision after publication begins' 'Evidence replay was stranded by later workspace revision drift';Remove-Item -LiteralPath $postEvidenceDriftPath -Force
$preclaimEvidence=New-EvidenceFixture $workspace 'preclaim-task' $contracts['preclaim-task'].Digest 'pass';$preclaimFault=Invoke-Cli $workspace @('verify','-TaskId','preclaim-task','-ExpectedVersion','3','-Evidence',$preclaimEvidence.Path,'-AsJson') '' '1';$preclaimMatch=[regex]::Match($preclaimFault.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$preclaimId=$(if($preclaimMatch.Success){$preclaimMatch.Groups[1].Value}else{''});$preclaimClaims=@(Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$preclaimDriftPath=Join-Path $workspace 'preclaim-drift.txt';[IO.File]::WriteAllText($preclaimDriftPath,"later change`n",[Text.UTF8Encoding]::new($false));$preclaimSnap=Snapshot $workspace;$preclaimReplay=$(if($preclaimId){Invoke-Cli $workspace @('replay','-TransactionId',$preclaimId,'-AsJson')}else{$preclaimFault})
Check ($preclaimFault.ExitCode-eq2-and$preclaimMatch.Success-and$preclaimClaims.Count-eq0-and$preclaimReplay.ExitCode-eq2-and$preclaimReplay.StdErr-match'Evidence .* revision is stale') 'claim-free Evidence replay revalidates the live workspace revision' 'claim-free replay accepted stale Evidence without publication ownership';Same $preclaimSnap (Snapshot $workspace) 'claim-free revision rejection is zero-write' 'claim-free revision rejection wrote state';Remove-Item -LiteralPath $preclaimDriftPath -Force

$writerEvidence=New-EvidenceFixture $workspace 'writer-preclaim-task' $contracts['writer-preclaim-task'].Digest 'pass';$writerPendingBefore=@(Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/failed-writes') -Filter 'txn_*.json' -File -ErrorAction SilentlyContinue|Select-Object -ExpandProperty BaseName);$writerHandle=Start-Cli $workspace @('verify','-TaskId','writer-preclaim-task','-ExpectedVersion','3','-Evidence',$writerEvidence.Path,'-AsJson') '' '' '4000';$writerPending=$null;$writerDeadline=[datetime]::UtcNow.AddSeconds(10);while($null-eq$writerPending-and[datetime]::UtcNow-lt$writerDeadline){$writerPending=Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/failed-writes') -Filter 'txn_*.json' -File -ErrorAction SilentlyContinue|Where-Object{$writerPendingBefore -notcontains $_.BaseName}|Select-Object -First 1;if($null-eq$writerPending){Start-Sleep -Milliseconds 25}};$writerDriftPath=Join-Path $workspace 'normal-writer-drift.txt';[IO.File]::WriteAllText($writerDriftPath,"drift before first claim`n",[Text.UTF8Encoding]::new($false));$writerResult=Complete-Cli $writerHandle;$writerStatus=Read-Output (Invoke-Cli $workspace @('status','-TaskId','writer-preclaim-task','-AsJson'));$writerClaims=@(Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$writerArtifact=Join-Path $workspace 'docs/tasks/writer-preclaim-task/evidence.json';$writerId=$(if($null-ne$writerPending){$writerPending.BaseName}else{''})
Check ($null-ne$writerPending-and$writerResult.ExitCode-eq2-and$writerResult.StdErr-match'Evidence .* revision is stale'-and$writerStatus.task.version-eq3-and$writerStatus.task.status-ceq'verifying'-and-not(Test-Path $writerArtifact)-and$writerClaims.Count-eq0) 'normal writer revalidates the live Evidence revision before its first publication claim' 'normal writer published stale Evidence after pre-claim revision drift';Remove-Item -LiteralPath $writerDriftPath -Force;$writerReplay=$(if($writerId){Invoke-Cli $workspace @('replay','-TransactionId',$writerId,'-AsJson')}else{$writerResult});$writerRecovered=Read-Output $writerReplay
Check ($writerReplay.ExitCode-eq0-and$writerRecovered.result-ceq'recovered'-and$writerRecovered.completed_steps.Count-ge3) 'claim-free writer rejection remains replayable after the live revision is restored' 'pre-claim revision rejection stranded its transaction'

if(-not[string]::IsNullOrWhiteSpace($volumeAlias)){$aliasEvidence=New-EvidenceFixture $workspace 'alias-task' $contracts['alias-task'].Digest 'pass';$aliasFault=Invoke-Cli $workspace @('verify','-TaskId','alias-task','-ExpectedVersion','3','-Evidence',$aliasEvidence.Path,'-AsJson') '' '1';$aliasMatch=[regex]::Match($aliasFault.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$aliasId=$(if($aliasMatch.Success){$aliasMatch.Groups[1].Value}else{''});$aliasReplay=$(if($aliasId){Invoke-Cli $volumeAlias @('replay','-TransactionId',$aliasId,'-AsJson')}else{$aliasFault});$aliasStatus=Read-Output (Invoke-Cli $workspace @('status','-TaskId','alias-task','-AsJson'));Check ($aliasFault.ExitCode-eq2-and$aliasMatch.Success-and$aliasReplay.ExitCode-eq0-and(Read-Output $aliasReplay).result-ceq'recovered'-and$aliasStatus.task.status-ceq'done') 'claim-free Evidence replay accepts a volume-GUID spelling of the same physical workspace' "volume-GUID Evidence replay failed: faultExit=$($aliasFault.ExitCode) fault=[$($aliasFault.StdErr)] replayExit=$($aliasReplay.ExitCode) replay=[$($aliasReplay.StdErr)]"}

[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"dirty-one`n",[Text.UTF8Encoding]::new($false));$dirtyEvidence=New-EvidenceFixture $workspace 'dirty-task' $contracts['dirty-task'].Digest 'dirty'
Check ($dirtyEvidence.Document.revision -match '^dirty:[0-9a-f]{64}$') 'dirty revision is deterministic and schema-valid' 'dirty revision was not derived'
[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"dirty-two`n",[Text.UTF8Encoding]::new($false));$snapshot=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','dirty-task','-ExpectedVersion','3','-Evidence',$dirtyEvidence.Path,'-AsJson')
Check ($result.ExitCode-eq 2-and$result.StdErr-match'dirty revision is stale') 'stale dirty revision is rejected' 'stale dirty revision was accepted';Same $snapshot (Snapshot $workspace) 'stale revision rejection is zero-write' 'stale revision rejection wrote state'
$dirtyEvidence.Document.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $workspace -ContractDigest $contracts['dirty-task'].Digest -Evidence $dirtyEvidence.Document -EvidenceInputPath $dirtyEvidence.Path -EvidenceOutputPath 'docs/tasks/dirty-task/evidence.json';Write-JsonFile $workspace $dirtyEvidence.Path $dirtyEvidence.Document
$dirtyVerifyRoot=$workspace;if(-not[string]::IsNullOrWhiteSpace($volumeAlias)){$dirtyAliasRevision=Get-HarnessEvidenceRevision -WorkspaceRoot $volumeAlias -ContractDigest $contracts['dirty-task'].Digest -Evidence $dirtyEvidence.Document -EvidenceInputPath $dirtyEvidence.Path -EvidenceOutputPath 'docs/tasks/dirty-task/evidence.json';Check ($dirtyAliasRevision-ceq$dirtyEvidence.Document.revision) 'dirty Evidence revision is bound to physical workspace identity across volume aliases' 'dirty Evidence revision changed across lexical aliases of one workspace';$dirtyVerifyRoot=$volumeAlias};$result=Invoke-Cli $dirtyVerifyRoot @('verify','-TaskId','dirty-task','-ExpectedVersion','3','-Evidence',$dirtyEvidence.Path,'-AsJson');$value=Read-Output $result
Check ($result.ExitCode-eq 0-and$value.task.status-ceq'done'-and$value.conclusion-ceq'pass') 'fresh dirty revision can close a task' "fresh dirty revision failed: exit=$($result.ExitCode) stderr=[$($result.StdErr)]"

$sha256Workspace=Join-Path $temp 'sha256-workspace';[void][IO.Directory]::CreateDirectory($sha256Workspace);[IO.File]::WriteAllText((Join-Path $sha256Workspace '.gitignore'),".assistant/runtime/`n.harness/evidence/`nevidence-inputs/`ndocs/tasks/*/evidence.json`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $sha256Workspace 'source.txt'),"sha256 baseline`n",[Text.UTF8Encoding]::new($false));$sha256Contract=Write-Contract $sha256Workspace 'sha256-task'
$sha256Init=@(& git -C $sha256Workspace init -q --object-format=sha256 2>&1|ForEach-Object{[string]$_});$sha256InitExit=$LASTEXITCODE
if($sha256InitExit-ne0){$script:unavailable.Add("Git SHA-256 Evidence fixture unavailable: $($sha256Init-join'; ')")}else{git -C $sha256Workspace config user.email harness@example.invalid;git -C $sha256Workspace config user.name Harness;git -C $sha256Workspace config core.autocrlf false;git -C $sha256Workspace add .;git -C $sha256Workspace commit -qm baseline;$sha256Head=(git -C $sha256Workspace rev-parse HEAD).Trim();Start-TaskVerifying $sha256Workspace 'sha256-task' $sha256Contract.Path;$sha256Evidence=New-EvidenceFixture $sha256Workspace 'sha256-task' $sha256Contract.Digest 'pass';Check ($sha256Head-match'^[0-9a-f]{64}$'-and$sha256Evidence.Document.revision-ceq$sha256Head) 'clean Evidence binds the complete SHA-256 Git HEAD' 'SHA-256 Evidence revision was truncated or marked dirty';$sha256Result=Invoke-Cli $sha256Workspace @('verify','-TaskId','sha256-task','-ExpectedVersion','3','-Evidence',$sha256Evidence.Path,'-AsJson');$sha256Value=Read-Output $sha256Result;Check ($sha256Result.ExitCode-eq0-and$sha256Value.task.status-ceq'done') 'SHA-256 Git Evidence passes schema and closes the task' "SHA-256 Git Evidence failed: exit=$($sha256Result.ExitCode) stderr=[$($sha256Result.StdErr)]"}

if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}
$repoAfter=@(& git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count-eq 0) 'Evidence verifier performs no repository writes' 'Evidence verifier changed repository state'
foreach($item in $script:passes){"[PASS] $item"};foreach($item in $script:unavailable){"[UNAVAILABLE] $item"};foreach($item in $script:failures){"[FAIL] $item"}
if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:passes.Count) checks)";exit 0
