[CmdletBinding()]
param([string]$RepoRoot='')

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(!$RepoRoot){$RepoRoot=Split-Path -Parent $PSScriptRoot};$RepoRoot=(Resolve-Path $RepoRoot).Path
. (Join-Path $RepoRoot 'tests/fixture-test-common.ps1')
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.ProtectedAction.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Evidence.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.AtomicWrite.psm1') -Force
$taskScript=Join-Path $RepoRoot 'scripts/task.ps1';$hookScript=Join-Path $RepoRoot 'runtime-hooks/core/pretooluse.ps1';$script:passes=[Collections.Generic.List[string]]::new();$script:failures=[Collections.Generic.List[string]]::new()
function Check($Condition,$Pass,$Fail){if($Condition){$script:passes.Add($Pass)}else{$script:failures.Add($Fail)}}
function Snapshot($Root){$items=@(Get-ChildItem -LiteralPath $Root -Force -Recurse);$entries=[Collections.Generic.List[string]]::new();foreach($item in @($items|Where-Object{$_.PSIsContainer})){$entries.Add('D|'+$item.FullName)};foreach($hash in @($items|Where-Object{-not$_.PSIsContainer}|Get-FileHash -Algorithm SHA256)){$entries.Add('F|'+$hash.Path+'|'+$hash.Hash)};return @($entries|Sort-Object)}
function Same($Before,$After,$Pass,$Fail){Check (@(Compare-Object @($Before) @($After)).Count-eq0) $Pass $Fail}
function Digest($Text){$hash=[Security.Cryptography.SHA256]::Create();try{return 'sha256:'+([BitConverter]::ToString($hash.ComputeHash([Text.UTF8Encoding]::new($false).GetBytes($Text))).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()}}
function Complete-Process($Handle){if(-not$Handle.Process.WaitForExit(30000)){$Handle.Process.Kill($true);throw 'process timeout'};$result=[pscustomobject]@{ExitCode=$Handle.Process.ExitCode;StdOut=$Handle.StdOut.GetAwaiter().GetResult().Trim();StdErr=$Handle.StdErr.GetAwaiter().GetResult().Trim()};$Handle.Process.Dispose();return $result}
function Start-Cli($Workspace,[string[]]$Arguments,$Fault='',$FaultBeforeFirstClaim='',$DelayBeforeFirstClaim=''){$old=$env:HARNESS_PROTOCOL;$oldFault=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP;$oldPreclaim=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM;$oldDelay=$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS;try{$env:HARNESS_PROTOCOL='v2';if($Fault){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP=$Fault}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP -ErrorAction Ignore};if($FaultBeforeFirstClaim){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM=$FaultBeforeFirstClaim}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM -ErrorAction Ignore};if($DelayBeforeFirstClaim){$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS=$DelayBeforeFirstClaim}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS -ErrorAction Ignore};return Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $taskScript -Arguments ($Arguments+@('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$Workspace))}finally{if($null-eq$old){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$old};if($null-eq$oldFault){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP=$oldFault};if($null-eq$oldPreclaim){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM=$oldPreclaim};if($null-eq$oldDelay){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_FIRST_CLAIM_MS=$oldDelay}}}
function Invoke-Cli($Workspace,[string[]]$Arguments,$Fault='',$FaultBeforeFirstClaim='',$DelayBeforeFirstClaim=''){return Complete-Process (Start-Cli $Workspace $Arguments $Fault $FaultBeforeFirstClaim $DelayBeforeFirstClaim)}
function Invoke-Hook($Workspace,[string[]]$Arguments,$HookRepo=$RepoRoot,$HookPath=$hookScript){return Complete-Process (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $HookPath -Arguments ($Arguments+@('-RepoRoot',$HookRepo,'-WorkspaceRoot',$Workspace,'-AsJson')))}
function Read-Output($Result){if($Result.StdOut){return $Result.StdOut|ConvertFrom-Json -Depth 50 -DateKind String};return $null}
function Write-JsonFile($Workspace,$Relative,$Value){$path=Join-Path $Workspace $Relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllText($path,(($Value|ConvertTo-Json -Depth 40)+"`n"),[Text.UTF8Encoding]::new($false))}
function Write-Contract($Workspace,$TaskId){$body=[ordered]@{schema_version='requirement-contract/v1';task_id=$TaskId;goal="Protect $TaskId.";acceptance=@('Protected action remains gated.');in_scope=@('v2 safety');out_of_scope=@('production execution');product_constraints=@('No prompt bypass.');product_decisions=@();unresolved_product_decisions=@();source_authority=@('current-user-message')};$contract=[ordered]@{};foreach($key in $body.Keys){$contract[$key]=$body[$key]};$contract.digest=Digest ($body|ConvertTo-Json -Depth 30 -Compress);$relative="contracts/$TaskId.json";Write-JsonFile $Workspace $relative $contract;return [pscustomobject]@{Path=$relative;Digest=$contract.digest}}
function Write-Approval($Workspace,$TaskId,$TaskVersion,$ContractDigest,$ApprovalId,$Type,[string[]]$Scopes,$Status='granted',$Expires=$null){$approval=[ordered]@{schema_version='approval/v1';approval_id=$ApprovalId;task_id=$TaskId;task_version=$TaskVersion;contract_digest=$ContractDigest;approval_type=$Type;approved_scope=$Scopes;approver='fixture-user';approved_at=[DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o');expires_at=$Expires;status=$Status};$relative="approval-inputs/$ApprovalId.json";Write-JsonFile $Workspace $relative $approval;return $relative}
function New-PassEvidence($Workspace,$TaskId,$TaskVersion,$ContractDigest){$recordRelative=".harness/evidence/$TaskId.txt";$recordPath=Join-Path $Workspace $recordRelative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $recordPath));[IO.File]::WriteAllText($recordPath,"pass`n",[Text.UTF8Encoding]::new($false));$recordDigest='sha256:'+((Get-FileHash $recordPath).Hash.ToLowerInvariant());$record=[ordered]@{type='command';command='pwsh -File tests/approval.ps1';cwd='.';exit_code=0;executed_at=[DateTimeOffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest=$recordDigest;covers=@('AC-1')};$document=[ordered]@{schema_version='evidence/v1';task_id=$TaskId;task_version=$TaskVersion;contract_digest=$ContractDigest;revision=('dirty:'+'0'*64);records=@($record);coverage=[ordered]@{satisfied=@('AC-1');not_verified=@();blocked=@()};gaps=@();conclusion='pass'};$relative="evidence-inputs/$TaskId.json";Write-JsonFile $Workspace $relative $document;$document.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $Workspace -ContractDigest $ContractDigest -Evidence $document -EvidenceInputPath $relative -EvidenceOutputPath "docs/tasks/$TaskId/evidence.json";Write-JsonFile $Workspace $relative $document;return $relative}
function Start-Task($Workspace,$TaskId,$Contract,$Profile='governed',[string[]]$Capabilities=@()){$args=@('create','-TaskId',$TaskId,'-Contract',$Contract.Path,'-Profile',$Profile,'-AsJson');if($Capabilities.Count){$args+=@('-Capabilities')+$Capabilities};$result=Invoke-Cli $Workspace $args;if($result.ExitCode){throw "create failed: $TaskId $($result.StdErr)"};return Read-Output $result}
function Start-VerifyingTask($Workspace,$TaskId,$Contract,[string[]]$Capabilities=@()){[void](Start-Task $Workspace $TaskId $Contract 'governed' $Capabilities);$running=Invoke-Cli $Workspace @('transition','-TaskId',$TaskId,'-ExpectedVersion','1','-To','running','-AsJson');$verifying=Invoke-Cli $Workspace @('transition','-TaskId',$TaskId,'-ExpectedVersion','2','-To','verifying','-AsJson');if($running.ExitCode-ne0-or$verifying.ExitCode-ne0){throw "verifying fixture failed: $TaskId running=[$($running.StdErr)] verifying=[$($verifying.StdErr)]"}}
function ConvertTo-LegacyJournal($Journal){$steps=@($Journal.steps|ForEach-Object{[ordered]@{id=[string]$_.id;relative_path=[string]$_.relative_path;action=[string]$_.action;before_digest=$_.before_digest;after_digest=$_.after_digest;content_base64=$_.content_base64}});return [ordered]@{transaction_id=[string]$Journal.transaction_id;operation=[string]$Journal.operation;task_id=[string]$Journal.task_id;expected_version=$Journal.expected_version;status=[string]$Journal.status;completed_steps=@($Journal.completed_steps);failed_step=[string]$Journal.failed_step;error=[string]$Journal.error;replay_command=[string]$Journal.replay_command;created_at=[string]$Journal.created_at;steps=$steps}}
function Convert-PendingToLegacy($Workspace,$Result){$match=[regex]::Match($Result.StdErr,'TransactionId=(txn_[0-9a-f]{32})');if($Result.ExitCode-ne2-or-not$match.Success){throw "legacy fixture did not create a pending journal: $($Result.StdErr)"};$id=$match.Groups[1].Value;$relative=".assistant/runtime/failed-writes/$id.json";$current=Get-Content -LiteralPath (Join-Path $Workspace $relative) -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String;Get-ChildItem -LiteralPath (Join-Path $Workspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue|Remove-Item -Force;$legacy=ConvertTo-LegacyJournal $current;Write-JsonFile $Workspace $relative $legacy;return [pscustomobject]@{TransactionId=$id;Path=$relative;Journal=$legacy}}
function Get-LegacyStep($Journal,$Id){$matches=@($Journal.steps|Where-Object{[string]$_.id-ceq$Id});if($matches.Count-ne1){throw "legacy fixture step is missing or ambiguous: $Id"};return $matches[0]}
function Set-LegacyStepContent($Step,$Content){$Step.content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes($Content));$Step.after_digest=Digest $Content}

$repoBefore=@(&git -C $RepoRoot status --porcelain --untracked-files=all);$temp=Join-Path ([IO.Path]::GetTempPath()) ('v2-approval-'+[guid]::NewGuid().ToString('N'));$workspace=Join-Path $temp 'workspace';[void][IO.Directory]::CreateDirectory($workspace)
try{
    [IO.File]::WriteAllText((Join-Path $workspace '.gitignore'),".assistant/runtime/`n.harness/evidence/`nevidence-inputs/`napproval-inputs/`ndocs/tasks/*/evidence.json`ndocs/tasks/*/plan.md`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false));git -C $workspace init -q;git -C $workspace config user.email harness@example.invalid;git -C $workspace config user.name Harness;git -C $workspace config core.autocrlf false;git -C $workspace add .;git -C $workspace commit -qm baseline
    foreach($file in @('scripts/lib/Harness.Approval.psm1','scripts/lib/Harness.ProtectedAction.psm1','scripts/lib/Harness.Governance.psm1','scripts/lib/Harness.TaskState.psm1','runtime-hooks/core/pretooluse.ps1','scripts/task.ps1','tests/verify-v2-approval.ps1')){$path=Join-Path $RepoRoot $file;$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($path,[ref]$tokens,[ref]$errors)|Out-Null;Check (@($errors).Count-eq0) "$file parses" "$file parse failed";Check (Test-FileHasUtf8Bom $path) "$file has UTF-8 BOM" "$file lacks UTF-8 BOM"}
    Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Approval.psm1') -Force;$approvalExports=@(Get-Command -Module Harness.Approval|Select-Object -ExpandProperty Name|Sort-Object);Check (@(Compare-Object @('Assert-HarnessTaskApproval','Resolve-HarnessApprovalInput') $approvalExports).Count-eq0) 'Approval exports are exact' 'Approval exports drifted';$approvalResolve=Get-Command Resolve-HarnessApprovalInput -Module Harness.Approval;$approvalAssert=Get-Command Assert-HarnessTaskApproval -Module Harness.Approval;Check (-not$approvalResolve.Parameters.ContainsKey('AsOf')-and-not$approvalAssert.Parameters.ContainsKey('AsOf')) 'Approval authorization timestamp override is module-private' 'Approval public API exposes a historical-time bypass';Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.ProtectedAction.psm1') -Force;$guardExports=@(Get-Command -Module Harness.ProtectedAction|Select-Object -ExpandProperty Name);Check ($guardExports.Count-eq1-and$guardExports[0]-ceq'Assert-HarnessProtectedAction') 'protected action export is exact' 'protected action exports drifted'
    $contracts=@{};foreach($id in @('critical-task','approval-task','approval-replay-task','approval-preclaim-task','approval-writer-preclaim-task','review-task','no-review-task','legacy-approval-prepared','legacy-approval-published','legacy-approval-status','legacy-approval-event','legacy-approval-path','legacy-approval-policy','legacy-verify-prepared','legacy-verify-published','legacy-verify-record','legacy-verify-plan','legacy-verify-approval')){$contracts[$id]=Write-Contract $workspace $id}
    [void](Start-Task $workspace 'approval-replay-task' $contracts['approval-replay-task'] 'governed' @('approval_required'));$approvalReplayInput=Write-Approval $workspace 'approval-replay-task' 2 $contracts['approval-replay-task'].Digest 'apr_replay_expiry' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddSeconds(6).ToString('o'));$approvalReplayCrash=Invoke-Cli $workspace @('approve','-TaskId','approval-replay-task','-ExpectedVersion','1','-Approval',$approvalReplayInput,'-AsJson') '1';$approvalReplayMatch=[regex]::Match($approvalReplayCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$approvalReplayId=$(if($approvalReplayMatch.Success){$approvalReplayMatch.Groups[1].Value}else{''});Start-Sleep -Seconds 7;$approvalReplay=$(if($approvalReplayId){Invoke-Cli $workspace @('replay','-TransactionId',$approvalReplayId,'-AsJson')}else{$approvalReplayCrash});$approvalReplayStatus=Read-Output (Invoke-Cli $workspace @('status','-TaskId','approval-replay-task','-AsJson'))
    Check ($approvalReplayCrash.ExitCode-eq2-and$approvalReplayMatch.Success-and$approvalReplay.ExitCode-eq0-and(Read-Output $approvalReplay).result-ceq'recovered'-and$approvalReplayStatus.task.version-eq2-and@($approvalReplayStatus.task.approvals)-ccontains'apr_replay_expiry') 'Approval replay evaluates expiry at the journal authorization time' 'Approval replay was stranded when authorization expired after publication began'
    [void](Start-Task $workspace 'approval-preclaim-task' $contracts['approval-preclaim-task'] 'governed' @('approval_required'));$approvalPreclaimInput=Write-Approval $workspace 'approval-preclaim-task' 2 $contracts['approval-preclaim-task'].Digest 'apr_preclaim_expiry' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddSeconds(6).ToString('o'));$approvalPreclaimCrash=Invoke-Cli $workspace @('approve','-TaskId','approval-preclaim-task','-ExpectedVersion','1','-Approval',$approvalPreclaimInput,'-AsJson') '' '1';$approvalPreclaimMatch=[regex]::Match($approvalPreclaimCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$approvalPreclaimId=$(if($approvalPreclaimMatch.Success){$approvalPreclaimMatch.Groups[1].Value}else{''});Start-Sleep -Seconds 7;$approvalPreclaimSnap=Snapshot $workspace;$approvalPreclaimReplay=$(if($approvalPreclaimId){Invoke-Cli $workspace @('replay','-TransactionId',$approvalPreclaimId,'-AsJson')}else{$approvalPreclaimCrash})
    Check ($approvalPreclaimCrash.ExitCode-eq2-and$approvalPreclaimMatch.Success-and$approvalPreclaimReplay.ExitCode-eq2-and$approvalPreclaimReplay.StdErr-match'Approval is expired') 'claim-free Approval replay revalidates expiry at recovery time' 'claim-free replay reused an expired authorization timestamp';Same $approvalPreclaimSnap (Snapshot $workspace) 'claim-free Approval expiry rejection is zero-write' 'claim-free Approval expiry rejection wrote state'
    [void](Start-Task $workspace 'approval-writer-preclaim-task' $contracts['approval-writer-preclaim-task'] 'governed' @('approval_required'));$approvalWriterInput=Write-Approval $workspace 'approval-writer-preclaim-task' 2 $contracts['approval-writer-preclaim-task'].Digest 'apr_writer_expiry' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddHours(1).ToString('o'));$approvalWriterPendingBefore=@(Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/failed-writes') -Filter 'txn_*.json' -File -ErrorAction SilentlyContinue|Select-Object -ExpandProperty BaseName);$approvalWriterHandle=Start-Cli $workspace @('approve','-TaskId','approval-writer-preclaim-task','-ExpectedVersion','1','-Approval',$approvalWriterInput,'-AsJson') '' '' '4000';$approvalWriterPending=$null;$approvalWriterDeadline=[datetime]::UtcNow.AddSeconds(10);while($null-eq$approvalWriterPending-and[datetime]::UtcNow-lt$approvalWriterDeadline){$approvalWriterPending=Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/failed-writes') -Filter 'txn_*.json' -File -ErrorAction SilentlyContinue|Where-Object{$approvalWriterPendingBefore -notcontains $_.BaseName}|Select-Object -First 1;if($null-eq$approvalWriterPending){Start-Sleep -Milliseconds 25}};$approvalWriterDocument=Get-Content -LiteralPath (Join-Path $workspace $approvalWriterInput) -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String;$approvalWriterDocument.expires_at=[DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o');Write-JsonFile $workspace $approvalWriterInput $approvalWriterDocument;$approvalWriterResult=Complete-Process $approvalWriterHandle;$approvalWriterStatus=Read-Output (Invoke-Cli $workspace @('status','-TaskId','approval-writer-preclaim-task','-AsJson'));$approvalWriterClaims=@(Get-ChildItem -LiteralPath (Join-Path $workspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$approvalWriterTarget=Join-Path $workspace '.assistant/runtime/tasks/approval-writer-preclaim-task/approvals/apr_writer_expiry.json'
    Check ($null-ne$approvalWriterPending-and$approvalWriterResult.ExitCode-eq2-and$approvalWriterResult.StdErr-match'Approval is expired'-and$approvalWriterStatus.task.version-eq1-and@($approvalWriterStatus.task.approvals).Count-eq0-and-not(Test-Path $approvalWriterTarget)-and$approvalWriterClaims.Count-eq0) 'normal writer revalidates Approval expiry before its first publication claim' 'normal writer published an Approval after the live authorization expired'

    [void](Start-Task $workspace 'legacy-approval-prepared' $contracts['legacy-approval-prepared'] 'governed' @('approval_required'))
    [void](Start-Task $workspace 'legacy-approval-published' $contracts['legacy-approval-published'] 'governed' @('approval_required'))
    $legacyApprovalPreparedExpiry=[DateTimeOffset]::UtcNow.AddSeconds(30).ToString('o')
    $legacyApprovalPreparedInput=Write-Approval $workspace 'legacy-approval-prepared' 2 $contracts['legacy-approval-prepared'].Digest 'apr_legacy_prepared' 'product' @('task:complete') 'granted' $legacyApprovalPreparedExpiry
    $legacyApprovalPreparedCrash=Invoke-Cli $workspace @('approve','-TaskId','legacy-approval-prepared','-ExpectedVersion','1','-Approval',$legacyApprovalPreparedInput,'-AsJson') '' '1'
    $legacyApprovalPrepared=Convert-PendingToLegacy $workspace $legacyApprovalPreparedCrash
    $legacyApprovalPublishedExpiry=[DateTimeOffset]::UtcNow.AddSeconds(30).ToString('o')
    $legacyApprovalPublishedInput=Write-Approval $workspace 'legacy-approval-published' 2 $contracts['legacy-approval-published'].Digest 'apr_legacy_published' 'product' @('task:complete') 'granted' $legacyApprovalPublishedExpiry
    $legacyApprovalPublishedCrash=Invoke-Cli $workspace @('approve','-TaskId','legacy-approval-published','-ExpectedVersion','1','-Approval',$legacyApprovalPublishedInput,'-AsJson') '1'
    $legacyApprovalPublished=Convert-PendingToLegacy $workspace $legacyApprovalPublishedCrash
    $legacyApprovalPublishedStep=Get-LegacyStep $legacyApprovalPublished.Journal 'approval'
    if($legacyApprovalPublishedCrash.StdErr-notmatch'injected task-state fault after step 1'-or@($legacyApprovalPublished.Journal.completed_steps).Count-ne1-or[string]$legacyApprovalPublished.Journal.completed_steps[0]-cne'approval'-or-not(Test-Path -LiteralPath (Join-Path $workspace ([string]$legacyApprovalPublishedStep.relative_path)) -PathType Leaf)){throw 'published legacy Approval fixture did not cross its first publication boundary'}
    Start-Sleep -Seconds 31
    $legacyApprovalPreparedSnap=Snapshot $workspace
    $legacyApprovalPreparedReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyApprovalPrepared.TransactionId,'-AsJson')
    Check ($legacyApprovalPreparedReplay.ExitCode-eq2-and$legacyApprovalPreparedReplay.StdErr-match'Approval is expired') 'claim-free legacy Approval replay uses the current authorization time' 'claim-free legacy Approval replay reused an expired authorization'
    Same $legacyApprovalPreparedSnap (Snapshot $workspace) 'claim-free legacy Approval expiry rejection is zero-write' 'claim-free legacy Approval expiry rejection wrote state'
    $legacyApprovalPublishedReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyApprovalPublished.TransactionId,'-AsJson')
    $legacyApprovalPublishedStatus=Read-Output (Invoke-Cli $workspace @('status','-TaskId','legacy-approval-published','-AsJson'))
    Check ($legacyApprovalPublishedReplay.ExitCode-eq0-and(Read-Output $legacyApprovalPublishedReplay).result-ceq'recovered'-and$legacyApprovalPublishedStatus.task.version-eq2-and@($legacyApprovalPublishedStatus.task.approvals)-ccontains'apr_legacy_published') 'published legacy Approval replay uses its journal authorization snapshot' 'published legacy Approval replay was stranded after later expiry'

    [void](Start-Task $workspace 'legacy-approval-status' $contracts['legacy-approval-status'] 'governed' @('approval_required'))
    $legacyApprovalStatusInput=Write-Approval $workspace 'legacy-approval-status' 2 $contracts['legacy-approval-status'].Digest 'apr_legacy_status' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddHours(1).ToString('o'))
    $legacyApprovalStatusCrash=Invoke-Cli $workspace @('approve','-TaskId','legacy-approval-status','-ExpectedVersion','1','-Approval',$legacyApprovalStatusInput,'-AsJson') '' '1'
    $legacyApprovalStatus=Convert-PendingToLegacy $workspace $legacyApprovalStatusCrash
    $legacyApprovalStatusStep=Get-LegacyStep $legacyApprovalStatus.Journal 'approval'
    $legacyApprovalStatusDocument=[Text.UTF8Encoding]::new($false).GetString([Convert]::FromBase64String([string]$legacyApprovalStatusStep.content_base64))|ConvertFrom-Json -AsHashtable -DateKind String
    $legacyApprovalStatusDocument.status='revoked'
    Set-LegacyStepContent $legacyApprovalStatusStep (($legacyApprovalStatusDocument|ConvertTo-Json -Depth 40)+"`n")
    Write-JsonFile $workspace $legacyApprovalStatus.Path $legacyApprovalStatus.Journal
    $legacyApprovalStatusSnap=Snapshot $workspace
    $legacyApprovalStatusReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyApprovalStatus.TransactionId,'-AsJson')
    Check ($legacyApprovalStatusReplay.ExitCode-eq2-and$legacyApprovalStatusReplay.StdErr-match'legacy approve transaction payload intent') 'legacy replay rejects a revoked embedded Approval' 'legacy replay accepted a revoked embedded Approval'
    Same $legacyApprovalStatusSnap (Snapshot $workspace) 'revoked legacy Approval rejection is zero-write' 'revoked legacy Approval rejection wrote state'
    Remove-Item -LiteralPath (Join-Path $workspace $legacyApprovalStatus.Path) -Force

    [void](Start-Task $workspace 'legacy-approval-event' $contracts['legacy-approval-event'] 'governed' @('approval_required'))
    $legacyApprovalEventInput=Write-Approval $workspace 'legacy-approval-event' 2 $contracts['legacy-approval-event'].Digest 'apr_legacy_event' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddHours(1).ToString('o'))
    $legacyApprovalEventCrash=Invoke-Cli $workspace @('approve','-TaskId','legacy-approval-event','-ExpectedVersion','1','-Approval',$legacyApprovalEventInput,'-AsJson') '' '1'
    $legacyApprovalEvent=Convert-PendingToLegacy $workspace $legacyApprovalEventCrash
    $legacyApprovalEventStep=Get-LegacyStep $legacyApprovalEvent.Journal 'event-log'
    $legacyApprovalEventContent=[Text.UTF8Encoding]::new($false).GetString([Convert]::FromBase64String([string]$legacyApprovalEventStep.content_base64))
    $legacyApprovalEventLines=@($legacyApprovalEventContent.Substring(0,$legacyApprovalEventContent.Length-1)-split"`n")
    $legacyApprovalEventDocument=$legacyApprovalEventLines[-1]|ConvertFrom-Json -AsHashtable -DateKind String
    $legacyApprovalEventDocument.payload.approval_id='apr_tampered'
    $legacyApprovalEventLines[-1]=$legacyApprovalEventDocument|ConvertTo-Json -Depth 40 -Compress
    Set-LegacyStepContent $legacyApprovalEventStep (($legacyApprovalEventLines-join"`n")+"`n")
    Write-JsonFile $workspace $legacyApprovalEvent.Path $legacyApprovalEvent.Journal
    $legacyApprovalEventSnap=Snapshot $workspace
    $legacyApprovalEventReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyApprovalEvent.TransactionId,'-AsJson')
    Check ($legacyApprovalEventReplay.ExitCode-eq2-and$legacyApprovalEventReplay.StdErr-match'legacy approve transaction payload intent') 'legacy replay rejects a mismatched Approval event binding' 'legacy replay accepted a mismatched Approval event binding'
    Same $legacyApprovalEventSnap (Snapshot $workspace) 'mismatched legacy Approval event rejection is zero-write' 'mismatched legacy Approval event rejection wrote state'
    Remove-Item -LiteralPath (Join-Path $workspace $legacyApprovalEvent.Path) -Force

    [void](Start-Task $workspace 'legacy-approval-path' $contracts['legacy-approval-path'] 'governed' @('approval_required'))
    $legacyApprovalPathInput=Write-Approval $workspace 'legacy-approval-path' 2 $contracts['legacy-approval-path'].Digest 'apr_legacy_path' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddHours(1).ToString('o'))
    $legacyApprovalPathCrash=Invoke-Cli $workspace @('approve','-TaskId','legacy-approval-path','-ExpectedVersion','1','-Approval',$legacyApprovalPathInput,'-AsJson') '' '1'
    $legacyApprovalPath=Convert-PendingToLegacy $workspace $legacyApprovalPathCrash
    $legacyApprovalPathStep=Get-LegacyStep $legacyApprovalPath.Journal 'approval'
    $legacyApprovalPathStep.relative_path='.assistant/runtime/tasks/legacy-approval-path/approvals/apr_wrong_path.json'
    $legacyApprovalPathEventStep=Get-LegacyStep $legacyApprovalPath.Journal 'event-log'
    $legacyApprovalPathEventContent=[Text.UTF8Encoding]::new($false).GetString([Convert]::FromBase64String([string]$legacyApprovalPathEventStep.content_base64))
    $legacyApprovalPathEventLines=@($legacyApprovalPathEventContent.Substring(0,$legacyApprovalPathEventContent.Length-1)-split"`n")
    $legacyApprovalPathEventDocument=$legacyApprovalPathEventLines[-1]|ConvertFrom-Json -AsHashtable -DateKind String
    $legacyApprovalPathEventDocument.payload.approval_path=[string]$legacyApprovalPathStep.relative_path
    $legacyApprovalPathEventLines[-1]=$legacyApprovalPathEventDocument|ConvertTo-Json -Depth 40 -Compress
    Set-LegacyStepContent $legacyApprovalPathEventStep (($legacyApprovalPathEventLines-join"`n")+"`n")
    Write-JsonFile $workspace $legacyApprovalPath.Path $legacyApprovalPath.Journal
    $legacyApprovalPathSnap=Snapshot $workspace
    $legacyApprovalPathReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyApprovalPath.TransactionId,'-AsJson')
    Check ($legacyApprovalPathReplay.ExitCode-eq2-and$legacyApprovalPathReplay.StdErr-match'legacy approve transaction payload intent') 'legacy replay rejects an Approval path not bound to its ID' 'legacy replay accepted an Approval path not bound to its ID'
    Same $legacyApprovalPathSnap (Snapshot $workspace) 'mismatched legacy Approval path rejection is zero-write' 'mismatched legacy Approval path rejection wrote state'
    Remove-Item -LiteralPath (Join-Path $workspace $legacyApprovalPath.Path) -Force

    [void](Start-Task $workspace 'legacy-approval-policy' $contracts['legacy-approval-policy'] 'governed' @('approval_required'))
    $legacyApprovalPolicyInput=Write-Approval $workspace 'legacy-approval-policy' 2 $contracts['legacy-approval-policy'].Digest 'apr_legacy_policy' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddHours(1).ToString('o'))
    $legacyApprovalPolicyCrash=Invoke-Cli $workspace @('approve','-TaskId','legacy-approval-policy','-ExpectedVersion','1','-Approval',$legacyApprovalPolicyInput,'-AsJson') '' '1'
    $legacyApprovalPolicy=Convert-PendingToLegacy $workspace $legacyApprovalPolicyCrash
    $legacyApprovalPolicyStep=Get-LegacyStep $legacyApprovalPolicy.Journal 'task-state'
    $legacyApprovalPolicyDocument=[Text.UTF8Encoding]::new($false).GetString([Convert]::FromBase64String([string]$legacyApprovalPolicyStep.content_base64))|ConvertFrom-Json -AsHashtable -DateKind String
    $legacyApprovalPolicyDocument.policies.approval_required=$false
    Set-LegacyStepContent $legacyApprovalPolicyStep (($legacyApprovalPolicyDocument|ConvertTo-Json -Depth 40)+"`n")
    Write-JsonFile $workspace $legacyApprovalPolicy.Path $legacyApprovalPolicy.Journal
    $legacyApprovalPolicySnap=Snapshot $workspace
    $legacyApprovalPolicyReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyApprovalPolicy.TransactionId,'-AsJson')
    Check ($legacyApprovalPolicyReplay.ExitCode-eq2-and$legacyApprovalPolicyReplay.StdErr-match'legacy approve transaction payload intent') 'legacy replay rejects Approval publication without an approval-required policy' 'legacy replay accepted Approval publication without an approval-required policy'
    Same $legacyApprovalPolicySnap (Snapshot $workspace) 'legacy Approval policy rejection is zero-write' 'legacy Approval policy rejection wrote state'
    Remove-Item -LiteralPath (Join-Path $workspace $legacyApprovalPolicy.Path) -Force

    Start-VerifyingTask $workspace 'legacy-verify-prepared' $contracts['legacy-verify-prepared']
    $legacyVerifyPreparedInput=New-PassEvidence $workspace 'legacy-verify-prepared' 3 $contracts['legacy-verify-prepared'].Digest
    $legacyVerifyPreparedCrash=Invoke-Cli $workspace @('verify','-TaskId','legacy-verify-prepared','-ExpectedVersion','3','-Evidence',$legacyVerifyPreparedInput,'-AsJson') '' '1'
    $legacyVerifyPrepared=Convert-PendingToLegacy $workspace $legacyVerifyPreparedCrash
    $legacyVerifyPreparedSnap=Snapshot $workspace
    $legacyVerifyPreparedReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyVerifyPrepared.TransactionId,'-AsJson')
    Check ($legacyVerifyPreparedReplay.ExitCode-eq2-and$legacyVerifyPreparedReplay.StdErr-match'original Evidence input path is unavailable') 'claim-free legacy verify fails closed without its original Evidence input path' 'claim-free legacy verify reused an unverifiable Evidence snapshot'
    Same $legacyVerifyPreparedSnap (Snapshot $workspace) 'claim-free legacy verify rejection is zero-write' 'claim-free legacy verify rejection wrote state'

    Start-VerifyingTask $workspace 'legacy-verify-published' $contracts['legacy-verify-published']
    $legacyVerifyPublishedInput=New-PassEvidence $workspace 'legacy-verify-published' 3 $contracts['legacy-verify-published'].Digest
    $legacyVerifyPublishedCrash=Invoke-Cli $workspace @('verify','-TaskId','legacy-verify-published','-ExpectedVersion','3','-Evidence',$legacyVerifyPublishedInput,'-AsJson') '1'
    $legacyVerifyPublished=Convert-PendingToLegacy $workspace $legacyVerifyPublishedCrash
    $legacyVerifyPublishedReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyVerifyPublished.TransactionId,'-AsJson')
    $legacyVerifyPublishedStatus=Read-Output (Invoke-Cli $workspace @('status','-TaskId','legacy-verify-published','-AsJson'))
    Check ($legacyVerifyPublishedReplay.ExitCode-eq0-and(Read-Output $legacyVerifyPublishedReplay).result-ceq'recovered'-and$legacyVerifyPublishedStatus.task.status-ceq'done') 'published legacy verify revalidates and completes from its pinned Evidence' 'published legacy verify could not complete after safe revalidation'

    Start-VerifyingTask $workspace 'legacy-verify-record' $contracts['legacy-verify-record']
    $legacyVerifyRecordInput=New-PassEvidence $workspace 'legacy-verify-record' 3 $contracts['legacy-verify-record'].Digest
    $legacyVerifyRecordCrash=Invoke-Cli $workspace @('verify','-TaskId','legacy-verify-record','-ExpectedVersion','3','-Evidence',$legacyVerifyRecordInput,'-AsJson') '1'
    $legacyVerifyRecord=Convert-PendingToLegacy $workspace $legacyVerifyRecordCrash
    [IO.File]::WriteAllText((Join-Path $workspace '.harness/evidence/legacy-verify-record.txt'),"tampered`n",[Text.UTF8Encoding]::new($false))
    $legacyVerifyRecordSnap=Snapshot $workspace
    $legacyVerifyRecordReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyVerifyRecord.TransactionId,'-AsJson')
    Check ($legacyVerifyRecordReplay.ExitCode-eq2-and$legacyVerifyRecordReplay.StdErr-match'Evidence record digest mismatch') 'published legacy verify revalidates live record digests' 'published legacy verify ignored changed record evidence'
    Same $legacyVerifyRecordSnap (Snapshot $workspace) 'legacy verify record rejection is zero-write' 'legacy verify record rejection wrote state'

    Start-VerifyingTask $workspace 'legacy-verify-plan' $contracts['legacy-verify-plan'] @('plan_required')
    $legacyVerifyPlanPath=Join-Path $workspace 'docs/tasks/legacy-verify-plan/plan.md'
    $legacyVerifyPlanText=[IO.File]::ReadAllText($legacyVerifyPlanPath,[Text.Encoding]::UTF8).Replace('<fill-goal>','Implement the confirmed Contract.').Replace('<fill-scope>','Only governed v2 artifacts.').Replace('<fill-implementation>','Apply the smallest policy-required change.').Replace('<fill-verification>','Run the declared Evidence commands.').Replace('<fill-rollback>','Revert the governed change.')
    [IO.File]::WriteAllText($legacyVerifyPlanPath,$legacyVerifyPlanText,[Text.UTF8Encoding]::new($false))
    $legacyVerifyPlanInput=New-PassEvidence $workspace 'legacy-verify-plan' 3 $contracts['legacy-verify-plan'].Digest
    $legacyVerifyPlanCrash=Invoke-Cli $workspace @('verify','-TaskId','legacy-verify-plan','-ExpectedVersion','3','-Evidence',$legacyVerifyPlanInput,'-AsJson') '1'
    $legacyVerifyPlan=Convert-PendingToLegacy $workspace $legacyVerifyPlanCrash
    [IO.File]::WriteAllText($legacyVerifyPlanPath,"tampered`n",[Text.UTF8Encoding]::new($false))
    $legacyVerifyPlanSnap=Snapshot $workspace
    $legacyVerifyPlanReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyVerifyPlan.TransactionId,'-AsJson')
    Check ($legacyVerifyPlanReplay.ExitCode-eq2-and$legacyVerifyPlanReplay.StdErr-match'plan') 'published legacy verify revalidates governance artifacts' 'published legacy verify ignored changed governance artifacts'
    Same $legacyVerifyPlanSnap (Snapshot $workspace) 'legacy verify governance rejection is zero-write' 'legacy verify governance rejection wrote state'

    Start-VerifyingTask $workspace 'legacy-verify-approval' $contracts['legacy-verify-approval'] @('approval_required')
    $legacyVerifyApprovalInput=Write-Approval $workspace 'legacy-verify-approval' 4 $contracts['legacy-verify-approval'].Digest 'apr_legacy_verify' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddHours(1).ToString('o'))
    $legacyVerifyApprovalImport=Invoke-Cli $workspace @('approve','-TaskId','legacy-verify-approval','-ExpectedVersion','3','-Approval',$legacyVerifyApprovalInput,'-AsJson')
    $legacyVerifyApprovalValue=Read-Output $legacyVerifyApprovalImport
    $legacyVerifyApprovalEvidence=New-PassEvidence $workspace 'legacy-verify-approval' 4 $contracts['legacy-verify-approval'].Digest
    $legacyVerifyApprovalCrash=Invoke-Cli $workspace @('verify','-TaskId','legacy-verify-approval','-ExpectedVersion','4','-Evidence',$legacyVerifyApprovalEvidence,'-AsJson') '1'
    $legacyVerifyApproval=Convert-PendingToLegacy $workspace $legacyVerifyApprovalCrash
    Remove-Item -LiteralPath (Join-Path $workspace $legacyVerifyApprovalValue.approval_path) -Force
    $legacyVerifyApprovalSnap=Snapshot $workspace
    $legacyVerifyApprovalReplay=Invoke-Cli $workspace @('replay','-TransactionId',$legacyVerifyApproval.TransactionId,'-AsJson')
    Check ($legacyVerifyApprovalImport.ExitCode-eq0-and$legacyVerifyApprovalReplay.ExitCode-eq2-and$legacyVerifyApprovalReplay.StdErr-match'task Approval|does not exist') 'published legacy verify revalidates completion Approval' 'published legacy verify completed without its required Approval'
    Same $legacyVerifyApprovalSnap (Snapshot $workspace) 'legacy verify Approval rejection is zero-write' 'legacy verify Approval rejection wrote state'

    [void](Start-Task $workspace 'critical-task' $contracts['critical-task'] 'critical');$snap=Snapshot $workspace;$blocked=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','1','-CommandText','DELETE FROM customer','-Environment','production','-DryRun','-UserInstruction','direct execute')
    Check ($blocked.ExitCode-eq2-and-not$blocked.StdOut-and$blocked.StdErr-match'no current granted Approval') 'unapproved Critical action fails closed despite direct instruction' 'unapproved Critical action was allowed';Same $snap (Snapshot $workspace) 'Critical rejection is zero-write' 'Critical rejection wrote state'
    $scopes=@('rule:production-database-destructive',('command_digest:'+(Digest 'DELETE FROM customer')),'environment:production','dry-run:true');$input=Write-Approval $workspace 'critical-task' 2 $contracts['critical-task'].Digest 'apr_production' 'production' $scopes;$approved=Invoke-Cli $workspace @('approve','-TaskId','critical-task','-ExpectedVersion','1','-Approval',$input,'-AsJson');$approvedValue=Read-Output $approved
    Check ($approved.ExitCode-eq0-and$approvedValue.task.version-eq2-and$approvedValue.task.approvals[0]-ceq'apr_production'-and(Test-Path (Join-Path $workspace $approvedValue.approval_path))) 'external Approval import is transactional and version-bound' 'Approval import failed'
    $allowed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DELETE FROM customer','-Environment','production','-DryRun','-UserInstruction','direct execute');$allowedValue=Read-Output $allowed;$storedApproval=Get-Content -LiteralPath (Join-Path $workspace $approvedValue.approval_path) -Raw -Encoding utf8|ConvertFrom-Json;Check ($allowed.ExitCode-eq0-and$allowedValue.protected-and$allowedValue.approval_id-ceq'apr_production') 'exact approved Critical dry-run is allowed' ("approved Critical dry-run was rejected: exit={0} stderr=[{1}] approved_scopes=[{2}]" -f $allowed.ExitCode,$allowed.StdErr,(@($storedApproval.approved_scope)-join ','))
    $changed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DROP TABLE customer','-Environment','production','-DryRun');Check ($changed.ExitCode-eq2-and$changed.StdErr-match'no current granted Approval') 'expanded command scope invalidates Approval' 'expanded command scope reused stale Approval'
    $noDryRun=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DELETE FROM customer','-Environment','production');Check ($noDryRun.ExitCode-eq2-and$noDryRun.StdErr-match'dry-run') 'Critical destructive command requires dry-run' 'Critical command bypassed dry-run'
    $contractPath=Join-Path $workspace $contracts['critical-task'].Path;$contractText=[IO.File]::ReadAllText($contractPath,[Text.Encoding]::UTF8);$changedContract=$contractText|ConvertFrom-Json -AsHashtable -DateKind String;$changedContract.goal='Changed after approval.';Write-JsonFile $workspace $contracts['critical-task'].Path $changedContract;try{$changedContractResult=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DELETE FROM customer','-Environment','production','-DryRun')}finally{[IO.File]::WriteAllText($contractPath,$contractText,[Text.UTF8Encoding]::new($false))};Check ($changedContractResult.ExitCode-eq2-and$changedContractResult.StdErr-match'Contract digest is stale') 'changed Contract content invalidates Approval' 'changed Contract content reused Approval'
    $transition=Invoke-Cli $workspace @('transition','-TaskId','critical-task','-ExpectedVersion','2','-To','running','-AsJson');$stale=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','3','-CommandText','DELETE FROM customer','-Environment','production','-DryRun');Check ($transition.ExitCode-eq0-and$stale.ExitCode-eq2-and$stale.StdErr-match'no current granted Approval') 'task version change invalidates Approval' 'stale version Approval remained usable'
    $readOnlySnap=Snapshot $workspace;$readOnly=Invoke-Hook $workspace @('-SessionMode','read-only','-ActionMode','write','-ChangedPaths','src/view.ps1','-UserInstruction','direct execute');Check ($readOnly.ExitCode-eq2-and$readOnly.StdErr-match'read-only session') 'read-only session cannot invoke write tool' 'read-only session invoked write tool';Same $readOnlySnap (Snapshot $workspace) 'read-only denial is zero-write' 'read-only denial wrote state'
    $escape=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','../outside.ps1');Check ($escape.ExitCode-eq2-and$escape.StdErr-match'escapes WorkspaceRoot') 'write path escape is rejected' 'write path escape was allowed'
    $ordinary=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','src/view.ps1');Check ($ordinary.ExitCode-eq0-and-not(Read-Output $ordinary).protected) 'ordinary contained write has no protected ceremony' 'ordinary write was over-gated'
    [void](Start-Task $workspace 'no-review-task' $contracts['no-review-task']);$missingReview=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','no-review-task','-ExpectedVersion','1','-ChangedPaths','src/auth/authorize.ps1');Check ($missingReview.ExitCode-eq2-and$missingReview.StdErr-match'independent review policy') 'authorization path requires independent review capability' 'authorization path bypassed review policy'
    [void](Start-Task $workspace 'review-task' $contracts['review-task'] 'governed' @('independent_review_required'));$reviewAllowed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','review-task','-ExpectedVersion','1','-ChangedPaths','src/auth/authorize.ps1');Check ($reviewAllowed.ExitCode-eq0-and(Read-Output $reviewAllowed).protected) 'governed authorization write with required review policy passes preflight' 'valid authorization preflight failed'
    $conflictingOverlay=[ordered]@{schema_version='protected-actions-overlay/v1';rules=@([ordered]@{id='project-payment-architecture';match=[ordered]@{path_globs=@('**/payments/**');environment='production'};requires_profile='critical';requires_approval='architecture';requires_dry_run=$false;requires_independent_review=$true})};Write-JsonFile $workspace '.assistant/policies/protected-actions.local.json' $conflictingOverlay;$snap=Snapshot $workspace
    $conflictingTypes=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','3','-CommandText','DELETE FROM customer','-ChangedPaths','src/payments/charge.ps1','-Environment','production','-DryRun');Check ($conflictingTypes.ExitCode-eq2-and$conflictingTypes.StdErr-match'conflicting Approval types') 'different matched Approval types fail closed before lookup' 'different matched Approval types selected one rule by order';Same $snap (Snapshot $workspace) 'conflicting Approval type rejection is zero-write' 'conflicting Approval type rejection wrote state'
    $sameTypeOverlay=[ordered]@{schema_version='protected-actions-overlay/v1';rules=@([ordered]@{id='project-payment-production';match=[ordered]@{path_globs=@('**/payments/**');environment='production'};requires_profile='critical';requires_approval='production';requires_dry_run=$false;requires_independent_review=$true})};Write-JsonFile $workspace '.assistant/policies/protected-actions.local.json' $sameTypeOverlay
    $multiScopes=@('rule:production-database-destructive','rule:project-payment-production',('command_digest:'+(Digest 'DELETE FROM customer')),'environment:production','path:src/payments/charge.ps1','dry-run:true');$multiInput=Write-Approval $workspace 'critical-task' 4 $contracts['critical-task'].Digest 'apr_multi_production' 'production' $multiScopes;$multiApproved=Invoke-Cli $workspace @('approve','-TaskId','critical-task','-ExpectedVersion','3','-Approval',$multiInput,'-AsJson');$multiAllowed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','4','-CommandText','DELETE FROM customer','-ChangedPaths','src/payments/charge.ps1','-Environment','production','-DryRun');$multiValue=Read-Output $multiAllowed
    Check ($multiApproved.ExitCode-eq0-and$multiAllowed.ExitCode-eq0-and$multiValue.approval_id-ceq'apr_multi_production'-and@($multiValue.matched_rules)-ccontains'production-database-destructive'-and@($multiValue.matched_rules)-ccontains'project-payment-production'-and@($multiValue.required_scopes)-ccontains'rule:production-database-destructive'-and@($multiValue.required_scopes)-ccontains'rule:project-payment-production') 'same Approval type across rules merges scopes under one Approval' 'same Approval type across rules did not preserve merged scopes'
    $overlay=[ordered]@{schema_version='protected-actions-overlay/v1';rules=@([ordered]@{id='project-payment-path';match=[ordered]@{path_globs=@('**/payments/**');environment='staging'};requires_profile='governed';requires_approval='none';requires_dry_run=$false;requires_independent_review=$true})};Write-JsonFile $workspace '.assistant/policies/protected-actions.local.json' $overlay
    $overlayAllowed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','review-task','-ExpectedVersion','1','-ChangedPaths','src/payments/charge.ps1','-Environment','staging');$overlayValue=Read-Output $overlayAllowed;Check ($overlayAllowed.ExitCode-eq0-and$overlayValue.protected-and@($overlayValue.matched_rules)-ccontains'project-payment-path') 'project overlay classifies an environment-specific protected path' 'valid project protected-action overlay was not enforced'
    $overlay.rules[0].id='authorization-path-change';Write-JsonFile $workspace '.assistant/policies/protected-actions.local.json' $overlay;$collision=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','src/view.ps1');Check ($collision.ExitCode-eq2-and$collision.StdErr-match'collides') 'overlay cannot replace a core protected rule id' 'overlay replaced a core protected rule'
    [IO.File]::WriteAllText((Join-Path $workspace '.assistant/policies/protected-actions.local.json'),'{"broken":',[Text.UTF8Encoding]::new($false));$malformedOverlay=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','src/view.ps1');Check ($malformedOverlay.ExitCode-eq2-and$malformedOverlay.StdErr-match'overlay is invalid') 'malformed project overlay fails closed for writes' 'malformed project overlay allowed a write';Remove-Item (Join-Path $workspace '.assistant/policies/protected-actions.local.json') -Force
    $badRepo=Join-Path $temp 'bad-repo';[void][IO.Directory]::CreateDirectory((Join-Path $badRepo 'policies'));$badPolicyPath=Join-Path $badRepo 'policies/protected-actions.json';[IO.File]::WriteAllText($badPolicyPath,'{"broken":', [Text.UTF8Encoding]::new($false));$badPolicy=$false;try{Assert-HarnessProtectedAction -RepoRoot $badRepo -WorkspaceRoot $workspace -SessionMode write -ActionMode write -ChangedPaths @('src/view.ps1')|Out-Null}catch{$badPolicy=$_.Exception.Message-match'policy is invalid'};Check $badPolicy 'malformed protected policy fails closed' 'malformed protected policy allowed write';Remove-Item $badPolicyPath;$missingPolicy=$false;try{Assert-HarnessProtectedAction -RepoRoot $badRepo -WorkspaceRoot $workspace -SessionMode write -ActionMode write -ChangedPaths @('src/view.ps1')|Out-Null}catch{$missingPolicy=$_.Exception.Message-match'policy is unavailable'};Check $missingPolicy 'unavailable protected policy fails closed for write' 'unavailable protected policy allowed write';$readWithoutPolicy=Assert-HarnessProtectedAction -RepoRoot $badRepo -WorkspaceRoot $workspace -SessionMode read-only -ActionMode read;Check $readWithoutPolicy.allowed 'ordinary read continues without protected policy' 'ordinary read required protected policy'
    $hookOnly=Join-Path $temp 'hook-only';[void][IO.Directory]::CreateDirectory((Join-Path $hookOnly 'runtime-hooks/core'));Copy-Item $hookScript (Join-Path $hookOnly 'runtime-hooks/core/pretooluse.ps1');$missingHookModule=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','src/view.ps1') $hookOnly (Join-Path $hookOnly 'runtime-hooks/core/pretooluse.ps1');Check ($missingHookModule.ExitCode-eq2-and$missingHookModule.StdErr-match'module is unavailable') 'unavailable safety module fails closed for write' 'unavailable safety module allowed write';$readWithoutModule=Invoke-Hook $workspace @('-SessionMode','read-only','-ActionMode','read') $hookOnly (Join-Path $hookOnly 'runtime-hooks/core/pretooluse.ps1');Check ($readWithoutModule.ExitCode-eq0-and(Read-Output $readWithoutModule).allowed) 'ordinary read continues without safety module' 'ordinary read required safety module'
    [void](Start-Task $workspace 'approval-task' $contracts['approval-task'] 'governed' @('approval_required'));[void](Invoke-Cli $workspace @('transition','-TaskId','approval-task','-ExpectedVersion','1','-To','running','-AsJson'));[void](Invoke-Cli $workspace @('transition','-TaskId','approval-task','-ExpectedVersion','2','-To','verifying','-AsJson'));$evidence=New-PassEvidence $workspace 'approval-task' 3 $contracts['approval-task'].Digest;$snap=Snapshot $workspace;$missing=Invoke-Cli $workspace @('verify','-TaskId','approval-task','-ExpectedVersion','3','-Evidence',$evidence,'-AsJson');Check ($missing.ExitCode-eq2-and$missing.StdErr-match'no current granted Approval') 'approval_required task cannot complete without Approval' 'approval_required task completed without Approval';Same $snap (Snapshot $workspace) 'missing completion Approval is zero-write' 'missing completion Approval wrote state'
    $revokedInput=Write-Approval $workspace 'approval-task' 4 $contracts['approval-task'].Digest 'apr_revoked' 'product' @('task:complete') 'revoked';$snap=Snapshot $workspace;$revoked=Invoke-Cli $workspace @('approve','-TaskId','approval-task','-ExpectedVersion','3','-Approval',$revokedInput,'-AsJson');Check ($revoked.ExitCode-eq2-and$revoked.StdErr-match'only a granted') 'revoked Approval cannot be imported' 'revoked Approval was imported';Same $snap (Snapshot $workspace) 'revoked Approval rejection is zero-write' 'revoked Approval rejection wrote state';$expiredInput=Write-Approval $workspace 'approval-task' 4 $contracts['approval-task'].Digest 'apr_expired' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o'));$snap=Snapshot $workspace;$expired=Invoke-Cli $workspace @('approve','-TaskId','approval-task','-ExpectedVersion','3','-Approval',$expiredInput,'-AsJson');Check ($expired.ExitCode-eq2-and$expired.StdErr-match'Approval is expired') 'expired Approval cannot be imported' 'expired Approval was imported';Same $snap (Snapshot $workspace) 'expired Approval rejection is zero-write' 'expired Approval rejection wrote state'
    $validInput=Write-Approval $workspace 'approval-task' 4 $contracts['approval-task'].Digest 'apr_complete' 'product' @('task:complete');$grant=Invoke-Cli $workspace @('approve','-TaskId','approval-task','-ExpectedVersion','3','-Approval',$validInput,'-AsJson');$evidence=New-PassEvidence $workspace 'approval-task' 4 $contracts['approval-task'].Digest;$verified=Invoke-Cli $workspace @('verify','-TaskId','approval-task','-ExpectedVersion','4','-Evidence',$evidence,'-AsJson');$verifiedValue=Read-Output $verified;Check ($grant.ExitCode-eq0-and$verified.ExitCode-eq0-and$verifiedValue.task.status-ceq'done') 'current granted Approval permits policy-complete Evidence' 'valid completion Approval did not permit done'
}finally{if(Test-Path $temp){Remove-DirectoryWithRetry -Path $temp}}
$repoAfter=@(&git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count-eq0) 'Approval verifier performs no repository writes' 'Approval verifier changed repository state'
foreach($item in $script:passes){"[PASS] $item"};foreach($item in $script:failures){"[FAIL] $item"};if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:passes.Count) checks)";exit 0
