[CmdletBinding()]
param([string]$RepoRoot = '')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($RepoRoot)) { $RepoRoot = Split-Path -Parent $PSScriptRoot }
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $PSScriptRoot 'fixture-test-common.ps1')

$script:checks = [Collections.Generic.List[string]]::new()
$script:failures = [Collections.Generic.List[string]]::new()
function Check($Condition,[string]$Pass,[string]$Fail) { if ($Condition) { $script:checks.Add($Pass) } else { $script:failures.Add($Fail) } }
function Digest([string]$Text) { return 'sha256:' + [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.UTF8Encoding]::new($false).GetBytes($Text))).ToLowerInvariant() }
function Copy-Document([Collections.IDictionary]$Value) { return ($Value|ConvertTo-Json -Depth 50 -Compress)|ConvertFrom-Json -AsHashtable -Depth 50 -DateKind String }
function Write-Json([string]$Path,$Value) { [void][IO.Directory]::CreateDirectory((Split-Path -Parent $Path));[IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 50 -Compress),[Text.UTF8Encoding]::new($false)) }
function Write-Decision([string]$Workspace,$Value) { Write-Json (Join-Path $Workspace '.assistant\runtime\protocol-default.json') $Value }
function Snapshot([string]$Root) { return @(Get-ChildItem -LiteralPath $Root -Force -Recurse|ForEach-Object{if($_.PSIsContainer){'D|'+$_.FullName}else{'F|'+$_.FullName+'|'+(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash}}|Sort-Object) }
function Same($Before,$After,[string]$Pass,[string]$Fail) { Check (@(Compare-Object @($Before) @($After)).Count-eq0) $Pass $Fail }
function Complete($Handle,[int]$Timeout=30000) { if(-not$Handle.Process.WaitForExit($Timeout)){$Handle.Process.Kill($true);throw 'fixture process timeout'};$value=[pscustomobject]@{ExitCode=$Handle.Process.ExitCode;StdOut=$Handle.StdOut.GetAwaiter().GetResult().Trim();StdErr=$Handle.StdErr.GetAwaiter().GetResult().Trim()};$Handle.Process.Dispose();return $value }
function Get-FileState([string[]]$Paths) { return @($Paths|ForEach-Object{if(Test-Path -LiteralPath $_ -PathType Leaf){'F|'+$_+'|'+(Get-FileHash -LiteralPath $_ -Algorithm SHA256).Hash}elseif(Test-Path -LiteralPath $_ -PathType Container){'D|'+$_}else{'M|'+$_}}) }
$script:fixtureUserProfile='';$script:fixtureWorkingDirectory=''
function Start-FixtureRepoProcess([string]$ScriptPath,[string[]]$Arguments) {
    $names=@('DEV_HARNESS_WORKSPACE_ROOT','CLAUDE_DEV_HARNESS_WORKSPACE_ROOT','WORKSPACE_ROOT','CODEX_HOME','HOST_BENCHMARK_CODEX_HOME','GIT_DIR','GIT_WORK_TREE','GIT_COMMON_DIR')
    $saved=[ordered]@{};$present=[Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    try {
        foreach($name in $names){if(Test-Path -LiteralPath "Env:$name"){[void]$present.Add($name);$saved[$name]=(Get-Item -LiteralPath "Env:$name").Value};Remove-Item -LiteralPath "Env:$name" -ErrorAction Ignore}
        return Start-RepoProcess -UserProfile $script:fixtureUserProfile -WorkingDirectory $script:fixtureWorkingDirectory -ScriptPath $ScriptPath -Arguments $Arguments
    } finally {
        foreach($name in $names){if($present.Contains($name)){Set-Item -LiteralPath "Env:$name" -Value ([string]$saved[$name])}else{Remove-Item -LiteralPath "Env:$name" -ErrorAction Ignore}}
    }
}
function Invoke-Script([string]$Path,[string[]]$Arguments,[AllowNull()][string]$Protocol=$null) {
    $prior=[Environment]::GetEnvironmentVariable('HARNESS_PROTOCOL',[EnvironmentVariableTarget]::Process)
    try { if($null-eq$Protocol){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$Protocol};return Complete (Start-FixtureRepoProcess -ScriptPath $Path -Arguments $Arguments) }
    finally { if($null-eq$prior){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$prior} }
}
function Resolve-Protocol([string]$Workspace,[string]$TaskId='',[string]$Requested='auto') { return & $script:protocolModule {param($Root,$Work,$Task,$Mode)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -TaskId $Task -RequestedProtocol $Mode} $RepoRoot $Workspace $TaskId $Requested }
function New-Host([string]$Version,$Telemetry='unavailable') { return [ordered]@{schema_version='harness-host-capabilities/v1';product='codex';actual_version=$Version;observation_status=$(if($Version-ceq'unknown'){'unavailable'}else{'partial'});capabilities=[ordered]@{workspace_protocol_config=$true;structured_tool_events='unavailable';request_send_telemetry=$Telemetry;desktop_profile_isolation='unavailable';hook_status_query='unavailable'}} }
function New-V2Task([string]$TaskId) { $now=[datetimeoffset]::UtcNow.ToString('o');return [ordered]@{schema_version='task-state/v2';task_id=$TaskId;version=1;status='ready';identity='existing';intent='write';requirement_state='clear';execution_profile='direct';persistence='ephemeral';policies=[ordered]@{plan_required=$false;approval_required=$false;rollback_required=$false;independent_review_required=$false;verification_required=$true};created_at=$now;updated_at=$now} }
function Write-Contract([string]$Workspace,[string]$TaskId) { $body=[ordered]@{schema_version='requirement-contract/v1';task_id=$TaskId;goal="Verify $TaskId.";acceptance=@('AC-1');in_scope=@('fixture');out_of_scope=@('production');product_constraints=@('deterministic');product_decisions=@();unresolved_product_decisions=@();source_authority=@('current-user-message')};$doc=[ordered]@{};foreach($key in $body.Keys){$doc[$key]=$body[$key]};$doc.digest=Digest ($body|ConvertTo-Json -Depth 20 -Compress);$relative="contracts/$TaskId.json";Write-Json (Join-Path $Workspace $relative) $doc;return [pscustomobject]@{Path=$relative;Digest=$doc.digest} }
function Invoke-Task([string]$Workspace,[string[]]$Arguments) { return Invoke-Script -Path (Join-Path $RepoRoot 'scripts\task.ps1') -Arguments ($Arguments+@('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$Workspace)) -Protocol v2 }
function Read-Output($Result) { if([string]::IsNullOrWhiteSpace($Result.StdOut)){return $null};return $Result.StdOut|ConvertFrom-Json -AsHashtable -Depth 50 -DateKind String }
function Write-Approval([string]$Workspace,[string]$TaskId,[int]$TaskVersion,[string]$ContractDigest) { $relative="approval-inputs/$TaskId.json";$doc=[ordered]@{schema_version='approval/v1';approval_id=('apr_'+$TaskId.Replace('-','_'));task_id=$TaskId;task_version=$TaskVersion;contract_digest=$ContractDigest;approval_type='product';approved_scope=@('task:complete');approver='fixture-user';approved_at=[datetimeoffset]::UtcNow.AddMinutes(-1).ToString('o');expires_at=$null;status='granted'};Write-Json (Join-Path $Workspace $relative) $doc;return $relative }
function Write-Evidence([string]$Workspace,[string]$TaskId,[int]$TaskVersion,[string]$ContractDigest) { $recordRelative=".harness/evidence/$TaskId.txt";$recordPath=Join-Path $Workspace $recordRelative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $recordPath));[IO.File]::WriteAllText($recordPath,"pass`n",[Text.UTF8Encoding]::new($false));$relative="evidence-inputs/$TaskId.json";$doc=[ordered]@{schema_version='evidence/v1';task_id=$TaskId;task_version=$TaskVersion;contract_digest=$ContractDigest;revision=('dirty:'+'0'*64);records=@([ordered]@{type='command';command='pwsh -File tests/fixture.ps1';cwd='.';exit_code=0;executed_at=[datetimeoffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest='sha256:'+((Get-FileHash -LiteralPath $recordPath -Algorithm SHA256).Hash.ToLowerInvariant());covers=@('AC-1')});coverage=[ordered]@{satisfied=@('AC-1');not_verified=@();blocked=@()};gaps=@();conclusion='pass'};Write-Json (Join-Path $Workspace $relative) $doc;$doc.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $Workspace -ContractDigest $ContractDigest -Evidence $doc -EvidenceInputPath $relative -EvidenceOutputPath "docs/tasks/$TaskId/evidence.json";Write-Json (Join-Path $Workspace $relative) $doc;return $relative }

$repoBefore=@(& git -C $RepoRoot status --porcelain --untracked-files=all)
$callerUserProfile=$env:USERPROFILE
$callerStatePaths=@((Join-Path $callerUserProfile '.dev-harness\install-registry.json'),(Join-Path $callerUserProfile '.dev-harness\install-transaction.json'),(Join-Path $callerUserProfile '.dev-harness\uninstall-transaction.json'),(Join-Path $callerUserProfile '.codex\managed_config.toml'),(Join-Path $callerUserProfile '.codex\AGENTS.md'),(Join-Path $callerUserProfile '.claude\CLAUDE.md'),(Join-Path $callerUserProfile '.agents\AGENTS.md'))
$callerStateBefore=Get-FileState $callerStatePaths
$temp=Join-Path $RepoRoot ('tmp\runtime-qualification-decoupling-'+[guid]::NewGuid().ToString('N'))
try {
    [void][IO.Directory]::CreateDirectory($temp)
    $script:fixtureUserProfile=Join-Path $temp 'fixture-user-profile';$script:fixtureWorkingDirectory=Join-Path $temp 'fixture-cwd';[void][IO.Directory]::CreateDirectory($script:fixtureUserProfile);[void][IO.Directory]::CreateDirectory($script:fixtureWorkingDirectory)
    $environmentProbePath=Join-Path $temp 'probe-child-environment.ps1';[IO.File]::WriteAllText($environmentProbePath,'[pscustomobject]@{USERPROFILE=$env:USERPROFILE;HOME=$env:HOME}|ConvertTo-Json -Compress',[Text.UTF8Encoding]::new($true));$environmentProbe=Complete (Start-FixtureRepoProcess -ScriptPath $environmentProbePath -Arguments @());$environmentObservation=$environmentProbe.StdOut|ConvertFrom-Json
    Check ($environmentProbe.ExitCode-eq0-and(Get-NormalizedPath $environmentObservation.USERPROFILE)-eq(Get-NormalizedPath $script:fixtureUserProfile)-and(Get-NormalizedPath $environmentObservation.HOME)-eq(Get-NormalizedPath $script:fixtureUserProfile)) 'verifier child processes use one fixture USERPROFILE and HOME' 'verifier child process inherited the caller USERPROFILE or HOME'
    $protocolPath=Join-Path $RepoRoot 'scripts\lib\Harness.Protocol.psm1';$runtimePath=Join-Path $RepoRoot 'scripts\lib\Harness.RuntimeDefault.psm1';$hostPath=Join-Path $RepoRoot 'scripts\lib\Harness.HostCapabilities.psm1';$qualificationPath=Join-Path $RepoRoot 'scripts\lib\Harness.Qualification.psm1';$promotionPath=Join-Path $RepoRoot 'scripts\promote-v2-rollout-report.ps1'
    foreach($file in @($protocolPath,$runtimePath,$hostPath,$qualificationPath,(Join-Path $RepoRoot 'scripts\harness-status.ps1'),(Join-Path $RepoRoot 'scripts\qualification-status.ps1'),(Join-Path $RepoRoot 'scripts\task.ps1'),$PSCommandPath)){$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($file,[ref]$tokens,[ref]$errors)|Out-Null;Check (@($errors).Count-eq0) "$(Split-Path -Leaf $file) parses" "$(Split-Path -Leaf $file) parse failed";Check (Test-FileHasUtf8Bom $file) "$(Split-Path -Leaf $file) has UTF-8 BOM" "$(Split-Path -Leaf $file) lacks UTF-8 BOM"}
    $protocolText=[IO.File]::ReadAllText($protocolPath,[Text.UTF8Encoding]::new($true,$true));$runtimeText=[IO.File]::ReadAllText($runtimePath,[Text.UTF8Encoding]::new($true,$true));$hostText=[IO.File]::ReadAllText($hostPath,[Text.UTF8Encoding]::new($true,$true));$promotionText=[IO.File]::ReadAllText($promotionPath,[Text.UTF8Encoding]::new($true,$true));$forbidden=@('0.144.4','DP-G','rollout-eligibility','ObservedHostContext','ReviewReceipt','CanaryAuthorization','Model40','HostBenchmark');Check (@($forbidden|Where-Object{$protocolText.Contains($_,[StringComparison]::OrdinalIgnoreCase)}).Count-eq0) 'Protocol contains no exact Host or Qualification concepts' 'Protocol still contains a Qualification concept'
    $ordinaryTargets=@('scripts/task.ps1','scripts/lib/Harness.Policy.psm1','scripts/harness-status.ps1','harness.ps1');$ordinaryText=@($ordinaryTargets|ForEach-Object{[IO.File]::ReadAllText((Join-Path $RepoRoot $_),[Text.UTF8Encoding]::new($true,$true))})-join"`n";Check ($ordinaryText-cnotmatch'Harness\.(?:RolloutEvidence|Qualification)|host_version_expected|rollout-eligibility|DP-G') 'ordinary task, policy, status, and bootstrap exclude Qualification' 'an ordinary entry imports or exposes Qualification'
    Check ($protocolText-match'Harness\.RuntimeDefault'-and([IO.File]::ReadAllText($runtimePath)-match'Harness\.HostCapabilities')-and([IO.File]::ReadAllText($qualificationPath)-notmatch'Harness\.Protocol')) 'dependency direction is Protocol to Runtime Default to Host facts, separate from Qualification' 'runtime and Qualification dependency direction is cyclic'
    Check ($runtimeText-notmatch'Harness\.(?:Qualification|RolloutEvidence)|DP-G|CanaryAuthorization|ReviewReceipt') 'Runtime Source Identity remains independent of Qualification and release evidence' 'Runtime Source Identity imported or named a Qualification concern'
    $runtimePathRequirements=@('Harness.Protocol.psm1','Harness.RuntimeDefault.psm1','Harness.HostCapabilities.psm1','Harness.Path.psm1','Harness.AtomicWrite.psm1','Harness.Policy.psm1','scripts/task.ps1','runtime-default-decision.schema.json','protocol-config.schema.json','policies/entry-contract.md','agent-configs/claude/CLAUDE.md.template','agent-configs/workspace/AGENTS.md.template','vault-template/entry/AGENTS.md.template');Check ($runtimeText-match'Get-HarnessRuntimeSourceIdentity'-and$runtimeText-match'RuntimeSourcePaths'-and$runtimeText-match'runtime_contract_digest'-and@($runtimePathRequirements|Where-Object{-not$runtimeText.Contains($_,[StringComparison]::Ordinal)}).Count-eq0) 'Runtime Default has one bounded deterministic Source Identity implementation over every direct Runtime path' 'Runtime Default lacks the bounded Source Identity implementation or a required direct path'
    Check ($hostText-match'if \(\$ProbeHostDetails\).*Get-HarnessCodexVersionObservation'-and$runtimeText-match'Get-HarnessHostCapabilities -RepoRoot \$RepoRoot -RequiredCapabilities') 'Host details are opt-in and Runtime requests only Decision capabilities' 'Runtime still performs an unconditional Host observation'
    Check ($promotionText-match'New-HarnessRuntimeDefaultDecisionDocument'-and$promotionText-notmatch'Get-HarnessRuntimeSourceIdentity') 'Promotion delegates Source Identity to the shared Runtime Decision constructor' 'Promotion duplicates or bypasses Runtime Source Identity'

    $script:protocolModule=Import-Module $protocolPath -Force -PassThru;$script:runtimeModule=Import-Module $runtimePath -Force -PassThru;$script:hostModule=Import-Module $hostPath -Force -PassThru;$script:qualificationModule=Import-Module $qualificationPath -Force -PassThru
    $profile=& $script:qualificationModule {Get-HarnessRolloutV2ExpectedHost};Check ($profile.observed_version-ceq'0.144.4') 'Qualification independently retains the exact 0.144.4 profile' 'Qualification exact Host profile was weakened'
    $newHost=New-Host '0.146.0-alpha.3.1' $false;$unknownHost=New-Host 'unknown';$newHostValid=& $script:hostModule {param($Doc)Assert-HarnessHostCapabilitiesDocument -Document $Doc} $newHost;$unknownHostValid=& $script:hostModule {param($Doc)Assert-HarnessHostCapabilitiesDocument -Document $Doc} $unknownHost;Check ($newHostValid-and$unknownHostValid-and$newHost.capabilities.request_send_telemetry-eq$false) 'Host adapter accepts observed newer and unknown facts without qualification conclusions' 'Host facts were rejected or coerced by version'

    $explicitWorkspace=Join-Path $temp 'explicit';[void][IO.Directory]::CreateDirectory($explicitWorkspace);$explicit=Resolve-Protocol $explicitWorkspace '' v2
    $configWorkspace=Join-Path $temp 'config';[void][IO.Directory]::CreateDirectory($configWorkspace);$configured=& $script:protocolModule {param($Root,$Work)$null=Set-HarnessWorkspaceProtocolConfig -RepoRoot $Root -WorkspaceRoot $Work -NewTaskProtocol v2;Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work} $RepoRoot $configWorkspace
    $artifactWorkspace=Join-Path $temp 'artifact';[void][IO.Directory]::CreateDirectory($artifactWorkspace);Write-Json (Join-Path $artifactWorkspace '.assistant\runtime\tasks\existing-v2\task.json') (New-V2Task 'existing-v2');$artifact=Resolve-Protocol $artifactWorkspace 'existing-v2'
    $risk=[ordered]@{user_visible_behavior=0;data_integrity=0;authorization_and_security=0;external_side_effects=0;blast_radius=0;rollback=0;verification_coverage=0};$priorProtocol=$env:HARNESS_PROTOCOL;try{$env:HARNESS_PROTOCOL='v2';Import-Module (Join-Path $RepoRoot 'scripts\lib\Harness.Policy.psm1') -Force;$direct=Resolve-HarnessExecutionProfile -RepoRoot $RepoRoot -WorkspaceRoot $explicitWorkspace -RiskScores $risk -Intent write -Identity new}finally{if($null-eq$priorProtocol){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$priorProtocol}}
    Check ($explicit.selected_protocol-ceq'v2'-and$configured.selected_protocol-ceq'v2'-and$artifact.selected_protocol-ceq'v2'-and$direct.profile-ceq'direct'-and$direct.handoff-ceq'main-agent') 'newer or unknown Host facts cannot block explicit, workspace, existing-v2, or Direct' 'a version-independent v2 path was blocked'

    $missingWorkspace=Join-Path $temp 'decision-missing';[void][IO.Directory]::CreateDirectory($missingWorkspace);$missing=Resolve-Protocol $missingWorkspace
    $reportOnly=Join-Path $temp 'report-only';[void][IO.Directory]::CreateDirectory($reportOnly);foreach($name in @('v2-eligibility.json','v2-canary-candidate.json','v2-canary-authorization.json')){Write-Json (Join-Path $reportOnly ".assistant\runtime\rollout\$name") ([ordered]@{qualification='ignored'})};$reportOnlyResolution=Resolve-Protocol $reportOnly
    $releaseWorkspace=Join-Path $temp 'release-decision';[void][IO.Directory]::CreateDirectory($releaseWorkspace);$release=& $script:runtimeModule {param($Root,$Work)New-HarnessRuntimeDefaultDecisionDocument -RepoRoot $Root -WorkspaceRoot $Work -Scope release-default} $RepoRoot $releaseWorkspace;Write-Json (Join-Path $releaseWorkspace '.assistant\runtime\rollout\v2-eligibility.json') ([ordered]@{qualification='ignored'});Write-Decision $releaseWorkspace $release;$releaseWithReport=Resolve-Protocol $releaseWorkspace;[IO.File]::Move((Join-Path $releaseWorkspace '.assistant\runtime\rollout\v2-eligibility.json'),(Join-Path $releaseWorkspace 'moved-qualification.json'));$releaseWithoutReport=Resolve-Protocol $releaseWorkspace
    $releaseNewHost=& $script:runtimeModule {param($Root,$Work,$Host)Get-HarnessRuntimeDefaultDecision -RepoRoot $Root -WorkspaceRoot $Work -HostCapabilities $Host} $RepoRoot $releaseWorkspace $newHost;$releaseUnknownHost=& $script:runtimeModule {param($Root,$Work,$Host)Get-HarnessRuntimeDefaultDecision -RepoRoot $Root -WorkspaceRoot $Work -HostCapabilities $Host} $RepoRoot $releaseWorkspace $unknownHost
    Check ($missing.selected_protocol-ceq'v1'-and$missing.reason-ceq'runtime-default-missing'-and$reportOnlyResolution.selected_protocol-ceq'v1'-and$reportOnlyResolution.reason-ceq'runtime-default-missing') 'missing decision and Qualification-only artifacts select the v1 fallback' 'Qualification artifacts influenced ordinary routing'
    Check ($releaseWithReport.selected_protocol-ceq'v2'-and$releaseWithoutReport.selected_protocol-ceq'v2'-and$releaseNewHost.status-ceq'valid'-and$releaseUnknownHost.status-ceq'valid') 'release Runtime Default works after Qualification report move/delete and across Host versions' 'Runtime Default depended on a Qualification report or exact Host version'

    $fastBin=Join-Path $temp 'fast-path-bin';[void][IO.Directory]::CreateDirectory($fastBin);$fastSentinel=Join-Path $fastBin 'codex-called.txt';$fastCodex=Join-Path $fastBin 'codex.cmd';[IO.File]::WriteAllText($fastCodex,"@echo called>`"$fastSentinel`"`r`n@ping 127.0.0.1 -n 8 >nul`r`n@echo codex-cli 0.144.4`r`n",[Text.ASCIIEncoding]::new());$priorPath=$env:PATH
    try {
        $env:PATH="$fastBin;$priorPath"
        $fastResults=[ordered]@{};$fastTimer=[Diagnostics.Stopwatch]::StartNew()
        foreach($case in @('missing','explicit','workspace','artifact','release')){
            if(Test-Path -LiteralPath $fastSentinel){[IO.File]::Delete($fastSentinel)}
            $value=switch($case){'missing'{Resolve-Protocol $missingWorkspace}'explicit'{Resolve-Protocol $explicitWorkspace '' v2}'workspace'{& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work} $RepoRoot $configWorkspace}'artifact'{Resolve-Protocol $artifactWorkspace 'existing-v2'}'release'{Resolve-Protocol $releaseWorkspace}}
            $fastResults[$case]=[ordered]@{resolution=$value;codex_called=(Test-Path -LiteralPath $fastSentinel)}
        }
        $fastTimer.Stop()
    } finally { $env:PATH=$priorPath }
    Check (-not$fastResults.missing.codex_called-and$fastResults.missing.resolution.reason-ceq'runtime-default-missing') 'missing Runtime Decision starts no Codex probe' 'missing Runtime Decision started Codex'
    Check (-not$fastResults.explicit.codex_called-and$fastResults.explicit.resolution.selected_protocol-ceq'v2') 'explicit v2 starts no Codex probe' 'explicit v2 started Codex'
    Check (-not$fastResults.workspace.codex_called-and$fastResults.workspace.resolution.selected_protocol-ceq'v2') 'workspace enable-v2 starts no Codex probe' 'workspace enable-v2 started Codex'
    Check (-not$fastResults.artifact.codex_called-and$fastResults.artifact.resolution.selected_protocol-ceq'v2') 'existing v2 Artifact starts no Codex probe' 'existing v2 Artifact started Codex'
    Check (-not$fastResults.release.codex_called-and$fastResults.release.resolution.selected_protocol-ceq'v2') 'static-capability release Runtime Decision starts no Codex probe' 'static-capability Runtime Decision started Codex'
    Check ($fastTimer.Elapsed.TotalSeconds-lt5) 'a sleeping fake Codex cannot delay ordinary protocol resolution' "ordinary protocol resolution took $($fastTimer.Elapsed.TotalSeconds) seconds"

    $canaryWorkspace=Join-Path $temp 'canary';[void][IO.Directory]::CreateDirectory($canaryWorkspace);$canary=& $script:runtimeModule {param($Root,$Work)New-HarnessRuntimeDefaultDecisionDocument -RepoRoot $Root -WorkspaceRoot $Work -Scope workspace-canary -ExpiresAtUtc ([datetimeoffset]::UtcNow.AddHours(1))} $RepoRoot $canaryWorkspace;Write-Decision $canaryWorkspace $canary;$canaryValid=Resolve-Protocol $canaryWorkspace
    $copiedWorkspace=Join-Path $temp 'canary-copy';[void][IO.Directory]::CreateDirectory($copiedWorkspace);Write-Decision $copiedWorkspace $canary;$canaryCopied=Resolve-Protocol $copiedWorkspace
    $expiredWorkspace=Join-Path $temp 'canary-expired';[void][IO.Directory]::CreateDirectory($expiredWorkspace);$issued=[datetimeoffset]::UtcNow.AddHours(-2);$expired=& $script:runtimeModule {param($Root,$Work,$Start)New-HarnessRuntimeDefaultDecisionDocument -RepoRoot $Root -WorkspaceRoot $Work -Scope workspace-canary -IssuedAtUtc $Start -ExpiresAtUtc $Start.AddHours(1)} $RepoRoot $expiredWorkspace $issued;Write-Decision $expiredWorkspace $expired;$canaryExpired=Resolve-Protocol $expiredWorkspace
    Check ($canaryValid.selected_protocol-ceq'v2'-and$canaryCopied.selected_protocol-ceq'v1'-and$canaryCopied.reason-ceq'runtime-default-workspace-mismatch'-and$canaryExpired.selected_protocol-ceq'v1'-and$canaryExpired.reason-ceq'runtime-default-expired') 'workspace canary is bounded to its workspace and expiry' 'workspace canary escaped its binding or lifetime'

    $sourceRepo=Join-Path $temp 'runtime-source-repo';$cloneOutput=@(& git clone --quiet --no-hardlinks $RepoRoot $sourceRepo 2>&1);if($LASTEXITCODE-ne0){throw "runtime source fixture clone failed: $($cloneOutput-join' ')"}
    $sourceWorkspace=Join-Path $temp 'runtime-source-workspace';[void][IO.Directory]::CreateDirectory($sourceWorkspace)
    $sourceDecision=& $script:runtimeModule {param($Root,$Work)New-HarnessRuntimeDefaultDecisionDocument -RepoRoot $Root -WorkspaceRoot $Work -Scope release-default} $sourceRepo $sourceWorkspace;Write-Decision $sourceWorkspace $sourceDecision
    $observedIdentity=& $script:runtimeModule {param($Root)Get-HarnessRuntimeSourceIdentity -RepoRoot $Root} $sourceRepo
    Check (($sourceDecision.source_identity|ConvertTo-Json -Compress)-ceq($observedIdentity|ConvertTo-Json -Compress)-and$sourceDecision.source_revision-ceq$observedIdentity.revision) 'Runtime Decision binds the shared deterministic Source Identity' 'Runtime Decision Source Identity differs from the shared observation'

    $fixtureRuntime=Join-Path $sourceRepo 'scripts\lib\Harness.RuntimeDefault.psm1';$fixtureRuntimeBytes=[IO.File]::ReadAllBytes($fixtureRuntime)
    try{[IO.File]::AppendAllText($fixtureRuntime,"`n# dirty-runtime-fixture`n",[Text.UTF8Encoding]::new($false));$dirtyRuntime=& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -RequestedProtocol auto} $sourceRepo $sourceWorkspace}finally{[IO.File]::WriteAllBytes($fixtureRuntime,$fixtureRuntimeBytes)}
    Check ($dirtyRuntime.selected_protocol-ceq'v1'-and$dirtyRuntime.reason-ceq'runtime-default-source-dirty') 'dirty Runtime Core invalidates the old Decision and falls back to v1' 'dirty Runtime Core still accepted the old Decision'

    $fixtureQualification=Join-Path $sourceRepo 'docs\release\default-promotion-gates.md';$fixtureQualificationBytes=[IO.File]::ReadAllBytes($fixtureQualification)
    try{[IO.File]::AppendAllText($fixtureQualification,"`nqualification-only fixture`n",[Text.UTF8Encoding]::new($false));$qualificationDirty=& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -RequestedProtocol auto} $sourceRepo $sourceWorkspace}finally{[IO.File]::WriteAllBytes($fixtureQualification,$fixtureQualificationBytes)}
    Check ($qualificationDirty.selected_protocol-ceq'v2'-and$qualificationDirty.runtime_default_decision.status-ceq'valid') 'Qualification-only source changes do not invalidate ordinary Runtime' 'Qualification-only source was incorrectly added to Runtime Source Identity'

    $fixtureHost=Join-Path $sourceRepo 'scripts\lib\Harness.HostCapabilities.psm1';$fixtureHostBytes=[IO.File]::ReadAllBytes($fixtureHost)
    try{[IO.File]::AppendAllText($fixtureHost,"`n# staged-runtime-fixture`n",[Text.UTF8Encoding]::new($false));$null=@(& git -C $sourceRepo add -- 'scripts/lib/Harness.HostCapabilities.psm1' 2>&1);if($LASTEXITCODE-ne0){throw 'runtime source staged fixture setup failed'};$stagedRuntime=& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -RequestedProtocol auto} $sourceRepo $sourceWorkspace}finally{[IO.File]::WriteAllBytes($fixtureHost,$fixtureHostBytes);$null=& git -C $sourceRepo add -- 'scripts/lib/Harness.HostCapabilities.psm1'}
    Check ($stagedRuntime.selected_protocol-ceq'v1'-and$stagedRuntime.reason-ceq'runtime-default-source-dirty') 'staged Runtime Core invalidates the old Decision' 'staged Runtime Core still accepted the old Decision'

    try{$null=@(& git -C $sourceRepo update-index --assume-unchanged -- 'scripts/lib/Harness.Protocol.psm1' 2>&1);if($LASTEXITCODE-ne0){throw 'unsafe-index fixture setup failed'};$unsafeIndex=& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -RequestedProtocol auto} $sourceRepo $sourceWorkspace}finally{$null=& git -C $sourceRepo update-index --no-assume-unchanged -- 'scripts/lib/Harness.Protocol.psm1'}
    Check ($unsafeIndex.selected_protocol-ceq'v1'-and$unsafeIndex.reason-ceq'runtime-default-source-unsafe-index') 'unsafe Runtime index flags invalidate the old Decision' 'unsafe Runtime index flag was accepted'

    try{$null=@(& git -C $sourceRepo rm --cached --quiet -- 'scripts/lib/Harness.AtomicWrite.psm1' 2>&1);if($LASTEXITCODE-ne0){throw 'untracked-shadow fixture setup failed'};$untrackedShadow=& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -RequestedProtocol auto} $sourceRepo $sourceWorkspace}finally{$null=& git -C $sourceRepo add -- 'scripts/lib/Harness.AtomicWrite.psm1'}
    Check ($untrackedShadow.selected_protocol-ceq'v1'-and$untrackedShadow.reason-ceq'runtime-default-source-untracked-shadow') 'untracked Runtime shadow invalidates the old Decision' 'untracked Runtime shadow was accepted'

    $identityReasons=[ordered]@{}
    foreach($case in @('tree','path-set','contract','digest-coverage','missing','extra')){
        $work=Join-Path $temp "source-identity-$case";[void][IO.Directory]::CreateDirectory($work);$doc=Copy-Document $sourceDecision
        switch($case){
            'tree'{$doc.source_identity.tree_oid='1'*40}
            'path-set'{$doc.source_identity.path_set_digest='sha256:'+('2'*64)}
            'contract'{$doc.source_identity.runtime_contract_digest='sha256:'+('3'*64)}
            'digest-coverage'{$doc.source_identity.runtime_contract_digest='sha256:'+('4'*64)}
            'missing'{[void]$doc.Remove('source_identity')}
            'extra'{$doc.source_identity['unexpected']='rejected'}
        }
        if($case-cin@('tree','path-set','contract')){$doc.decision_digest=& $script:runtimeModule {param($Value)Get-HarnessRuntimeDefaultDecisionDigest -Document $Value} $doc}
        Write-Decision $work $doc
        $identityReasons[$case]=(& $script:protocolModule {param($Root,$Work)Get-HarnessProtocolResolution -RepoRoot $Root -WorkspaceRoot $Work -RequestedProtocol auto} $sourceRepo $work).reason
    }
    Check ($identityReasons.tree-ceq'runtime-default-source-tree-mismatch') 'tampered Source tree OID is rejected precisely' 'tampered Source tree OID was accepted or misreported'
    Check ($identityReasons.'path-set'-ceq'runtime-default-source-path-set-mismatch') 'tampered Runtime path-set digest is rejected precisely' 'tampered Runtime path-set digest was accepted or misreported'
    Check ($identityReasons.contract-ceq'runtime-default-source-contract-mismatch') 'tampered Runtime contract digest is rejected precisely' 'tampered Runtime contract digest was accepted or misreported'
    Check ($identityReasons.'digest-coverage'-ceq'runtime-default-digest-mismatch') 'Decision digest covers Source Identity' 'Decision digest did not cover Source Identity'
    Check ($identityReasons.missing-ceq'runtime-default-invalid-document'-and$identityReasons.extra-ceq'runtime-default-invalid-document') 'strict Runtime Default schema requires an exact Source Identity' 'strict Runtime Default schema accepted a missing or extended Source Identity'
    Check (@(& git -C $sourceRepo status --porcelain --untracked-files=all).Count-eq0) 'Runtime Source Identity fixtures restore a clean repository' 'Runtime Source Identity fixture repository remained dirty'

    $invalidResults=[ordered]@{}
    foreach($case in @('digest','source','unknown','bom','capability')){$work=Join-Path $temp "invalid-$case";[void][IO.Directory]::CreateDirectory($work);$doc=Copy-Document $release;if($case-ceq'digest'){$doc.new_task_protocol='v1'}elseif($case-ceq'source'){$doc.source_revision='1'*40;$doc.decision_digest=& $script:runtimeModule {param($Value)Get-HarnessRuntimeDefaultDecisionDigest -Document $Value} $doc}elseif($case-ceq'unknown'){$doc.host_version='0.144.4'}elseif($case-ceq'capability'){$doc=& $script:runtimeModule {param($Root,$Work)New-HarnessRuntimeDefaultDecisionDocument -RepoRoot $Root -WorkspaceRoot $Work -Scope release-default -RequiredCapabilities @('request_send_telemetry')} $RepoRoot $work};if($case-ceq'bom'){$json=$doc|ConvertTo-Json -Depth 20 -Compress;$bytes=[byte[]](0xEF,0xBB,0xBF)+[Text.UTF8Encoding]::new($false).GetBytes($json);$path=Join-Path $work '.assistant\runtime\protocol-default.json';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllBytes($path,$bytes)}else{Write-Decision $work $doc};$invalidResults[$case]=Resolve-Protocol $work}
    Check ($invalidResults.digest.reason-ceq'runtime-default-digest-mismatch'-and$invalidResults.source.reason-ceq'runtime-default-source-revision-mismatch'-and$invalidResults.unknown.reason-ceq'runtime-default-invalid-document'-and$invalidResults.bom.reason-ceq'runtime-default-bom-rejected'-and$invalidResults.capability.reason-match'^runtime-default-capability-missing-request_send_telemetry$'-and@($invalidResults.Values|Where-Object{$_.selected_protocol-cne'v1'}).Count-eq0) 'invalid, drifting, unknown-field, BOM, and missing-capability decisions fail to v1 with precise reasons' 'an invalid Runtime Default was accepted or misreported'

    $bin=Join-Path $temp 'bin';[void][IO.Directory]::CreateDirectory($bin);$fakeCodex=Join-Path $bin 'codex.cmd';$statusSentinel=Join-Path $bin 'status-codex-called.txt';$statusWorkspace=Join-Path $temp 'status';[void][IO.Directory]::CreateDirectory($statusWorkspace);Write-Decision $statusWorkspace $release
    $requiredStatusWorkspace=Join-Path $temp 'status-required-missing';[void][IO.Directory]::CreateDirectory($requiredStatusWorkspace);$requiredStatusDecision=& $script:runtimeModule {param($Root,$Work)New-HarnessRuntimeDefaultDecisionDocument -RepoRoot $Root -WorkspaceRoot $Work -Scope release-default -RequiredCapabilities @('request_send_telemetry')} $RepoRoot $requiredStatusWorkspace;Write-Decision $requiredStatusWorkspace $requiredStatusDecision
    $bootstrapWorkspace=Join-Path $temp 'bootstrap-no-host-probe';$priorPath=$env:PATH
    try{
        $env:PATH="$bin;$priorPath"
        [IO.File]::WriteAllText($fakeCodex,"@echo called>`"$statusSentinel`"`r`n@echo codex-cli 0.146.0-alpha.3.1`r`n",[Text.ASCIIEncoding]::new())
        $defaultStatus=Invoke-Script (Join-Path $RepoRoot 'scripts\harness-status.ps1') @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$statusWorkspace)
        $defaultStatusCalled=Test-Path -LiteralPath $statusSentinel
        $probeStatus=Invoke-Script (Join-Path $RepoRoot 'scripts\harness-status.ps1') @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$statusWorkspace,'-ProbeHostDetails')
        $probeStatusCalled=Test-Path -LiteralPath $statusSentinel
        if(Test-Path -LiteralPath $statusSentinel){[IO.File]::Delete($statusSentinel)}
        [IO.File]::WriteAllText($fakeCodex,"@echo malformed`r`n",[Text.ASCIIEncoding]::new())
        $unknownStatus=Invoke-Script (Join-Path $RepoRoot 'scripts\harness-status.ps1') @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$statusWorkspace,'-ProbeHostDetails')
        $requiredStatus=Invoke-Script (Join-Path $RepoRoot 'scripts\harness-status.ps1') @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$requiredStatusWorkspace)
        $requiredStatusCalled=Test-Path -LiteralPath $statusSentinel
        $bootstrapStatus=Invoke-Script (Join-Path $RepoRoot 'harness.ps1') @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$bootstrapWorkspace)
        $bootstrapCalled=Test-Path -LiteralPath $statusSentinel
        $qualificationStatus=Invoke-Script (Join-Path $RepoRoot 'scripts\qualification-status.ps1') @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$statusWorkspace)
    }finally{$env:PATH=$priorPath}
    Check ($defaultStatus.ExitCode-eq0-and$defaultStatus.StdOut-match'(?m)^STATUS: PASS\r?$'-and$defaultStatus.StdOut-match'host_version_actual: unknown'-and$defaultStatus.StdOut-match'host_details_probed: false'-and$defaultStatus.StdOut-match'capability_observation: observed'-and$defaultStatus.StdOut-match'capability_hook_status_query: unavailable'-and$defaultStatus.StdOut-match'(?ms)^Warnings:\r?\n- none(?:\r?\n|$)'-and-not$defaultStatusCalled) 'normal Runtime status is PASS without probing Host or warning on unavailable optional capabilities' 'normal Runtime status probed Host or retained the permanent optional-capability warning'
    Check ($probeStatus.ExitCode-eq0-and$probeStatus.StdOut-match'host_version_actual: 0\.146\.0-alpha\.3\.1'-and$probeStatus.StdOut-match'host_details_probed: true'-and$probeStatusCalled-and$probeStatus.StdOut-notmatch'host_version_expected|version.mismatch|qualification_profile') 'ProbeHostDetails alone observes a newer Host without compatibility inference' 'ProbeHostDetails did not remain explicit and version-independent'
    Check ($unknownStatus.ExitCode-eq0-and$unknownStatus.StdOut-match'host_version_actual: unknown'-and$unknownStatus.StdOut-match'host_details_probed: true'-and$unknownStatus.StdOut-notmatch'host_version_expected|version.mismatch|observation is unavailable|qualification_profile') 'unknown Host detail remains an optional fact without warning or mismatch' 'unknown Host detail was treated as a Runtime warning or release mismatch'
    Check ($requiredStatus.ExitCode-eq1-and$requiredStatus.StdOut-match'(?m)^STATUS: WARN\r?$'-and$requiredStatus.StdOut-match'runtime-default-capability-missing-request_send_telemetry'-and-not$requiredStatusCalled) 'status warns only when the current Decision requires an unavailable capability' 'required capability status did not fail closed without Host probing'
    Check (-not$bootstrapCalled-and$bootstrapStatus.StdOut-match'(?m)^- harness-status\.ps1: WARN\r?$') 'default harness bootstrap executes fast Runtime-only status without Host version probing' 'default harness bootstrap executed the Host version probe'
    Check ($qualificationStatus.StdOut-match'host_version_expected: 0\.144\.4'-and$qualificationStatus.StdOut-match'qualification_profile') 'only explicit qualification-status exposes the exact release profile' 'qualification maintenance status lost its explicit profile'

    $taskWorkspace=Join-Path $temp 'task-cas';[void][IO.Directory]::CreateDirectory($taskWorkspace);[IO.File]::WriteAllText((Join-Path $taskWorkspace '.gitignore'),".assistant/`ncontracts/`napproval-inputs/`nevidence-inputs/`n.harness/`ndocs/tasks/`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $taskWorkspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false));$null=& git -C $taskWorkspace init -q;$null=& git -C $taskWorkspace config user.email harness@example.invalid;$null=& git -C $taskWorkspace config user.name Harness;$null=& git -C $taskWorkspace add .;$null=& git -C $taskWorkspace commit -qm baseline;Import-Module (Join-Path $RepoRoot 'scripts\lib\Harness.Evidence.psm1') -Force
    $contracts=@{};foreach($id in @('auto-transition','auto-resume','auto-approve','auto-verify','auto-race')){$contracts[$id]=Write-Contract $taskWorkspace $id}
    foreach($id in $contracts.Keys){$args=@('create','-TaskId',$id,'-Contract',$contracts[$id].Path,'-AsJson');if($id-ceq'auto-approve'){$args+=@('-Capabilities','approval_required')};$created=Invoke-Task $taskWorkspace $args;if($created.ExitCode-ne0){throw "task fixture create failed: $id $($created.StdErr)"}}
    $autoTransition=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-transition','-To','running','-AsJson');$autoResume=Invoke-Task $taskWorkspace @('resume-and-execute','-TaskId','auto-resume','-AsJson')
    $null=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-approve','-To','running','-AsJson');$null=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-approve','-To','verifying','-AsJson');$approvalPath=Write-Approval $taskWorkspace 'auto-approve' 4 $contracts['auto-approve'].Digest;$autoApprove=Invoke-Task $taskWorkspace @('approve','-TaskId','auto-approve','-Approval',$approvalPath,'-AsJson')
    $null=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-verify','-To','running','-AsJson');$null=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-verify','-To','verifying','-AsJson');$evidencePath=Write-Evidence $taskWorkspace 'auto-verify' 3 $contracts['auto-verify'].Digest;$autoVerify=Invoke-Task $taskWorkspace @('verify','-TaskId','auto-verify','-Evidence',$evidencePath,'-AsJson')
    Check ($autoTransition.ExitCode-eq0-and(Read-Output $autoTransition).task.version-eq2-and$autoResume.ExitCode-eq0-and(Read-Output $autoResume).task.version-eq2-and$autoApprove.ExitCode-eq0-and(Read-Output $autoApprove).task.version-eq4-and$autoVerify.ExitCode-eq0-and(Read-Output $autoVerify).task.status-ceq'done') 'transition, resume-and-execute, approve, and verify auto-read one CAS version' 'a normal task command still required a numeric ExpectedVersion'

    $readyName="Local\dev-harness.dp02r.ready.$([guid]::NewGuid().ToString('N'))";$releaseName="Local\dev-harness.dp02r.release.$([guid]::NewGuid().ToString('N'))";$readyCreated=$false;$releaseCreated=$false;$readyEvent=[Threading.EventWaitHandle]::new($false,[Threading.EventResetMode]::ManualReset,$readyName,[ref]$readyCreated);$releaseEvent=[Threading.EventWaitHandle]::new($false,[Threading.EventResetMode]::ManualReset,$releaseName,[ref]$releaseCreated);$raceHandle=$null
    try{$oldReady=[Environment]::GetEnvironmentVariable('DEV_HARNESS_TEST_TASK_CLI_VERSION_READY_EVENT',[EnvironmentVariableTarget]::Process);$oldRelease=[Environment]::GetEnvironmentVariable('DEV_HARNESS_TEST_TASK_CLI_VERSION_RELEASE_EVENT',[EnvironmentVariableTarget]::Process);$oldProtocol=$env:HARNESS_PROTOCOL;try{$env:DEV_HARNESS_TEST_TASK_CLI_VERSION_READY_EVENT=$readyName;$env:DEV_HARNESS_TEST_TASK_CLI_VERSION_RELEASE_EVENT=$releaseName;$env:HARNESS_PROTOCOL='v2';$raceHandle=Start-FixtureRepoProcess -ScriptPath (Join-Path $RepoRoot 'scripts\task.ps1') -Arguments @('transition','-TaskId','auto-race','-To','running','-AsJson','-RepoRoot',$RepoRoot,'-WorkspaceRoot',$taskWorkspace)}finally{if($null-eq$oldReady){Remove-Item Env:DEV_HARNESS_TEST_TASK_CLI_VERSION_READY_EVENT -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_CLI_VERSION_READY_EVENT=$oldReady};if($null-eq$oldRelease){Remove-Item Env:DEV_HARNESS_TEST_TASK_CLI_VERSION_RELEASE_EVENT -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_CLI_VERSION_RELEASE_EVENT=$oldRelease};if($null-eq$oldProtocol){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$oldProtocol}};if(-not$readyEvent.WaitOne(10000)){throw 'auto-version race did not reach barrier'};$winner=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-race','-ExpectedVersion','1','-To','running','-AsJson');$afterWinner=Snapshot $taskWorkspace;[void]$releaseEvent.Set();$loser=Complete $raceHandle;$raceHandle=$null;$afterLoser=Snapshot $taskWorkspace;$conflict=$loser.StdErr|ConvertFrom-Json -AsHashtable -Depth 10;Check ($winner.ExitCode-eq0-and$loser.ExitCode-eq2-and$conflict.error-ceq'task-version-conflict'-and$conflict.current_version-eq2-and$conflict.writes-eq0-and$loser.StdErr-notmatch'provide|enter|ExpectedVersion') 'auto CAS conflict is machine-readable and never asks for a number' 'auto CAS conflict was overwritten, retried, or exposed ExpectedVersion';Same $afterWinner $afterLoser 'auto CAS conflict is zero-write' 'auto CAS conflict changed task state'}finally{if($null-ne$raceHandle){[void]$releaseEvent.Set();try{$null=Complete $raceHandle}catch{}};$releaseEvent.Dispose();$readyEvent.Dispose()}
    $beforeWrong=Snapshot $taskWorkspace;$wrong=Invoke-Task $taskWorkspace @('transition','-TaskId','auto-transition','-ExpectedVersion','99','-To','verifying','-AsJson');Check ($wrong.ExitCode-eq2-and$wrong.StdErr-match'ExpectedVersion mismatch') 'internal explicit CAS still rejects a wrong ExpectedVersion' 'internal CAS accepted a wrong version';Same $beforeWrong (Snapshot $taskWorkspace) 'wrong internal CAS is zero-write' 'wrong internal CAS wrote state'
} finally {
    Remove-Module Harness.Protocol,Harness.RuntimeDefault,Harness.HostCapabilities,Harness.Qualification,Harness.Policy,Harness.Evidence -ErrorAction Ignore
    if(Test-Path -LiteralPath $temp){Remove-DirectoryWithRetry -Path $temp}
}
$callerStateAfter=Get-FileState $callerStatePaths;Same $callerStateBefore $callerStateAfter 'verifier leaves caller USERPROFILE Harness state unchanged' 'verifier changed caller USERPROFILE Harness state'
$repoAfter=@(& git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count-eq0) 'decoupling verifier leaves repository state unchanged' 'decoupling verifier changed repository state'
foreach($item in $script:checks){"[PASS] $item"};foreach($item in $script:failures){"[FAIL] $item"};if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:checks.Count) checks)";exit 0
