[CmdletBinding()]
param([string]$RepoRoot='')

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(!$RepoRoot){$RepoRoot=Split-Path -Parent $PSScriptRoot};$RepoRoot=(Resolve-Path $RepoRoot).Path
. (Join-Path $RepoRoot 'tests/fixture-test-common.ps1')
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Governance.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Evidence.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.AtomicWrite.psm1') -Force
$taskScript=Join-Path $RepoRoot 'scripts/task.ps1';$script:passes=[Collections.Generic.List[string]]::new();$script:failures=[Collections.Generic.List[string]]::new()
function Check($Condition,$Pass,$Fail){if($Condition){$script:passes.Add($Pass)}else{$script:failures.Add($Fail)}}
function Snapshot($Root){return @(Get-ChildItem $Root -Force -Recurse|%{if($_.PSIsContainer){'D|'+$_.FullName}else{'F|'+$_.FullName+'|'+(Get-FileHash $_.FullName).Hash}}|Sort-Object)}
function Same($Before,$After,$Pass,$Fail){Check (@(Compare-Object @($Before) @($After)).Count -eq 0) $Pass $Fail}
function Complete-Cli($Handle){if(-not$Handle.Process.WaitForExit(30000)){$Handle.Process.Kill($true);throw 'CLI timeout'};$result=[pscustomobject]@{ExitCode=$Handle.Process.ExitCode;StdOut=$Handle.StdOut.GetAwaiter().GetResult().Trim();StdErr=$Handle.StdErr.GetAwaiter().GetResult().Trim()};$Handle.Process.Dispose();return $result}
function Invoke-Cli($Workspace,[string[]]$Arguments){$old=$env:HARNESS_PROTOCOL;try{$env:HARNESS_PROTOCOL='v2';return Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $taskScript -Arguments ($Arguments+@('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$Workspace)))}finally{if($null-eq$old){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$old}}}
function Read-Output($Result){if($Result.StdOut){return $Result.StdOut|ConvertFrom-Json -Depth 50 -DateKind String};return $null}
function Write-JsonFile($Workspace,$Relative,$Value){$path=Join-Path $Workspace $Relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllText($path,(($Value|ConvertTo-Json -Depth 40)+"`n"),[Text.UTF8Encoding]::new($false))}
function Write-Contract($Workspace,$TaskId){
    $body=[ordered]@{schema_version='requirement-contract/v1';task_id=$TaskId;goal="Govern $TaskId.";acceptance=@('Governance requirements pass.');in_scope=@('v2 governance');out_of_scope=@('v1 stages');product_constraints=@('No fabricated review.');product_decisions=@();unresolved_product_decisions=@();source_authority=@('current-user-message')}
    $contract=[ordered]@{};foreach($key in $body.Keys){$contract[$key]=$body[$key]};$contract.digest=Get-HarnessSha256Text -Content ($body|ConvertTo-Json -Depth 30 -Compress)
    $relative="contracts/$TaskId.json";Write-JsonFile $Workspace $relative $contract;return [pscustomobject]@{Path=$relative;Digest=$contract.digest}
}
function Start-Verifying($Workspace,$TaskId,$Contract,[string[]]$Capabilities=@()){
    $args=@('create','-TaskId',$TaskId,'-Contract',$Contract.Path,'-AsJson');if($Capabilities.Count){$args+=@('-Capabilities')+$Capabilities}
    $created=Invoke-Cli $Workspace $args;$running=Invoke-Cli $Workspace @('transition','-TaskId',$TaskId,'-ExpectedVersion','1','-To','running','-AsJson');$verifying=Invoke-Cli $Workspace @('transition','-TaskId',$TaskId,'-ExpectedVersion','2','-To','verifying','-AsJson')
    if($created.ExitCode-or$running.ExitCode-or$verifying.ExitCode){throw "failed to prepare governed task: $TaskId`n$($created.StdErr)`n$($running.StdErr)`n$($verifying.StdErr)"};return Read-Output $created
}
function New-PassEvidence($Workspace,$TaskId,$ContractDigest,[switch]$WithActor){
    $recordRelative=".harness/evidence/$TaskId.txt";$recordPath=Join-Path $Workspace $recordRelative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $recordPath));[IO.File]::WriteAllText($recordPath,"pass`n",[Text.UTF8Encoding]::new($false));$recordDigest='sha256:'+((Get-FileHash $recordPath).Hash.ToLowerInvariant())
    $record=[ordered]@{type='command';command='pwsh -File tests/governed.ps1';cwd='.';exit_code=0;executed_at=[DateTimeOffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest=$recordDigest;covers=@('AC-1')};if($WithActor){$record.actor=[ordered]@{host='codex';model='gpt-5';actor_id='actor-implementer';context_id='context-implementer'}}
    $document=[ordered]@{schema_version='evidence/v1';task_id=$TaskId;task_version=3;contract_digest=$ContractDigest;revision=('dirty:'+'0'*64);records=@($record);coverage=[ordered]@{satisfied=@('AC-1');not_verified=@();blocked=@()};gaps=@();conclusion='pass'}
    $relative="evidence-inputs/$TaskId.json";Write-JsonFile $Workspace $relative $document;$document.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $Workspace -ContractDigest $ContractDigest -Evidence $document -EvidenceInputPath $relative -EvidenceOutputPath "docs/tasks/$TaskId/evidence.json";Write-JsonFile $Workspace $relative $document
    return [pscustomobject]@{Path=$relative;Document=$document;RecordPath=$recordRelative;RecordDigest=$recordDigest}
}
function Complete-Plan($Workspace,$TaskId){$path=Join-Path $Workspace "docs/tasks/$TaskId/plan.md";$text=[IO.File]::ReadAllText($path,[Text.Encoding]::UTF8);$text=$text.Replace('<fill-goal>','Implement the confirmed Contract.').Replace('<fill-scope>','Only governed v2 artifacts.').Replace('<fill-implementation>','Apply the smallest policy-required change.').Replace('<fill-verification>','Run the declared Evidence commands.').Replace('<fill-rollback>','Revert the governed change.');[IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false))}
function Write-Audit($Workspace,$TaskId,$ContractDigest,$EvidenceDigest,$ReviewerContext='context-reviewer',$ReviewerActor='actor-implementer',$Level='isolated-context',$Participated='false',$Findings='- none'){
    $record=[ordered]@{implementer_actor_id='actor-implementer';reviewer_actor_id=$ReviewerActor;reviewer_context_id=$ReviewerContext;reviewer_base_model='gpt-5';independence_level=$Level;evidence_digest=$EvidenceDigest}
    $template=[IO.File]::ReadAllText((Join-Path $RepoRoot 'templates/v2/audit.md.template'),[Text.Encoding]::UTF8);$text=$template.Replace('{{TASK_ID}}',$TaskId).Replace('{{TASK_VERSION}}','3').Replace('{{CONTRACT_DIGEST}}',$ContractDigest).Replace('{{VERDICT}}','pass').Replace('{{REVIEWER_PARTICIPATED}}',$Participated).Replace('{{AUDIT_RECORD_JSON}}',($record|ConvertTo-Json -Depth 10)).Replace('{{FINDINGS}}',$Findings).Replace('{{EVIDENCE}}','Read-only diff and command evidence review.')
    $path=Join-Path $Workspace "docs/tasks/$TaskId/audit.md";[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllText($path,$text,[Text.UTF8Encoding]::new($false))
}

$repoBefore=@(& git -C $RepoRoot status --porcelain --untracked-files=all);$temp=Join-Path ([IO.Path]::GetTempPath()) ('v2-governance-'+[guid]::NewGuid().ToString('N'));$workspace=Join-Path $temp 'workspace';[void][IO.Directory]::CreateDirectory($workspace)
try{
    [IO.File]::WriteAllText((Join-Path $workspace '.gitignore'),".assistant/runtime/`n.harness/evidence/`nevidence-inputs/`ndocs/tasks/*/evidence.json`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false))
    git -C $workspace init -q;git -C $workspace config user.email harness@example.invalid;git -C $workspace config user.name Harness;git -C $workspace config core.autocrlf false;git -C $workspace add .;git -C $workspace commit -qm baseline
    foreach($file in @('scripts/lib/Harness.Governance.psm1','scripts/lib/Harness.Evidence.psm1','scripts/lib/Harness.TaskState.psm1','scripts/task.ps1','tests/verify-v2-governed-audit.ps1')){$path=Join-Path $RepoRoot $file;$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($path,[ref]$tokens,[ref]$errors)|Out-Null;Check (@($errors).Count-eq 0) "$file parses" "$file parse failed";Check (Test-FileHasUtf8Bom $path) "$file has UTF-8 BOM" "$file lacks UTF-8 BOM"}
    $exports=@(Get-Command -Module Harness.Governance|Select-Object -ExpandProperty Name|Sort-Object);Check (@(Compare-Object @('Assert-HarnessGovernanceReady','Assert-HarnessPlanArtifact','New-HarnessPlanArtifact','Resolve-HarnessAuditArtifact') $exports).Count-eq 0) 'Governance exports are exact' 'Governance exports drifted'
    Check ((Test-Path (Join-Path $RepoRoot 'skills/planning/SKILL.md'))-and(Test-Path (Join-Path $RepoRoot 'skills/audit/SKILL.md'))-and(Test-Path (Join-Path $RepoRoot 'templates/v2/plan.md.template'))-and(Test-Path (Join-Path $RepoRoot 'templates/v2/audit.md.template'))) 'governed skills and durable templates exist' 'governed skills or templates are missing'
    $launchText=(Get-Content (Join-Path $RepoRoot 'scripts/lib/Harness.TaskState.psm1') -Raw -Encoding utf8)+(Get-Content (Join-Path $RepoRoot 'scripts/lib/Harness.Governance.psm1') -Raw -Encoding utf8)
    Check ($launchText-notmatch'(?i)Start-Process|spawn[_-]|workflow-team|create_thread') 'task creation has no reviewer launch path' 'task creation can launch a reviewer'

    $contracts=@{};foreach($taskId in @('optional-task','plan-task','audit-task')){$contracts[$taskId]=Write-Contract $workspace $taskId}
    $created=Start-Verifying $workspace 'optional-task' $contracts['optional-task'];Check ($created.plan_action-ceq'not-required'-and-not(Test-Path (Join-Path $workspace 'docs/tasks/optional-task/plan.md'))-and-not(Test-Path (Join-Path $workspace 'docs/tasks/optional-task/audit.md'))) 'false governance policies create no plan or audit' 'optional task created governed artifacts'
    $optionalEvidence=New-PassEvidence $workspace 'optional-task' $contracts['optional-task'].Digest;$result=Invoke-Cli $workspace @('verify','-TaskId','optional-task','-ExpectedVersion','3','-Evidence',$optionalEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 0-and(Read-Output $result).task.status-ceq'done') 'optional audit policy permits Evidence-only completion' 'optional task required an audit'

    $created=Start-Verifying $workspace 'plan-task' $contracts['plan-task'] @('plan_required');$planPath=Join-Path $workspace 'docs/tasks/plan-task/plan.md';Check ($created.plan_action-ceq'created'-and(Test-Path $planPath)-and-not(Test-Path (Join-Path $workspace 'docs/tasks/plan-task/audit.md'))) 'plan_required creates only a bound plan template' 'plan capability creation drifted'
    $planEvidence=New-PassEvidence $workspace 'plan-task' $contracts['plan-task'].Digest;$before=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','plan-task','-ExpectedVersion','3','-Evidence',$planEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 2-and$result.StdErr-match'fill placeholders') 'incomplete required plan blocks done' 'incomplete required plan was accepted';Same $before (Snapshot $workspace) 'plan rejection is zero-write' 'plan rejection wrote state'
    Complete-Plan $workspace 'plan-task';$planEvidence=New-PassEvidence $workspace 'plan-task' $contracts['plan-task'].Digest;$result=Invoke-Cli $workspace @('verify','-TaskId','plan-task','-ExpectedVersion','3','-Evidence',$planEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 0-and(Read-Output $result).task.status-ceq'done') 'completed bound plan permits Evidence completion' 'completed required plan was rejected'

    $created=Start-Verifying $workspace 'audit-task' $contracts['audit-task'] @('independent_review_required');Check ($created.plan_action-ceq'not-required'-and-not(Test-Path (Join-Path $workspace 'docs/tasks/audit-task/plan.md'))-and-not(Test-Path (Join-Path $workspace 'docs/tasks/audit-task/audit.md'))) 'independent review is not auto-started or auto-written' 'independent review created a reviewer artifact'
    $auditEvidence=New-PassEvidence $workspace 'audit-task' $contracts['audit-task'].Digest -WithActor;$resolved=Resolve-HarnessEvidence -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'audit-task' -TaskVersion 3 -ContractDigest $contracts['audit-task'].Digest -RequiredAcceptanceCount 1 -EvidencePath $auditEvidence.Path
    $before=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','audit-task','-ExpectedVersion','3','-Evidence',$auditEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 2-and$result.StdErr-match'independent audit') 'missing required audit blocks done' 'missing required audit was accepted';Same $before (Snapshot $workspace) 'missing audit rejection is zero-write' 'missing audit rejection wrote state'

    Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest $resolved.Digest -ReviewerContext 'context-implementer';$before=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','audit-task','-ExpectedVersion','3','-Evidence',$auditEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 2-and$result.StdErr-match'context must differ') 'same-context reviewer is rejected' 'same-context reviewer was accepted';Same $before (Snapshot $workspace) 'same-context rejection is zero-write' 'same-context rejection wrote state'
    Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest ('sha256:'+('0'*64));$before=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','audit-task','-ExpectedVersion','3','-Evidence',$auditEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 2-and$result.StdErr-match'evidence_digest is stale') 'stale Evidence digest is rejected' 'stale Evidence digest was accepted';Same $before (Snapshot $workspace) 'stale audit rejection is zero-write' 'stale audit rejection wrote state'
    Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest $resolved.Digest -Participated 'true';$before=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','audit-task','-ExpectedVersion','3','-Evidence',$auditEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 2-and$result.StdErr-match'participated') 'participating reviewer is rejected' 'participating reviewer was accepted';Same $before (Snapshot $workspace) 'participation rejection is zero-write' 'participation rejection wrote state'
    $badFinding="- P2: inspect command output | evidence_path=$($auditEvidence.RecordPath) | evidence_digest=sha256:$('0'*64)";Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest $resolved.Digest -Findings $badFinding;$before=Snapshot $workspace;$result=Invoke-Cli $workspace @('verify','-TaskId','audit-task','-ExpectedVersion','3','-Evidence',$auditEvidence.Path,'-AsJson');Check ($result.ExitCode-eq 2-and$result.StdErr-match'finding evidence digest mismatch') 'finding with false file digest is rejected' 'false finding evidence was accepted';Same $before (Snapshot $workspace) 'finding rejection is zero-write' 'finding rejection wrote state'
    $finding="- P2: inspect command output | evidence_path=$($auditEvidence.RecordPath) | evidence_digest=$($auditEvidence.RecordDigest)";Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest $resolved.Digest -Findings $finding;$criticalRejected=$false;try{Resolve-HarnessAuditArtifact -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'audit-task' -TaskVersion 3 -ContractDigest $contracts['audit-task'].Digest -Evidence $resolved -RequiredIndependence different-actor|Out-Null}catch{$criticalRejected=$_.Exception.Message-match'Critical task requires'};Check $criticalRejected 'Critical policy rejects isolated-context audit' 'Critical policy accepted isolated-context audit';$result=Invoke-Cli $workspace @('verify','-TaskId','audit-task','-ExpectedVersion','3','-Evidence',$auditEvidence.Path,'-AsJson');$value=Read-Output $result;Check ($result.ExitCode-eq 0-and$value.task.status-ceq'done'-and$value.audit_path-ceq'docs/tasks/audit-task/audit.md') 'valid isolated-context audit with real file evidence permits governed done' 'valid governed audit was rejected'
    Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest $resolved.Digest -ReviewerActor 'actor-implementer' -Level 'different-actor';$threw=$false;try{Resolve-HarnessAuditArtifact -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'audit-task' -TaskVersion 3 -ContractDigest $contracts['audit-task'].Digest -Evidence $resolved|Out-Null}catch{$threw=$_.Exception.Message-match'different reviewer actor'};Check $threw 'different-actor rejects the implementer identity' 'different-actor accepted the implementer identity'
    Write-Audit $workspace 'audit-task' $contracts['audit-task'].Digest $resolved.Digest -ReviewerActor 'actor-reviewer' -Level 'different-actor';$validDifferent=$true;try{Resolve-HarnessAuditArtifact -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'audit-task' -TaskVersion 3 -ContractDigest $contracts['audit-task'].Digest -Evidence $resolved -RequiredIndependence different-actor|Out-Null}catch{$validDifferent=$false};Check $validDifferent 'Critical different-actor accepts a distinct reviewer identity and context' 'valid Critical different-actor audit was rejected'
}finally{if(Test-Path $temp){Remove-DirectoryWithRetry -Path $temp}}
$repoAfter=@(& git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count-eq 0) 'governance verifier performs no repository writes' 'governance verifier changed repository state'
foreach($item in $script:passes){"[PASS] $item"};foreach($item in $script:failures){"[FAIL] $item"}
if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:passes.Count) checks)";exit 0
