[CmdletBinding()]
param([string]$RepoRoot = '')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($RepoRoot)) { $RepoRoot = Split-Path -Parent $PSScriptRoot }
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $PSScriptRoot 'fixture-test-common.ps1')

$script:checks=[System.Collections.Generic.List[string]]::new();$script:failures=[System.Collections.Generic.List[string]]::new()
function Check($Condition,$Pass,$Fail){if($Condition){$script:checks.Add($Pass)}else{$script:failures.Add($Fail)}}
function New-Gates([string]$Performance='pass'){
    $digest='sha256:'+('2'*64)
    return [ordered]@{
        behavior=[ordered]@{status='pass';evidence_digest=$digest;command='scripts/run-model-evals.ps1 -Model gpt-5.6-sol -Reasoning max'}
        v1_compatibility=[ordered]@{status='pass';evidence_digest=$digest;command='scripts/run-validation.ps1 -Suite all -CheckTimeoutSeconds 360 -VerboseOutput'}
        direct_performance=[ordered]@{status=$Performance;evidence_digest=$digest;command='scripts/run-host-benchmark.ps1 -Groups 3 -Trials 3 -Model gpt-5.6-sol -Reasoning max'}
        core_install_rollback=[ordered]@{status='pass';evidence_digest=$digest;command='scripts/run-isolated-install-smoke.ps1 -Preset core'}
        full_install_rollback=[ordered]@{status='pass';evidence_digest=$digest;command='scripts/run-isolated-install-smoke.ps1 -Preset full'}
    }
}
function New-Report([System.Collections.IDictionary]$Gates,$Distribution=$RepoRoot){return & $script:protocolModule {param($Root,$Values) New-HarnessRolloutReportDocument -RepoRoot $Root -Gates $Values} $Distribution $Gates}
function Set-ReportDigest([System.Collections.IDictionary]$Document){$Document.report_digest=& $script:protocolModule {param($Value) Get-HarnessRolloutReportDigest -Document $Value} $Document}
function Write-Report($Workspace,$Name,[System.Collections.IDictionary]$Document){$relative="rollout/$Name.json";$target=Join-Path $Workspace $relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $target));[IO.File]::WriteAllText($target,($Document|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));return $relative}
function Resolve-Protocol($Workspace,$ReportPath,$TaskId='new-task',$Requested='auto'){return Get-HarnessProtocolResolution -RepoRoot $RepoRoot -WorkspaceRoot $Workspace -TaskId $TaskId -RequestedProtocol $Requested -EligibilityReportPath $ReportPath}
function Resolve-ProtocolDefault($Workspace,$TaskId='new-task',$Requested='auto'){return Get-HarnessProtocolResolution -RepoRoot $RepoRoot -WorkspaceRoot $Workspace -TaskId $TaskId -RequestedProtocol $Requested}
function Test-ExactBytes([byte[]]$Left,[byte[]]$Right){if($Left.Length-ne$Right.Length){return $false};for($i=0;$i-lt$Left.Length;$i++){if($Left[$i]-ne$Right[$i]){return $false}};return $true}
function Invoke-Promotion($Workspace,$ReportPath,$Distribution=$RepoRoot){$output=@(& $script:powerShell -NoLogo -NoProfile -NonInteractive -File $script:promotionPath -RepoRoot $Distribution -WorkspaceRoot $Workspace -ReportPath $ReportPath 2>&1|ForEach-Object{[string]$_});return [pscustomobject]@{ExitCode=$LASTEXITCODE;Output=($output-join"`n")}}
function Set-ReportEnvironment($Value){if($null-eq$Value){Remove-Item Env:HARNESS_V2_ELIGIBILITY_REPORT -ErrorAction SilentlyContinue}else{[Environment]::SetEnvironmentVariable('HARNESS_V2_ELIGIBILITY_REPORT',[string]$Value,[EnvironmentVariableTarget]::Process)}}
function Test-PromotionPathRejected($Module,$Root,$Workspace,$Report,[string[]]$ProtectedRoots=@()){try{$null=& $Module {param($Repo,$Work,$InputReport,$Protected) Resolve-HarnessRolloutPromotionPaths -RepoRoot $Repo -WorkspaceRoot $Work -ReportPath $InputReport -ProtectedRoots $Protected} $Root $Workspace $Report $ProtectedRoots;return $false}catch{return $true}}
function Resolve-ProtocolCanonical($Workspace,$TaskId='new-task',$Requested='auto'){
    $prior=[Environment]::GetEnvironmentVariable('HARNESS_V2_ELIGIBILITY_REPORT',[EnvironmentVariableTarget]::Process)
    try{Set-ReportEnvironment $null;return Resolve-ProtocolDefault $Workspace $TaskId $Requested}
    finally{Set-ReportEnvironment $prior}
}
function New-V2TaskDocument($TaskId){$now=[DateTimeOffset]::UtcNow.ToString('o');return [ordered]@{schema_version='task-state/v2';task_id=$TaskId;version=1;status='ready';identity='existing';intent='write';requirement_state='clear';execution_profile='direct';persistence='ephemeral';policies=[ordered]@{plan_required=$false;approval_required=$false;rollback_required=$false;independent_review_required=$false;verification_required=$true};created_at=$now;updated_at=$now}}

$protocolPath=Join-Path $RepoRoot 'scripts\lib\Harness.Protocol.psm1';$generatorPath=Join-Path $RepoRoot 'scripts\generate-v2-rollout-report.ps1';$script:promotionPath=Join-Path $RepoRoot 'scripts\promote-v2-rollout-report.ps1';$docPath=Join-Path $RepoRoot 'docs\release\compatibility-policy.md';$script:powerShell=(Get-Process -Id $PID).Path
$repoBefore=@(&git -C $RepoRoot status --porcelain --untracked-files=all)
$temp=Join-Path ([IO.Path]::GetTempPath()) ('thin-v2-pr14-'+[guid]::NewGuid().ToString('N'));$workspace=Join-Path $temp 'workspace'
$oldGitDir=[Environment]::GetEnvironmentVariable('GIT_DIR',[EnvironmentVariableTarget]::Process);$oldGitWorkTree=[Environment]::GetEnvironmentVariable('GIT_WORK_TREE',[EnvironmentVariableTarget]::Process)
try{
    [void][IO.Directory]::CreateDirectory($workspace)
    $shadowRepo=Join-Path $temp 'qualification-git';$null=@(&git init --quiet -- $shadowRepo 2>&1);if($LASTEXITCODE-ne0){throw 'shadow qualification Git init failed'}
    $env:GIT_DIR=Join-Path $shadowRepo '.git';$env:GIT_WORK_TREE=$RepoRoot
    $null=@(&git -C $RepoRoot add -A -- 2>&1);if($LASTEXITCODE-ne0){throw 'shadow qualification Git add failed'}
    $null=@(&git -C $RepoRoot -c user.name='Rollout Test' -c user.email='rollout@test.invalid' commit --quiet -m qualification-snapshot 2>&1);if($LASTEXITCODE-ne0){throw 'shadow qualification Git commit failed'}
    foreach($file in @($protocolPath,$generatorPath,$script:promotionPath,$PSCommandPath)){$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($file,[ref]$tokens,[ref]$errors)|Out-Null;Check (@($errors).Count-eq0) "$(Split-Path -Leaf $file) parses" "$(Split-Path -Leaf $file) parse failed";Check (Test-FileHasUtf8Bom $file) "$(Split-Path -Leaf $file) has UTF-8 BOM" "$(Split-Path -Leaf $file) lacks UTF-8 BOM"}
    $script:protocolModule=Import-Module $protocolPath -Force -PassThru;$script:atomicModule=Import-Module (Join-Path $RepoRoot 'scripts\lib\Harness.AtomicWrite.psm1') -Force -PassThru
    $exports=@($script:protocolModule.ExportedFunctions.Keys)
    Check (@(Compare-Object @($exports|Sort-Object) @('Get-HarnessProtocolResolution','Get-HarnessWorkspaceProtocolConfig','Set-HarnessWorkspaceProtocolConfig')).Count-eq0) 'Protocol exports only resolution and workspace config operations' 'Protocol exposed rollout internals or omitted config operations'
    $sourcePaths=@(& $script:protocolModule {param($Root) Get-HarnessRolloutSourcePaths -RepoRoot $Root} $RepoRoot)
    Check ($sourcePaths-ccontains'runtime-hooks/core/pretooluse.ps1'-and$sourcePaths-ccontains'scripts/migrate-task-v1-to-v2.ps1'-and$sourcePaths-ccontains'scripts/run-validation.ps1'-and$sourcePaths-ccontains'tests/verify-v2-approval.ps1') 'rollout source digest covers runtime, migration, validation, and hard-safety tests' 'rollout source digest omits a safety execution surface'
    $generator=Get-Content -LiteralPath $generatorPath -Raw -Encoding utf8
    Check ($generator-match'run-validation\.ps1 -Suite all -CheckTimeoutSeconds 360 -VerboseOutput'-and$generator-match"\[UNAVAILABLE\\\]\\s\+") 'rollout generator exposes and classifies full-suite unavailable evidence' 'rollout generator can collapse unavailable full-suite evidence into pass'

    $promotionSource=Get-Content -LiteralPath $script:promotionPath -Raw -Encoding utf8;$rolloutEvidenceSource=Get-Content -LiteralPath (Join-Path $RepoRoot 'scripts\lib\Harness.RolloutEvidence.psm1') -Raw -Encoding utf8;$atomicSource=Get-Content -LiteralPath (Join-Path $RepoRoot 'scripts\lib\Harness.AtomicWrite.psm1') -Raw -Encoding utf8
    $plainWorkspace=& $script:protocolModule {param($Path) Resolve-HarnessWorkspaceRoot -WorkspaceRoot $Path} $workspace;$slashWorkspace=& $script:protocolModule {param($Path) Resolve-HarnessWorkspaceRoot -WorkspaceRoot $Path} ($workspace+[IO.Path]::DirectorySeparatorChar);$normalizeIndex=$promotionSource.IndexOf('$WorkspaceRoot = [string]$paths.workspace',[StringComparison]::Ordinal);$mutexIndex=$promotionSource.IndexOf('$mutexIdentity = [string]$paths.workspace_identity',[StringComparison]::Ordinal);$sourceSizeIndex=$promotionSource.IndexOf('$sourceInfo.Length -gt 4MB',[StringComparison]::Ordinal);$sourceReadIndex=$promotionSource.IndexOf('$bytes = [IO.File]::ReadAllBytes',[StringComparison]::Ordinal);$readSizeIndex=$promotionSource.IndexOf('$bytes.Length -gt 4MB',[StringComparison]::Ordinal)
    $publishedIndex=$promotionSource.IndexOf('$published = $true',[StringComparison]::Ordinal);$postResolveIndex=$promotionSource.IndexOf('$publishedPaths = & $evidenceModule',[StringComparison]::Ordinal);$targetReadIndex=$promotionSource.IndexOf('$targetBytes = [IO.File]::ReadAllBytes',[StringComparison]::Ordinal)
    Check ($plainWorkspace-ceq$slashWorkspace-and$rolloutEvidenceSource-match'workspace_identity\s*=\s*\$workspaceIdentity'-and$normalizeIndex-ge0-and$mutexIndex-gt$normalizeIndex-and$promotionSource-notmatch'\$WorkspaceRoot\.ToUpperInvariant\(\)') 'promotion mutex uses the physical workspace identity after lexical normalization' 'promotion mutex is not bound to the physical workspace identity'
    Check ($publishedIndex-ge0-and$postResolveIndex-gt$publishedIndex-and$targetReadIndex-gt$postResolveIndex) 'promotion revalidates physical paths after publish before consuming target bytes' 'promotion consumes a published target before post-publish path revalidation'
    Check ($rolloutEvidenceSource-match'Assert-ReleaseSingleLinkFile -Path \$source'-and$rolloutEvidenceSource-match'Assert-ReleaseSingleLinkFile -Path \$target') 'promotion path resolution retains source and target hardlink guards' 'promotion path resolution lost a hardlink guard'
    Check ($rolloutEvidenceSource-match'Assert-ReleaseSingleDataStreamFile -Path \$source'-and$rolloutEvidenceSource-match'Assert-ReleaseSingleDataStreamFile -Path \$target'-and$atomicSource-match'function Write-HarnessAtomicBytes'-and$atomicSource-notmatch'\[System\.IO\.File\]::Copy') 'promotion rejects alternate streams and publishes only validated bytes' 'promotion can copy unvalidated alternate streams'
    Check ($sourceSizeIndex-ge0-and$sourceReadIndex-gt$sourceSizeIndex-and$readSizeIndex-gt$sourceReadIndex) 'promotion rechecks the input size after reading exact bytes' 'promotion can consume bytes that grew beyond the input size limit'

    $missing=Resolve-ProtocolCanonical $workspace
    Check ($missing.selected_protocol-ceq'v1'-and$missing.reason-ceq'rollout-report-missing'-and$missing.rollout_eligibility.status-ceq'missing'-and$missing.warning-match'deprecated') 'missing report keeps new auto task on v1 with a diagnostic warning' 'missing report did not fail safe to v1'

    $pass=New-Report (New-Gates);$passPath=Write-Report $workspace 'pass' $pass;$eligible=Resolve-Protocol $workspace $passPath
    Check ($eligible.selected_protocol-ceq'v2'-and$eligible.reason-ceq'eligible-rollout-report'-and$eligible.rollout_eligibility.status-ceq'pass'-and$null-eq$eligible.warning) 'current all-pass report flips only a new auto task to v2' 'all-pass current report did not select v2'
    $configV1=& $script:protocolModule {param($Root,$Work) Set-HarnessWorkspaceProtocolConfig -RepoRoot $Root -WorkspaceRoot $Work -NewTaskProtocol v1} $RepoRoot $workspace;$workspaceV1=Get-HarnessProtocolResolution -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'workspace-v1' -EligibilityReportPath $passPath
    $configV2=& $script:protocolModule {param($Root,$Work) Set-HarnessWorkspaceProtocolConfig -RepoRoot $Root -WorkspaceRoot $Work -NewTaskProtocol v2} $RepoRoot $workspace;$workspaceV2=Get-HarnessProtocolResolution -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'workspace-v2' -EligibilityReportPath $passPath
    $configAuto=& $script:protocolModule {param($Root,$Work) Set-HarnessWorkspaceProtocolConfig -RepoRoot $Root -WorkspaceRoot $Work -NewTaskProtocol auto} $RepoRoot $workspace;$workspaceAuto=Get-HarnessProtocolResolution -RepoRoot $RepoRoot -WorkspaceRoot $workspace -TaskId 'workspace-auto' -EligibilityReportPath $passPath
    Check ($configV1.new_task_protocol-ceq'v1'-and$workspaceV1.selected_protocol-ceq'v1'-and$workspaceV1.preference_source-ceq'workspace-config'-and$workspaceV1.rollout_eligibility.status-ceq'not-required') 'workspace v1 stop-loss outranks an eligible rollout report' 'eligible rollout overrode workspace v1'
    Check ($configV2.new_task_protocol-ceq'v2'-and$workspaceV2.selected_protocol-ceq'v2'-and$workspaceV2.preference_source-ceq'workspace-config'-and$workspaceV2.rollout_eligibility.status-ceq'not-required') 'workspace v2 opt-in outranks rollout and fallback for a new task' 'workspace v2 did not outrank rollout resolution'
    Check ($configAuto.new_task_protocol-ceq'auto'-and$workspaceAuto.selected_protocol-ceq'v2'-and$workspaceAuto.rollout_eligibility.status-ceq'pass') 'workspace auto delegates to the eligible rollout report' 'workspace auto bypassed rollout qualification'
    Remove-Item -LiteralPath (Join-Path $workspace '.assistant\config\protocol.json') -Force
    $canonicalPath=Join-Path $workspace '.assistant\runtime\rollout\v2-eligibility.json';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $canonicalPath));[IO.File]::WriteAllText($canonicalPath,($pass|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false))
    Check (Test-Path -LiteralPath $canonicalPath -PathType Leaf) 'canonical report fixture exists at the fixed workspace path' 'canonical report fixture was not created'
    $deliveryRoot=Join-Path $temp 'release-input';[void][IO.Directory]::CreateDirectory($deliveryRoot);$deliveryPath=Join-Path $deliveryRoot 'eligible.json';[IO.File]::WriteAllText($deliveryPath,(($pass|ConvertTo-Json -Depth 30)+"`n`n"),[Text.UTF8Encoding]::new($false));$deliveryBytes=[IO.File]::ReadAllBytes($deliveryPath);Remove-Item -LiteralPath $canonicalPath -Force
    $evidenceModule=Import-Module (Join-Path $RepoRoot 'scripts\lib\Harness.RolloutEvidence.psm1') -Force -PassThru;$normalPaths=& $evidenceModule {param($Root,$Workspace,$Report) Resolve-HarnessRolloutPromotionPaths -RepoRoot $Root -WorkspaceRoot $Workspace -ReportPath $Report} $RepoRoot $workspace $deliveryPath;$slashPaths=& $evidenceModule {param($Root,$Workspace,$Report) Resolve-HarnessRolloutPromotionPaths -RepoRoot $Root -WorkspaceRoot $Workspace -ReportPath $Report} $RepoRoot ($workspace+[IO.Path]::DirectorySeparatorChar) $deliveryPath
    Check (-not[string]::IsNullOrWhiteSpace([string]$normalPaths.workspace_identity)-and[string]$normalPaths.workspace_identity-ceq[string]$slashPaths.workspace_identity) 'equivalent workspace spellings resolve to one physical promotion identity' 'equivalent workspace spellings split the physical promotion identity'
    $workspaceBoundaryInput=Join-Path $workspace 'boundary-input.json';[IO.File]::WriteAllText($workspaceBoundaryInput,'{}',[Text.UTF8Encoding]::new($false));Check (Test-PromotionPathRejected $evidenceModule $RepoRoot $workspace $workspaceBoundaryInput) 'promotion rejects a report inside the target workspace' 'promotion accepted a report inside the target workspace'
    Check (Test-PromotionPathRejected $evidenceModule $RepoRoot $workspace $protocolPath) 'promotion rejects a report inside the distribution repository' 'promotion accepted a report inside the distribution repository'
    $credentialRoot=Join-Path $temp 'credential-home';[void][IO.Directory]::CreateDirectory($credentialRoot);$credentialInput=Join-Path $credentialRoot 'report.json';[IO.File]::WriteAllText($credentialInput,'{}',[Text.UTF8Encoding]::new($false));Check (Test-PromotionPathRejected $evidenceModule $RepoRoot $workspace $credentialInput @($credentialRoot)) 'promotion rejects a report inside a credential root' 'promotion accepted a report inside a credential root'
    $aliasTarget=Join-Path $temp 'alias-target';[void][IO.Directory]::CreateDirectory($aliasTarget);$aliasInput=Join-Path $aliasTarget 'report.json';[IO.File]::WriteAllText($aliasInput,'{}',[Text.UTF8Encoding]::new($false));$inputAlias=Join-Path $temp 'input-alias';New-Item -ItemType Junction -Path $inputAlias -Target $aliasTarget|Out-Null;Check (Test-PromotionPathRejected $evidenceModule $RepoRoot $workspace (Join-Path $inputAlias 'report.json')) 'promotion rejects a reparse alias in the report path' 'promotion accepted a reparse alias in the report path'
    $workspaceAlias=Join-Path $temp 'workspace-alias';New-Item -ItemType Junction -Path $workspaceAlias -Target $workspace|Out-Null;Check (Test-PromotionPathRejected $evidenceModule $RepoRoot $workspaceAlias $deliveryPath) 'promotion rejects a reparse alias for the workspace root' 'promotion accepted a reparse alias for the workspace root'
    $promotion=Invoke-Promotion $workspace $deliveryPath
    $promotionPreservedBytes=$promotion.ExitCode-eq0-and(Test-Path -LiteralPath $canonicalPath -PathType Leaf)
    if($promotionPreservedBytes){$promotionPreservedBytes=Test-ExactBytes $deliveryBytes ([IO.File]::ReadAllBytes($canonicalPath))}
    Check $promotionPreservedBytes 'the offline promotion entry publishes exact report bytes to the fixed canonical path' ("promotion failed or re-encoded bytes: "+$promotion.Output)
    $canonicalEligible=Resolve-ProtocolCanonical $workspace
    Check ($canonicalEligible.selected_protocol-ceq'v2'-and$canonicalEligible.rollout_eligibility.status-ceq'pass') 'auto discovers the current canonical workspace report without an environment variable' ("auto did not discover the canonical rollout report: " + ($canonicalEligible|ConvertTo-Json -Depth 10 -Compress))
    $replacementPath=Join-Path $deliveryRoot 'eligible-reformatted.json';[IO.File]::WriteAllText($replacementPath,(($pass|ConvertTo-Json -Depth 30)+"`n `n"),[Text.UTF8Encoding]::new($false));$replacementBytes=[IO.File]::ReadAllBytes($replacementPath);$replacement=Invoke-Promotion $workspace $replacementPath
    $replacementPreserved=$replacement.ExitCode-eq0;if($replacementPreserved){$replacementPreserved=Test-ExactBytes $replacementBytes ([IO.File]::ReadAllBytes($canonicalPath))};Check $replacementPreserved 'promotion atomically replaces an existing canonical report without re-encoding' ("promotion replacement failed: "+$replacement.Output)
    $atomicWorkspace=Join-Path $temp 'atomic-workspace';[void][IO.Directory]::CreateDirectory($atomicWorkspace);$atomicTarget=Join-Path $atomicWorkspace 'state\target.json';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $atomicTarget));[IO.File]::WriteAllText($atomicTarget,'A',[Text.UTF8Encoding]::new($false));$digestA='sha256:'+(Get-FileHash -LiteralPath $atomicTarget -Algorithm SHA256).Hash.ToLowerInvariant();[IO.File]::WriteAllText($atomicTarget,'B',[Text.UTF8Encoding]::new($false));$digestB='sha256:'+(Get-FileHash -LiteralPath $atomicTarget -Algorithm SHA256).Hash.ToLowerInvariant();$sourceDigest='sha256:'+(Get-FileHash -LiteralPath $replacementPath -Algorithm SHA256).Hash.ToLowerInvariant();$casRejected=$false
    try{& $script:atomicModule {param($Root,$SourceBytes,$SourceDigest,$TargetDigest) Write-HarnessAtomicBytes -WorkspaceRoot $Root -SourceBytes $SourceBytes -Path 'state/target.json' -ExpectedSourceDigest $SourceDigest -ExpectedCurrentDigest $TargetDigest} $atomicWorkspace $replacementBytes $sourceDigest $digestA|Out-Null}catch{$casRejected=$true};Check ($casRejected-and([IO.File]::ReadAllText($atomicTarget)-ceq'B')) 'atomic publish rejects stale target CAS and restores exact competing bytes' 'stale target CAS overwrote or lost competing bytes'
    $sourceRejected=$false;try{& $script:atomicModule {param($Root,$SourceBytes,$WrongDigest) Write-HarnessAtomicBytes -WorkspaceRoot $Root -SourceBytes $SourceBytes -Path 'new/deep/target.json' -ExpectedSourceDigest $WrongDigest -ExpectedCurrentDigest missing} $atomicWorkspace $replacementBytes $digestB|Out-Null}catch{$sourceRejected=$true};Check ($sourceRejected-and-not(Test-Path -LiteralPath (Join-Path $atomicWorkspace 'new'))) 'failed source CAS leaves no target parents or publication debris' 'failed source CAS changed workspace structure'
    $deleteRejected=$false;try{& $script:atomicModule {param($Root,$WrongDigest) Remove-HarnessFileIfDigestAtomic -WorkspaceRoot $Root -Path 'state/target.json' -ExpectedDigest $WrongDigest} $atomicWorkspace $digestA|Out-Null}catch{$deleteRejected=$true};Check ($deleteRejected-and([IO.File]::ReadAllText($atomicTarget)-ceq'B')) 'atomic rollback delete restores a target whose digest changed' 'stale rollback delete removed or changed the competing target'
    $deleteSucceeded=& $script:atomicModule {param($Root,$Digest) Remove-HarnessFileIfDigestAtomic -WorkspaceRoot $Root -Path 'state/target.json' -ExpectedDigest $Digest} $atomicWorkspace $digestB;$debris=@(Get-ChildItem -LiteralPath $atomicWorkspace -Force -Recurse|Where-Object{$_.Name-like'.harness-*'});Check ($deleteSucceeded-and-not(Test-Path -LiteralPath $atomicTarget)-and$debris.Count-eq0) 'atomic rollback delete removes only exact published bytes without debris' 'exact rollback delete failed or left publication debris'
    $oversizedTarget=[byte[]]::new(4MB+1);[IO.File]::WriteAllBytes($canonicalPath,$oversizedTarget);$oversizedTargetResult=Invoke-Promotion $workspace $replacementPath
    Check ($oversizedTargetResult.ExitCode-eq2-and$oversizedTargetResult.Output-match'rollout-promotion-target-too-large'-and(Get-Item -LiteralPath $canonicalPath).Length-eq$oversizedTarget.Length) 'promotion rejects an oversized canonical preimage without reading or changing it' 'oversized canonical preimage was consumed or changed'
    [IO.File]::WriteAllBytes($canonicalPath,$replacementBytes)
    $canonicalBeforeRejection=[IO.File]::ReadAllBytes($canonicalPath);$ineligiblePromotion=New-Report (New-Gates 'fail');$ineligiblePromotionPath=Join-Path $deliveryRoot 'ineligible.json';[IO.File]::WriteAllText($ineligiblePromotionPath,($ineligiblePromotion|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$ineligibleResult=Invoke-Promotion $workspace $ineligiblePromotionPath
    $ineligiblePreserved=$ineligibleResult.ExitCode-eq2;if($ineligiblePreserved){$ineligiblePreserved=Test-ExactBytes $canonicalBeforeRejection ([IO.File]::ReadAllBytes($canonicalPath))};Check $ineligiblePreserved 'promotion rejects an ineligible report without changing canonical bytes' 'ineligible promotion changed canonical bytes or returned the wrong exit code'
    $tamperedPromotion=New-Report (New-Gates);$tamperedPromotion.report_digest='sha256:'+('f'*64);$tamperedPromotionPath=Join-Path $deliveryRoot 'tampered.json';[IO.File]::WriteAllText($tamperedPromotionPath,($tamperedPromotion|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$tamperedPromotionResult=Invoke-Promotion $workspace $tamperedPromotionPath
    $tamperedPreserved=$tamperedPromotionResult.ExitCode-eq2;if($tamperedPreserved){$tamperedPreserved=Test-ExactBytes $canonicalBeforeRejection ([IO.File]::ReadAllBytes($canonicalPath))};Check $tamperedPreserved 'promotion rejects a tampered report without changing canonical bytes' 'tampered promotion changed canonical bytes or returned the wrong exit code'
    $rollbackFixtureRoot=Join-Path $RepoRoot '.assistant\runtime\test-fixtures';$rollbackRepo=Join-Path $rollbackFixtureRoot ('post-publish-rollback-repo-'+[guid]::NewGuid().ToString('N'));$activeGitDir=$env:GIT_DIR;$activeGitWorkTree=$env:GIT_WORK_TREE
    try{
        Remove-Item Env:GIT_DIR,Env:GIT_WORK_TREE -ErrorAction SilentlyContinue;$null=@(&git clone --quiet --no-hardlinks -- $shadowRepo $rollbackRepo 2>&1);if($LASTEXITCODE-ne0){throw 'post-publish rollback clone failed'}
        $rollbackCanonical=Join-Path $rollbackRepo '.assistant\runtime\rollout\v2-eligibility.json';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $rollbackCanonical));$rollbackPreimage=[Text.UTF8Encoding]::new($false).GetBytes('{"sentinel":"preserve"}');[IO.File]::WriteAllBytes($rollbackCanonical,$rollbackPreimage)
        $null=@(&git -C $rollbackRepo add -f -- '.assistant/runtime/rollout/v2-eligibility.json' 2>&1);$null=@(&git -C $rollbackRepo -c user.name='Rollout Test' -c user.email='rollout@test.invalid' commit --quiet -m canonical-preimage 2>&1);if($LASTEXITCODE-ne0){throw 'post-publish rollback fixture commit failed'}
        $rollbackDocument=New-Report (New-Gates) $rollbackRepo;$rollbackInput=Join-Path $deliveryRoot 'post-publish-rollback.json';[IO.File]::WriteAllText($rollbackInput,($rollbackDocument|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$rollbackResult=Invoke-Promotion $rollbackRepo $rollbackInput $rollbackRepo
        $rollbackStatus=@(&git -C $rollbackRepo status --porcelain --untracked-files=all);$rollbackDebris=@(Get-ChildItem -LiteralPath $rollbackRepo -Force -Recurse|Where-Object{$_.Name-like'.harness-*'});$rollbackRestored=$rollbackResult.ExitCode-eq2-and$rollbackResult.Output-match'rollout-promotion-source-changed'-and(Test-ExactBytes $rollbackPreimage ([IO.File]::ReadAllBytes($rollbackCanonical)))-and$rollbackStatus.Count-eq0-and$rollbackDebris.Count-eq0
        Check $rollbackRestored 'post-publish source-state failure restores exact canonical bytes and clean repository state' ("post-publish rollback failed: "+$rollbackResult.Output)
        $null=@(&git -C $rollbackRepo rm --quiet -- '.assistant/runtime/rollout/v2-eligibility.json' 2>&1);$ignorePath=Join-Path $rollbackRepo '.gitignore';[IO.File]::AppendAllText($ignorePath,"`n!.assistant/`n!.assistant/runtime/`n!.assistant/runtime/rollout/`n!.assistant/runtime/rollout/v2-eligibility.json`n",[Text.UTF8Encoding]::new($false));$null=@(&git -C $rollbackRepo add -- '.gitignore' 2>&1);$null=@(&git -C $rollbackRepo -c user.name='Rollout Test' -c user.email='rollout@test.invalid' commit --quiet -m canonical-absent 2>&1);if($LASTEXITCODE-ne0){throw 'missing-preimage rollback fixture commit failed'};$rollbackAssistant=Join-Path $rollbackRepo '.assistant';if(Test-Path -LiteralPath $rollbackAssistant){Remove-Item -LiteralPath $rollbackAssistant -Recurse -Force}
        $missingRollbackDocument=New-Report (New-Gates) $rollbackRepo;$missingRollbackInput=Join-Path $deliveryRoot 'post-publish-missing-rollback.json';[IO.File]::WriteAllText($missingRollbackInput,($missingRollbackDocument|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$missingRollbackResult=Invoke-Promotion $rollbackRepo $missingRollbackInput $rollbackRepo
        $missingRollbackStatus=@(&git -C $rollbackRepo status --porcelain --untracked-files=all);$missingRollbackDebris=@(Get-ChildItem -LiteralPath $rollbackRepo -Force -Recurse|Where-Object{$_.Name-like'.harness-*'});$missingRollbackClean=$missingRollbackResult.ExitCode-eq2-and$missingRollbackResult.Output-match'rollout-promotion-source-changed'-and-not(Test-Path -LiteralPath $rollbackCanonical)-and-not(Test-Path -LiteralPath $rollbackAssistant)-and$missingRollbackStatus.Count-eq0-and$missingRollbackDebris.Count-eq0
        Check $missingRollbackClean 'post-publish failure removes a newly created canonical report and its empty parents' ("missing-preimage rollback failed: "+$missingRollbackResult.Output)
    }finally{
        if($null-eq$activeGitDir){Remove-Item Env:GIT_DIR -ErrorAction SilentlyContinue}else{$env:GIT_DIR=$activeGitDir};if($null-eq$activeGitWorkTree){Remove-Item Env:GIT_WORK_TREE -ErrorAction SilentlyContinue}else{$env:GIT_WORK_TREE=$activeGitWorkTree}
        Remove-DirectoryWithRetry -Path $rollbackRepo
        if((Test-Path -LiteralPath $rollbackFixtureRoot -PathType Container)-and@(Get-ChildItem -LiteralPath $rollbackFixtureRoot -Force).Count-eq0){[IO.Directory]::Delete($rollbackFixtureRoot,$false)}
    }
    $oversizedReportPath='rollout/oversized.json';[IO.File]::WriteAllBytes((Join-Path $workspace $oversizedReportPath),$oversizedTarget)
    $missingExplicit=Resolve-Protocol $workspace 'rollout/missing-explicit.json'
    Check ($missingExplicit.selected_protocol-ceq'v1'-and$missingExplicit.reason-ceq'rollout-report-missing') 'an explicitly selected missing report fails closed instead of falling through to canonical' 'missing explicit report fell through to canonical'
    $failedCanonical=New-Report (New-Gates 'fail');[IO.File]::WriteAllText($canonicalPath,($failedCanonical|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false));$explicitPreferred=Resolve-Protocol $workspace $passPath
    Check ($explicitPreferred.selected_protocol-ceq'v2') 'an explicit valid report has priority over canonical' 'canonical report overrode an explicit report'
    [IO.File]::WriteAllBytes($canonicalPath,$replacementBytes);$invalidEnvironmentPath='rollout/invalid-environment.json';[IO.File]::WriteAllText((Join-Path $workspace $invalidEnvironmentPath),'{',[Text.UTF8Encoding]::new($false))
    $priorReport=[Environment]::GetEnvironmentVariable('HARNESS_V2_ELIGIBILITY_REPORT',[EnvironmentVariableTarget]::Process)
    try{
        $env:HARNESS_V2_ELIGIBILITY_REPORT=$passPath;$environmentPreferred=Resolve-ProtocolDefault $workspace;Check ($environmentPreferred.selected_protocol-ceq'v2') 'the report environment variable has priority over canonical' 'canonical report overrode the environment report'
        $explicitOversizedWithEnvironment=Resolve-Protocol $workspace $oversizedReportPath;Check ($explicitOversizedWithEnvironment.selected_protocol-ceq'v1'-and$explicitOversizedWithEnvironment.reason-ceq'rollout-report-too-large'-and$explicitOversizedWithEnvironment.rollout_eligibility.status-ceq'invalid') 'an oversized explicit report blocks valid environment and canonical fallback' 'oversized explicit report fell through to environment or canonical'
        $explicitEmptyWithEnvironment=Resolve-Protocol $workspace '';Check ($explicitEmptyWithEnvironment.selected_protocol-ceq'v1'-and$explicitEmptyWithEnvironment.reason-ceq'rollout-report-missing'-and$explicitEmptyWithEnvironment.rollout_eligibility.status-ceq'missing') 'an explicitly selected empty report blocks valid environment and canonical fallback' 'empty explicit report fell through to environment or canonical'
        $explicitMissingWithEnvironment=Resolve-Protocol $workspace 'rollout/missing-explicit.json';Check ($explicitMissingWithEnvironment.selected_protocol-ceq'v1') 'a missing explicit report outranks a valid environment report and fails closed' 'a valid environment report masked a missing explicit selection'
        $explicitInvalidWithEnvironment=Resolve-Protocol $workspace $invalidEnvironmentPath;Check ($explicitInvalidWithEnvironment.selected_protocol-ceq'v1'-and$explicitInvalidWithEnvironment.reason-ceq'rollout-report-invalid-json') 'an invalid explicit report blocks valid environment and canonical fallback' 'invalid explicit report fell through to environment or canonical'
        New-Item -Path Env:HARNESS_V2_ELIGIBILITY_REPORT -Value '' -Force|Out-Null;$environmentEmpty=Resolve-ProtocolDefault $workspace;Check ($environmentEmpty.selected_protocol-ceq'v1'-and$environmentEmpty.reason-ceq'rollout-report-missing') 'a defined empty report environment variable blocks canonical fallback' 'empty report environment variable fell through to canonical'
        $env:HARNESS_V2_ELIGIBILITY_REPORT=$invalidEnvironmentPath;$environmentInvalid=Resolve-ProtocolDefault $workspace;Check ($environmentInvalid.selected_protocol-ceq'v1'-and$environmentInvalid.reason-ceq'rollout-report-invalid-json'-and$environmentInvalid.rollout_eligibility.status-ceq'invalid') 'an invalid environment report fails closed instead of using canonical' 'invalid environment report fell through to canonical'
        $env:HARNESS_V2_ELIGIBILITY_REPORT=$oversizedReportPath;$environmentOversized=Resolve-ProtocolDefault $workspace;Check ($environmentOversized.selected_protocol-ceq'v1'-and$environmentOversized.reason-ceq'rollout-report-too-large'-and$environmentOversized.rollout_eligibility.status-ceq'invalid') 'an oversized environment report fails closed instead of using canonical' 'oversized environment report fell through to canonical'
        $env:HARNESS_V2_ELIGIBILITY_REPORT='rollout/missing-environment.json';$environmentMissing=Resolve-ProtocolDefault $workspace;Check ($environmentMissing.selected_protocol-ceq'v1'-and$environmentMissing.reason-ceq'rollout-report-missing') 'a missing environment report fails closed instead of falling through to canonical' 'missing environment report fell through to canonical'
    }finally{Set-ReportEnvironment $priorReport}
    [IO.File]::WriteAllBytes($canonicalPath,$oversizedTarget);$canonicalOversized=Resolve-ProtocolCanonical $workspace;Check ($canonicalOversized.selected_protocol-ceq'v1'-and$canonicalOversized.reason-ceq'rollout-report-too-large'-and$canonicalOversized.rollout_eligibility.status-ceq'invalid') 'an oversized canonical report fails closed when no higher-priority source is selected' 'oversized canonical report did not fail closed'
    [IO.File]::WriteAllText($canonicalPath,($pass|ConvertTo-Json -Depth 30),[Text.UTF8Encoding]::new($false))
    $null=@(&git -C $RepoRoot rm --cached --quiet -- scripts/lib/Harness.RolloutEvidence.psm1 2>&1);if($LASTEXITCODE-ne0){throw 'shadow untracked-source setup failed'}
    $dirtyDistribution=Resolve-Protocol $workspace $passPath
    Check ($dirtyDistribution.selected_protocol-ceq'v1'-and$dirtyDistribution.reason-ceq'rollout-source-dirty') 'untracked distribution source invalidates an otherwise current report' 'untracked distribution source kept auto on v2'
    $dirtyCanonicalBytes=[IO.File]::ReadAllBytes($canonicalPath);$dirtyPromotion=Invoke-Promotion $workspace $deliveryPath
    $dirtyPreserved=$dirtyPromotion.ExitCode-eq2;if($dirtyPreserved){$dirtyPreserved=Test-ExactBytes $dirtyCanonicalBytes ([IO.File]::ReadAllBytes($canonicalPath))};Check $dirtyPreserved 'promotion rejects a dirty distribution without changing canonical bytes' 'dirty distribution promotion changed canonical bytes or returned the wrong exit code'
    $null=@(&git -C $RepoRoot add -- scripts/lib/Harness.RolloutEvidence.psm1 2>&1);if($LASTEXITCODE-ne0){throw 'shadow untracked-source restore failed'}

    foreach($status in @('fail','blocked','unavailable','simulated')){
        $document=New-Report (New-Gates $status);$path=Write-Report $workspace "performance-$status" $document;$result=Resolve-Protocol $workspace $path
        Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq"rollout-gate-direct_performance-$status") "$status performance gate keeps auto on v1" "$status performance gate selected v2"
    }
    foreach($case in @(
        [pscustomobject]@{name='behavior';status='unavailable'},
        [pscustomobject]@{name='v1_compatibility';status='blocked'},
        [pscustomobject]@{name='core_install_rollback';status='fail'},
        [pscustomobject]@{name='full_install_rollback';status='simulated'}
    )){
        $gates=New-Gates;$gates[$case.name].status=$case.status;$document=New-Report $gates;$path=Write-Report $workspace ("gate-{0}-{1}" -f $case.name,$case.status) $document;$result=Resolve-Protocol $workspace $path
        Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq("rollout-gate-{0}-{1}" -f $case.name,$case.status)) "$($case.name) $($case.status) keeps auto on v1" "$($case.name) $($case.status) selected v2"
    }

    $staleRevision=($pass|ConvertTo-Json -Depth 30)|ConvertFrom-Json -AsHashtable -Depth 30;$staleRevision.source_revision='0'*40;Set-ReportDigest $staleRevision;$path=Write-Report $workspace 'stale-revision' $staleRevision;$result=Resolve-Protocol $workspace $path
    Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq'rollout-report-stale-revision') 'stale revision fails closed' 'stale revision selected v2'
    $staleSource=($pass|ConvertTo-Json -Depth 30)|ConvertFrom-Json -AsHashtable -Depth 30;$staleSource.source_digest='sha256:'+('3'*64);Set-ReportDigest $staleSource;$path=Write-Report $workspace 'stale-source' $staleSource;$result=Resolve-Protocol $workspace $path
    Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq'rollout-report-stale-source') 'stale source digest fails closed' 'stale source digest selected v2'
    $staleGenerator=($pass|ConvertTo-Json -Depth 30)|ConvertFrom-Json -AsHashtable -Depth 30;$staleGenerator.generator_digest='sha256:'+('4'*64);Set-ReportDigest $staleGenerator;$path=Write-Report $workspace 'stale-generator' $staleGenerator;$result=Resolve-Protocol $workspace $path
    Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq'rollout-report-stale-generator') 'stale generator digest fails closed' 'stale generator selected v2'
    $tampered=($pass|ConvertTo-Json -Depth 30)|ConvertFrom-Json -AsHashtable -Depth 30;$tampered.gates.behavior.evidence_digest='sha256:'+('5'*64);$path=Write-Report $workspace 'tampered' $tampered;$result=Resolve-Protocol $workspace $path
    Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq'rollout-report-digest-mismatch') 'tampered report digest fails closed' 'tampered report selected v2'
    $proxy=($pass|ConvertTo-Json -Depth 30)|ConvertFrom-Json -AsHashtable -Depth 30;$proxy.gates.behavior.command='tests/run-scenario-evals.ps1 -Suite core';Set-ReportDigest $proxy;$path=Write-Report $workspace 'proxy-command' $proxy;$result=Resolve-Protocol $workspace $path
    Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq'rollout-report-invalid-gate') 'deterministic proxy command fails closed' 'deterministic proxy command selected v2'
    $extra=($pass|ConvertTo-Json -Depth 30)|ConvertFrom-Json -AsHashtable -Depth 30;$extra['authorization_bypass']=$true;$path=Write-Report $workspace 'extra-key' $extra;$result=Resolve-Protocol $workspace $path
    Check ($result.selected_protocol-ceq'v1'-and$result.reason-ceq'rollout-report-invalid-document') 'unknown report fields fail closed' 'unknown report field selected v2'
    $outside=Resolve-Protocol $workspace '..\outside-report.json'
    Check ($outside.selected_protocol-ceq'v1'-and$outside.rollout_eligibility.status-ceq'invalid') 'report path escape fails closed' 'outside report path was accepted'

    $v1Id='existing-v1';$v1Path=Join-Path $workspace "docs\tasks\$v1Id\plan.md";[void][IO.Directory]::CreateDirectory((Split-Path -Parent $v1Path));[IO.File]::WriteAllText($v1Path,"---`ntask_id: existing-v1`nstage: TEST`ntool: codex`nupdated: 2026-07-14`n---`n",[Text.UTF8Encoding]::new($false))
    $existingV1=Resolve-Protocol $workspace $passPath $v1Id
    Check ($existingV1.selected_protocol-ceq'v1'-and$existingV1.detected_protocol-ceq'v1'-and$existingV1.rollout_eligibility.status-ceq'not-required') 'existing v1 artifact overrides an eligible rollout report' 'eligible report converted existing v1 task'
    $v2Id='existing-v2';$v2Path=Join-Path $workspace ".assistant\runtime\tasks\$v2Id\task.json";[void][IO.Directory]::CreateDirectory((Split-Path -Parent $v2Path));[IO.File]::WriteAllText($v2Path,((New-V2TaskDocument $v2Id)|ConvertTo-Json -Depth 20 -Compress),[Text.UTF8Encoding]::new($false));$failedPath=Write-Report $workspace 'failed' (New-Report (New-Gates 'fail'))
    $existingV2=Resolve-Protocol $workspace $failedPath $v2Id
    Check ($existingV2.selected_protocol-ceq'v2'-and$existingV2.detected_protocol-ceq'v2'-and$existingV2.rollout_eligibility.status-ceq'not-required') 'existing v2 artifact overrides an ineligible report' 'ineligible report downgraded existing v2 task'
    $explicitV1=Resolve-Protocol $workspace $passPath 'explicit-new' 'v1';$explicitV2=Resolve-Protocol $workspace '' 'explicit-new' 'v2'
    Check ($explicitV1.selected_protocol-ceq'v1'-and$explicitV1.reason-ceq'explicit-v1-new-task'-and$explicitV2.selected_protocol-ceq'v2'-and$explicitV2.reason-ceq'explicit-v2-new-task') 'explicit v1 rollback and v2 opt-in remain deterministic' 'explicit protocol behavior drifted'

    $oldProtocol=$env:HARNESS_PROTOCOL;$oldReport=[Environment]::GetEnvironmentVariable('HARNESS_V2_ELIGIBILITY_REPORT',[EnvironmentVariableTarget]::Process)
    $workspaceBefore=@(Get-ChildItem -LiteralPath $workspace -Force -Recurse|ForEach-Object{$relative=$_.FullName.Substring($workspace.Length).TrimStart('\','/');if($_.PSIsContainer){"D|$relative"}else{"F|$relative|$((Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash)"}}|Sort-Object)
    try{$env:HARNESS_PROTOCOL='auto';Set-ReportEnvironment $null;Import-Module (Join-Path $RepoRoot 'scripts\lib\Harness.Policy.psm1') -Force;$zero=[ordered]@{user_visible_behavior=0;data_integrity=0;authorization_and_security=0;external_side_effects=0;blast_radius=0;rollback=0;verification_coverage=0};$route=Resolve-HarnessExecutionProfile -RepoRoot $RepoRoot -WorkspaceRoot $workspace -RiskScores $zero}finally{if($null-eq$oldProtocol){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$oldProtocol};Set-ReportEnvironment $oldReport;Remove-Module Harness.Policy -ErrorAction Ignore}
    $workspaceAfter=@(Get-ChildItem -LiteralPath $workspace -Force -Recurse|ForEach-Object{$relative=$_.FullName.Substring($workspace.Length).TrimStart('\','/');if($_.PSIsContainer){"D|$relative"}else{"F|$relative|$((Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash)"}}|Sort-Object);Check ($route.selected_protocol-ceq'v2'-and$route.profile-ceq'direct'-and@(Compare-Object $workspaceBefore $workspaceAfter).Count-eq0) 'canonical eligible auto reaches v2 Direct with zero workspace writes' ("Policy route or zero-write contract failed: " + ($route|ConvertTo-Json -Depth 10 -Compress))

    $doc=Get-Content -LiteralPath $docPath -Raw -Encoding utf8
    Check ($doc-match'HARNESS_PROTOCOL=v1'-and$doc-match'does not delete v1'-and$doc-match'complete external release cycle') 'compatibility policy documents rollback, retention, and external release-cycle boundary' 'compatibility policy is incomplete'
}finally{
    if($null-eq$oldGitDir){Remove-Item Env:GIT_DIR -ErrorAction Ignore}else{$env:GIT_DIR=$oldGitDir}
    if($null-eq$oldGitWorkTree){Remove-Item Env:GIT_WORK_TREE -ErrorAction Ignore}else{$env:GIT_WORK_TREE=$oldGitWorkTree}
    Remove-Module Harness.Protocol -ErrorAction Ignore;if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}
}
$repoAfter=@(&git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count-eq0) 'default-flip verifier leaves repository state unchanged' 'default-flip verifier changed repository state'
foreach($item in $script:checks){"[PASS] $item"};foreach($item in $script:failures){"[FAIL] $item"};if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:checks.Count) checks)";exit 0
