[CmdletBinding()]
param([string]$RepoRoot = '')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($RepoRoot)) { $RepoRoot = Split-Path -Parent $PSScriptRoot }
$RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $RepoRoot 'tests/fixture-test-common.ps1')
$taskScript = Join-Path $RepoRoot 'scripts/task.ps1'
$script:passes=[Collections.Generic.List[string]]::new();$script:failures=[Collections.Generic.List[string]]::new();$script:unavailable=[Collections.Generic.List[string]]::new()
function Check($Condition,$Pass,$Fail){if($Condition){$script:passes.Add($Pass)}else{$script:failures.Add($Fail)}}
function Snapshot($Root){return @(Get-ChildItem $Root -Force -Recurse|%{if($_.PSIsContainer){'D|'+$_.FullName}else{'F|'+$_.FullName+'|'+(Get-FileHash $_.FullName).Hash}}|Sort-Object)}
function Same($Before,$After,$Pass,$Fail){Check (@(Compare-Object @($Before) @($After)).Count -eq 0) $Pass $Fail}
function Digest($Text){$h=[Security.Cryptography.SHA256]::Create();try{return 'sha256:'+([BitConverter]::ToString($h.ComputeHash([Text.UTF8Encoding]::new($false).GetBytes($Text))).Replace('-','').ToLowerInvariant())}finally{$h.Dispose()}}
function Write-Contract($Workspace,$TaskId,$Name,$Revision='one'){
    $b=[ordered]@{schema_version='requirement-contract/v1';task_id=$TaskId;goal="Test $TaskId.";acceptance=@('Durable.');in_scope=@('v2');out_of_scope=@('v1');product_constraints=@('No v1 writes.');product_decisions=@([ordered]@{key='revision';value=$Revision;source='user-confirmed:2026-07-14'});unresolved_product_decisions=@();source_authority=@('current-user-message')}
    $c=[ordered]@{};foreach($k in $b.Keys){$c[$k]=$b[$k]};$c.digest=Digest ($b|ConvertTo-Json -Depth 20 -Compress)
    $p=Join-Path $Workspace $Name;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $p));[IO.File]::WriteAllText($p,(($c|ConvertTo-Json -Depth 20)+"`n"),[Text.UTF8Encoding]::new($false));return $Name
}

function Start-Cli($Workspace,[string[]]$Arguments,[AllowNull()]$Protocol='v2',$Fault='',$FaultBeforeClaimRelease='',$DelayBeforeCommit='',$FailBeforeFirstClaim='',$FailIdentityRecheck=''){
    $oldP=$env:HARNESS_PROTOCOL;$oldF=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP;$oldC=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_CLAIM_RELEASE;$oldD=$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_COMMIT_MS;$oldB=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM;$oldI=$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_IDENTITY_RECHECK
    try{
        if($null -eq $Protocol){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$Protocol}
        if($Fault){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP=$Fault}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP -ErrorAction Ignore}
        if($FaultBeforeClaimRelease){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_CLAIM_RELEASE=$FaultBeforeClaimRelease}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_CLAIM_RELEASE -ErrorAction Ignore}
        if($DelayBeforeCommit){$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_COMMIT_MS=$DelayBeforeCommit}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_COMMIT_MS -ErrorAction Ignore}
        if($FailBeforeFirstClaim){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM=$FailBeforeFirstClaim}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM -ErrorAction Ignore}
        if($FailIdentityRecheck){$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_IDENTITY_RECHECK=$FailIdentityRecheck}else{Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_IDENTITY_RECHECK -ErrorAction Ignore}
        return Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $taskScript -Arguments ($Arguments+@('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$Workspace))
    }finally{
        if($null -eq $oldP){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$oldP}
        if($null -eq $oldF){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_AFTER_STEP=$oldF}
        if($null -eq $oldC){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_CLAIM_RELEASE -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_CLAIM_RELEASE=$oldC}
        if($null -eq $oldD){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_COMMIT_MS -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_DELAY_BEFORE_COMMIT_MS=$oldD}
        if($null -eq $oldB){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_BEFORE_FIRST_CLAIM=$oldB}
        if($null -eq $oldI){Remove-Item Env:DEV_HARNESS_TEST_TASK_STATE_FAIL_IDENTITY_RECHECK -ErrorAction Ignore}else{$env:DEV_HARNESS_TEST_TASK_STATE_FAIL_IDENTITY_RECHECK=$oldI}
    }
}
function Complete-Cli($Handle){if(-not $Handle.Process.WaitForExit(30000)){$Handle.Process.Kill($true);throw 'task CLI timeout'};$r=[pscustomobject]@{ExitCode=$Handle.Process.ExitCode;StdOut=$Handle.StdOut.GetAwaiter().GetResult().Trim();StdErr=$Handle.StdErr.GetAwaiter().GetResult().Trim()};$Handle.Process.Dispose();return $r}
function Invoke-Cli($Workspace,[string[]]$Arguments,[AllowNull()]$Protocol='v2',$Fault='',$FaultBeforeClaimRelease='',$DelayBeforeCommit='',$FailBeforeFirstClaim='',$FailIdentityRecheck=''){return Complete-Cli (Start-Cli $Workspace $Arguments $Protocol $Fault $FaultBeforeClaimRelease $DelayBeforeCommit $FailBeforeFirstClaim $FailIdentityRecheck)}
function Read-Output($Result){if($Result.StdOut){return $Result.StdOut|ConvertFrom-Json -Depth 50 -DateKind String};return $null}

$repoBefore=@(& git -C $RepoRoot status --porcelain --untracked-files=all)
$temp=Join-Path ([IO.Path]::GetTempPath()) ('v2-state-'+[guid]::NewGuid().ToString('N'))
$workspace=Join-Path $temp 'workspace';$identityRaceWorkspace=Join-Path $temp 'identity-race';$identityWriteWorkspace=Join-Path $temp 'identity-write';$crashWorkspace=Join-Path $temp 'crash';$journalClaimWorkspace=Join-Path $temp 'journal-claim-recovery';$claimBlockWorkspace=Join-Path $temp 'claim-block';$pendingBlockWorkspace=Join-Path $temp 'pending-block';$writerReplayWorkspace=Join-Path $temp 'writer-replay';$pointerOmissionWorkspace=Join-Path $temp 'pointer-omission';$releasedClaimWorkspace=Join-Path $temp 'released-claim';$aliasReplayWorkspace=Join-Path $temp 'volume-alias-replay';$legacyPreparedWorkspace=Join-Path $temp 'legacy-prepared';$legacyLagWorkspace=Join-Path $temp 'legacy-lag';$legacyPrefixWorkspace=Join-Path $temp 'legacy-prefix';$legacyTransitionWorkspace=Join-Path $temp 'legacy-transition';$legacyHybridWorkspace=Join-Path $temp 'legacy-hybrid';$legacyOverlapWorkspace=Join-Path $temp 'legacy-overlap';$legacyAliasWorkspace=Join-Path $temp 'legacy-volume-alias';$outside=Join-Path $temp 'outside';$casWorkspace=Join-Path $temp 'cas';$claimWorkspace=Join-Path $temp 'claim-recovery'
foreach($path in @($workspace,$identityRaceWorkspace,$identityWriteWorkspace,$crashWorkspace,$journalClaimWorkspace,$claimBlockWorkspace,$pendingBlockWorkspace,$writerReplayWorkspace,$pointerOmissionWorkspace,$releasedClaimWorkspace,$aliasReplayWorkspace,$legacyPreparedWorkspace,$legacyLagWorkspace,$legacyPrefixWorkspace,$legacyTransitionWorkspace,$legacyHybridWorkspace,$legacyOverlapWorkspace,$legacyAliasWorkspace,$outside,$casWorkspace,$claimWorkspace)){[void][IO.Directory]::CreateDirectory($path)}
foreach($file in @('scripts/lib/Harness.Path.psm1','scripts/lib/Harness.AtomicWrite.psm1','scripts/lib/Harness.TaskState.psm1','scripts/task.ps1','tests/fixtures/v2-task-state-atomic-step.ps1','tests/verify-v2-task-state.ps1')){
    $tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile((Join-Path $RepoRoot $file),[ref]$tokens,[ref]$errors)|Out-Null
    Check (@($errors).Count -eq 0) "$file parses" "$file parse failed"
}
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.TaskState.psm1') -Force
$exports=@(Get-Command -Module Harness.TaskState|Select-Object -ExpandProperty Name|Sort-Object)
Check (@(Compare-Object @('Get-HarnessTaskStatus','New-HarnessTaskState','Repair-HarnessTaskTransaction','Resume-HarnessTaskExecution','Set-HarnessTaskApproval','Set-HarnessTaskEvidence','Set-HarnessTaskTransition') $exports).Count -eq 0) 'TaskState exports are exact' 'TaskState exports drifted'
$taskStateModule=@(Get-Module -Name Harness.TaskState)[-1]
$sourceReplayId='txn_00000000000000000000000000000002';$shimPath=Join-Path $workspace '.assistant/entry/task.ps1';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $shimPath));[IO.File]::WriteAllText($shimPath,'# unrelated workspace file',[Text.UTF8Encoding]::new($false));$sourceReplayCommand=& $taskStateModule {param($Root,$Id)Get-TaskReplayCommand -WorkspaceRoot $Root -TransactionId $Id} $workspace $sourceReplayId;$sourceTaskPath=Join-Path $RepoRoot 'scripts/task.ps1';$quotedShim="'"+($shimPath-replace"'","''")+"'";$quotedWorkspace="'"+($workspace-replace"'","''")+"'";$fakeShimCommand="pwsh -File $quotedShim replay -TransactionId $sourceReplayId -WorkspaceRoot $quotedWorkspace";$quotedRelativeCommand="pwsh -File 'scripts/task.ps1' replay -TransactionId $sourceReplayId -WorkspaceRoot $quotedWorkspace";$invalidCount=0;foreach($command in @($fakeShimCommand,$quotedRelativeCommand)){try{& $taskStateModule {param($Root,$Id,$Value)Get-TaskReplayCommandWorkspace -WorkspaceRoot $Root -TransactionId $Id -ReplayCommand $Value -Label 'test journal'} $workspace $sourceReplayId $command|Out-Null}catch{if($_.Exception.Message-match'replay command is invalid'){$invalidCount++}}};Check ($sourceReplayCommand-match[regex]::Escape("pwsh -File '"+($sourceTaskPath-replace"'","''")+"' replay -TransactionId $sourceReplayId -WorkspaceRoot '")-and$sourceReplayCommand.EndsWith("'")-and$invalidCount-eq2) 'journal records a fully-qualified trusted repo CLI and rejects arbitrary or relative quoted scripts' 'journal accepted an untrusted replay CLI';Remove-Item -LiteralPath (Join-Path $workspace '.assistant') -Recurse -Force
function Set-JournalIdentity($Journal,$TransactionId,$WorkspaceRoot){
    $Journal.transaction_id=$TransactionId
    $Journal.replay_command=& $taskStateModule {param($Root,$Id)Get-TaskReplayCommand -WorkspaceRoot $Root -TransactionId $Id} $WorkspaceRoot $TransactionId
    $Journal.intent_digest=& $taskStateModule {param($Value)Get-TransactionIntentDigest -Journal $Value} $Journal
}
function Refresh-JournalIntent($Journal){$Journal.intent_digest=& $taskStateModule {param($Value)Get-TransactionIntentDigest -Journal $Value} $Journal}
function Set-JournalStepContent($Journal,$StepId,$Content){
    $step=@($Journal.steps|Where-Object{[string]$_.id-ceq$StepId})[0]
    $step.content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes($Content))
    $step.after_digest=Digest $Content
}
function Get-JournalStepJson($Journal,$StepId){
    $step=@($Journal.steps|Where-Object{[string]$_.id-ceq$StepId})[0]
    return [Text.UTF8Encoding]::new($false,$true).GetString([Convert]::FromBase64String([string]$step.content_base64))|ConvertFrom-Json -AsHashtable -DateKind String
}
function Prepare-JournalFixture($Journal,$TransactionId,$WorkspaceRoot){
    $Journal.status='failed';$Journal.completed_steps=@();$Journal.failed_step=[string]$Journal.steps[0].id;$Journal.error='intent fixture'
    Set-JournalIdentity $Journal $TransactionId $WorkspaceRoot
}
function ConvertTo-LegacyJournal($Journal){
    $steps=@($Journal.steps|ForEach-Object{
        [ordered]@{id=[string]$_.id;relative_path=[string]$_.relative_path;action=[string]$_.action;before_digest=$_.before_digest;after_digest=$_.after_digest;content_base64=$_.content_base64}
    })
    return [ordered]@{
        transaction_id=[string]$Journal.transaction_id;operation=[string]$Journal.operation;task_id=[string]$Journal.task_id;expected_version=$Journal.expected_version
        status=[string]$Journal.status;completed_steps=@($Journal.completed_steps);failed_step=[string]$Journal.failed_step;error=[string]$Journal.error
        replay_command=[string]$Journal.replay_command;created_at=[string]$Journal.created_at;steps=$steps
    }
}
function Write-TestJson($Path,$Value){[IO.File]::WriteAllText($Path,(($Value|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false))}
function New-LegacyCreateFixture($Workspace,$TaskId,[ValidateSet('prepared','lag','prefix')]$Progress){
    $contract=Write-Contract $Workspace $TaskId 'contract.json'
    $result=if($Progress-ceq'prepared'){
        Invoke-Cli $Workspace @('create','-TaskId',$TaskId,'-Contract',$contract,'-AsJson') 'v2' '' '' '' '1'
    }else{
        Invoke-Cli $Workspace @('create','-TaskId',$TaskId,'-Contract',$contract,'-AsJson') 'v2' '1'
    }
    $match=[regex]::Match($result.StdErr,'TransactionId=(txn_[0-9a-f]{32})')
    if($result.ExitCode-ne2-or-not$match.Success){throw "unable to prepare legacy transaction fixture: $($result.StdErr)"}
    $id=$match.Groups[1].Value;$path=Join-Path $Workspace ".assistant/runtime/failed-writes/$id.json"
    $current=Get-Content -LiteralPath $path -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String
    Get-ChildItem -LiteralPath (Join-Path $Workspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue|Remove-Item -Force
    $legacy=ConvertTo-LegacyJournal $current
    $quotedLegacyWorkspace="'"+($Workspace-replace"'","''")+"'";$legacy.replay_command="pwsh -File scripts/task.ps1 replay -TransactionId $id -WorkspaceRoot $quotedLegacyWorkspace"
    if($Progress-ceq'prepared'){$legacy.status='prepared';$legacy.completed_steps=@();$legacy.failed_step=[string]$legacy.steps[0].id;$legacy.error=''}
    elseif($Progress-ceq'lag'){$legacy.status='failed';$legacy.completed_steps=@();$legacy.failed_step=[string]$legacy.steps[0].id;$legacy.error='legacy publication progress lag'}
    else{$legacy.status='failed';$legacy.failed_step=[string]$legacy.steps[@($legacy.completed_steps).Count].id;$legacy.error='legacy completed-prefix fault'}
    Write-TestJson $path $legacy
    return [pscustomobject]@{TransactionId=$id;Path=$path;Journal=$legacy;Contract=$contract;InitialResult=$result}
}
$pathModule=@(Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Path.psm1') -Force -PassThru)[-1]
$pathSource=Get-Content -LiteralPath (Join-Path $RepoRoot 'scripts/lib/Harness.Path.psm1') -Raw -Encoding utf8
$runningOnWindows=[System.Environment]::OSVersion.Platform-eq[System.PlatformID]::Win32NT
if($runningOnWindows){
    Check ($pathSource-match'physical identity is supported only on Windows'-and$pathSource-notmatch"return 'path:'") 'non-Windows physical identity fails closed instead of using a lexical lock' 'non-Windows physical identity still uses a lexical fallback'
    try{
        $identityBefore=& $taskStateModule {param($Root)Reset-TaskStateWorkspaceIdentityCache;Get-TaskStateWorkspaceIdentity -WorkspaceRoot $Root} $identityRaceWorkspace
        [IO.Directory]::Delete($identityRaceWorkspace,$true);[void][IO.Directory]::CreateDirectory($identityRaceWorkspace)
        $identityDriftRejected=$false;try{& $taskStateModule {param($Root)Assert-TaskStateWorkspaceIdentityCurrent -WorkspaceRoot $Root} $identityRaceWorkspace}catch{$identityDriftRejected=$_.Exception.Message-match'physical identity changed'}
        $identityAfter=& $taskStateModule {param($Root)Reset-TaskStateWorkspaceIdentityCache;Get-TaskStateWorkspaceIdentity -WorkspaceRoot $Root} $identityRaceWorkspace
        Check $identityDriftRejected 'operation identity recheck rejects a recreated workspace' 'operation identity recheck accepted a recreated workspace'
        Check ($identityAfter-cne$identityBefore) 'operation identity cache reset observes a recreated workspace' 'operation identity cache persisted across operation reset'
    }catch{Check $false 'operation identity recheck rejects a recreated workspace' ('operation identity recheck fixture failed: '+$_.Exception.Message);Check $false 'operation identity cache reset observes a recreated workspace' ('operation identity cache fixture failed: '+$_.Exception.Message)}
    $identityWriteContract=Write-Contract $identityWriteWorkspace 'identity-write-task' 'contract.json';$identityWriteSnap=Snapshot $identityWriteWorkspace;$identityWriteResult=Invoke-Cli $identityWriteWorkspace @('create','-TaskId','identity-write-task','-Contract',$identityWriteContract,'-AsJson') 'v2' '' '' '' '' '1'
    Check ($identityWriteResult.ExitCode-eq2-and$identityWriteResult.StdErr-match'injected task-state identity recheck failure') 'mutation runs a fresh identity recheck immediately before first persistence' 'mutation did not execute the pre-persistence identity recheck';Same $identityWriteSnap (Snapshot $identityWriteWorkspace) 'pre-persistence identity rejection is zero-write' 'pre-persistence identity rejection wrote state'
    $root=[IO.Path]::GetPathRoot($workspace)
    try{$resolvedRoot=& $pathModule {param($Path)Resolve-HarnessWorkspaceRoot -WorkspaceRoot $Path} $root;Check ($resolvedRoot-ceq$root) 'drive-root WorkspaceRoot preserves its root separator' 'drive-root WorkspaceRoot degraded to a drive-relative path'}catch{Check $false 'drive-root WorkspaceRoot preserves its root separator' ('drive-root WorkspaceRoot failed: '+$_.Exception.Message)}
    try{$driveChild=& $pathModule {param($Root,$Path)Resolve-HarnessContainedPath -WorkspaceRoot $Root -Path $Path -Label 'drive-root child' -MustExist Directory} $root $workspace;Check ($driveChild-ceq$workspace) 'drive-root containment accepts an existing child' 'drive-root containment rejected its child'}catch{Check $false 'drive-root containment accepts an existing child' ('drive-root containment failed: '+$_.Exception.Message)}
    $volumeOutput=@(& mountvol.exe $root /L 2>&1|ForEach-Object{[string]$_});$volumeExit=$LASTEXITCODE;$volumeMatch=[regex]::Match(($volumeOutput-join"`n"),'(?i)\\\\\?\\Volume\{[0-9a-f-]{36}\}\\')
    if($volumeExit -ne 0 -or -not $volumeMatch.Success){$script:unavailable.Add('physical volume alias fixture unavailable: mountvol did not return a volume GUID')}else{
        try{
            $resolvedVolumeRoot=& $pathModule {param($Path)Resolve-HarnessWorkspaceRoot -WorkspaceRoot $Path} $volumeMatch.Value;Check ($resolvedVolumeRoot.Equals($volumeMatch.Value,[StringComparison]::OrdinalIgnoreCase)) 'volume-GUID WorkspaceRoot preserves its root separator' 'volume-GUID WorkspaceRoot became invalid'
            $volumeAlias=$volumeMatch.Value+$workspace.Substring($root.Length);if(-not(Test-Path -LiteralPath $volumeAlias -PathType Container)){throw 'volume alias path does not exist'}
            $volumeChild=& $pathModule {param($Root,$Path)Resolve-HarnessContainedPath -WorkspaceRoot $Root -Path $Path -Label 'volume-root child' -MustExist Directory} $volumeMatch.Value $volumeAlias;Check ($volumeChild.Equals($volumeAlias,[StringComparison]::OrdinalIgnoreCase)) 'volume-GUID root containment accepts an existing child' 'volume-GUID root containment rejected its child'
            $volumeDot=& $pathModule {param($Root)Resolve-HarnessContainedPath -WorkspaceRoot $Root -Path '.' -Label 'volume-root dot' -MustExist Directory} $volumeAlias;Check ($volumeDot.Equals($volumeAlias,[StringComparison]::OrdinalIgnoreCase)) 'volume-GUID relative dot resolves to the existing workspace root' 'volume-GUID relative dot retained an invalid trailing segment'
            $mutexA=& $taskStateModule {param($Root)Get-TaskStateMutexName -WorkspaceRoot $Root -Suffix 'task.alias-probe'} $workspace;$mutexB=& $taskStateModule {param($Root)Get-TaskStateMutexName -WorkspaceRoot $Root -Suffix 'task.alias-probe'} $volumeAlias
            Check ($mutexA-ceq$mutexB) 'physical volume alias resolves to the same task-state mutex' 'physical volume alias produced a split task-state mutex'
            $volumeAliasReplay=$volumeMatch.Value+$aliasReplayWorkspace.Substring($root.Length);if(-not(Test-Path -LiteralPath $volumeAliasReplay -PathType Container)){throw 'volume replay alias path does not exist'}
            $aliasContract=Write-Contract $aliasReplayWorkspace 'volume-alias-task' 'contract.json';$aliasCrash=Invoke-Cli $aliasReplayWorkspace @('create','-TaskId','volume-alias-task','-Contract',$aliasContract,'-AsJson') 'v2' '1';$aliasMatch=[regex]::Match($aliasCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$aliasTransaction=$(if($aliasMatch.Success){$aliasMatch.Groups[1].Value}else{''});$aliasReplay=$(if($aliasTransaction){Invoke-Cli $volumeAliasReplay @('replay','-TransactionId',$aliasTransaction,'-AsJson')}else{$aliasCrash})
            Check ($aliasCrash.ExitCode-eq2-and$aliasMatch.Success-and$aliasReplay.ExitCode-eq0-and(Read-Output $aliasReplay).result-ceq'recovered'-and(Test-Path (Join-Path $aliasReplayWorkspace ".assistant/runtime/failed-writes/archive/$aliasTransaction.json"))) 'transaction replay accepts a different lexical alias of the same physical workspace' 'physical volume alias could not replay the original workspace transaction'
            $legacyVolumeFixture=New-LegacyCreateFixture $legacyAliasWorkspace 'legacy-volume-task' 'prepared';$legacyVolumeAlias=$volumeMatch.Value+$legacyAliasWorkspace.Substring($root.Length);$legacyVolumeReplay=Invoke-Cli $legacyVolumeAlias @('replay','-TransactionId',$legacyVolumeFixture.TransactionId,'-AsJson');$legacyVolumeArchive=Join-Path $legacyAliasWorkspace ".assistant/runtime/failed-writes/archive/$($legacyVolumeFixture.TransactionId).json"
            Check ($legacyVolumeReplay.ExitCode-eq0-and(Read-Output $legacyVolumeReplay).result-ceq'recovered'-and(Test-Path -LiteralPath $legacyVolumeArchive -PathType Leaf)) 'legacy transaction replay uses the same physical mutex through a volume alias' 'legacy transaction replay failed through a volume alias'
        }catch{Check $false 'physical volume alias resolves to the same task-state mutex' ('physical volume alias SUT failed: '+$_.Exception.Message);Check $false 'transaction replay accepts a different lexical alias of the same physical workspace' ('physical volume replay failed: '+$_.Exception.Message)}
    }
    Check ($pathSource-match'\$volumeOutput = @\(& mountvol\.exe \$root /L'-and$pathSource-notmatch'\$candidate = \[System\.IO\.Path\]::GetFullPath\(\$physical\)') 'physical identity queries the validated volume root once' 'physical identity still scans workspace ancestors for a volume'
    Check ($pathSource-match'function Resolve-HarnessSubstPath'-and$pathSource-match'\$physical = Resolve-HarnessSubstPath -Path \$resolved') 'SUBST resolution remains statically bound into physical mutex identity' 'physical mutex identity no longer invokes SUBST resolution'
    $script:unavailable.Add('dynamic SUBST alias fixture is environment-blocked by enterprise endpoint security and was not executed')
}else{
    $nonWindowsSnap=Snapshot $workspace;$nonWindowsRejected=$false
    try{[void](& $pathModule {param($Path)Get-HarnessPhysicalPathIdentity -Path $Path} $workspace)}catch{$nonWindowsRejected=$_.Exception.Message-match'physical identity is supported only on Windows'}
    Check $nonWindowsRejected 'non-Windows physical identity fails closed instead of using a lexical lock' 'non-Windows physical identity did not fail closed'
    Same $nonWindowsSnap (Snapshot $workspace) 'non-Windows physical identity rejection is zero-write' 'non-Windows physical identity rejection wrote state'
}
$legacyPrepared=New-LegacyCreateFixture $legacyPreparedWorkspace 'legacy-prepared-task' 'prepared'
$legacyPreparedReplay=Invoke-Cli $legacyPreparedWorkspace @('replay','-TransactionId',$legacyPrepared.TransactionId,'-AsJson')
$legacyPreparedArchivePath=Join-Path $legacyPreparedWorkspace ".assistant/runtime/failed-writes/archive/$($legacyPrepared.TransactionId).json"
$legacyPreparedArchive=$(if(Test-Path -LiteralPath $legacyPreparedArchivePath -PathType Leaf){Get-Content -LiteralPath $legacyPreparedArchivePath -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String}else{$null})
$legacyPreparedAgain=Invoke-Cli $legacyPreparedWorkspace @('replay','-TransactionId',$legacyPrepared.TransactionId,'-AsJson')
$legacyPreparedClaims=@(Get-ChildItem -LiteralPath (Join-Path $legacyPreparedWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
$legacyPreparedTopKeys=@('transaction_id','operation','task_id','expected_version','status','completed_steps','failed_step','error','replay_command','created_at','steps')
$legacyPreparedStepKeys=@('id','relative_path','action','before_digest','after_digest','content_base64')
$legacyArchiveExact=$null-ne$legacyPreparedArchive-and@(Compare-Object $legacyPreparedTopKeys @($legacyPreparedArchive.Keys)).Count-eq0-and@($legacyPreparedArchive.steps|Where-Object{@(Compare-Object $legacyPreparedStepKeys @($_.Keys)).Count-ne0}).Count-eq0
Check ($legacyPreparedReplay.ExitCode-eq0-and(Read-Output $legacyPreparedReplay).result-ceq'recovered'-and$legacyPreparedAgain.ExitCode-eq0-and(Read-Output $legacyPreparedAgain).result-ceq'already-recovered'-and$legacyArchiveExact-and$legacyPreparedClaims.Count-eq0-and-not(Test-Path -LiteralPath $legacyPrepared.Path)) 'exact legacy prepared journal replays, archives without format drift, and is idempotent' 'legacy prepared journal recovery, archive shape, or idempotence failed'

$legacyLag=New-LegacyCreateFixture $legacyLagWorkspace 'legacy-lag-task' 'lag'
$legacyLagReplay=Invoke-Cli $legacyLagWorkspace @('replay','-TransactionId',$legacyLag.TransactionId,'-AsJson')
Check ($legacyLagReplay.ExitCode-eq0-and(Read-Output $legacyLagReplay).result-ceq'recovered'-and(Test-Path -LiteralPath (Join-Path $legacyLagWorkspace '.assistant/runtime/tasks/legacy-lag-task/task.json') -PathType Leaf)) 'legacy progress-lag journal adopts its first unclaimed postimage and completes' 'legacy progress-lag journal could not recover its published first step'

$legacyPrefix=New-LegacyCreateFixture $legacyPrefixWorkspace 'legacy-prefix-task' 'prefix'
$legacyPrefixReplay=Invoke-Cli $legacyPrefixWorkspace @('replay','-TransactionId',$legacyPrefix.TransactionId,'-AsJson')
Check ($legacyPrefixReplay.ExitCode-eq0-and(Read-Output $legacyPrefixReplay).result-ceq'recovered'-and(Test-Path -LiteralPath (Join-Path $legacyPrefixWorkspace '.assistant/runtime/tasks/legacy-prefix-task/events.jsonl') -PathType Leaf)) 'legacy completed-prefix journal resumes its unfinished suffix' 'legacy completed-prefix journal did not recover'

$legacyTransitionContract=Write-Contract $legacyTransitionWorkspace 'legacy-transition-task' 'contract.json'
$legacyTransitionCreate=Invoke-Cli $legacyTransitionWorkspace @('create','-TaskId','legacy-transition-task','-Contract',$legacyTransitionContract,'-AsJson')
$legacyTransitionCrash=Invoke-Cli $legacyTransitionWorkspace @('transition','-TaskId','legacy-transition-task','-ExpectedVersion','1','-To','running','-AsJson') 'v2' '1'
$legacyTransitionMatch=[regex]::Match($legacyTransitionCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})')
$legacyTransitionId=$(if($legacyTransitionMatch.Success){$legacyTransitionMatch.Groups[1].Value}else{''})
$legacyTransitionPath=Join-Path $legacyTransitionWorkspace ".assistant/runtime/failed-writes/$legacyTransitionId.json"
if($legacyTransitionCreate.ExitCode-eq0-and$legacyTransitionCrash.ExitCode-eq2-and$legacyTransitionMatch.Success){
    $legacyTransitionCurrent=Get-Content -LiteralPath $legacyTransitionPath -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String
    Get-ChildItem -LiteralPath (Join-Path $legacyTransitionWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue|Remove-Item -Force
    $legacyTransitionJournal=ConvertTo-LegacyJournal $legacyTransitionCurrent
    $legacyTransitionJournal.status='failed';$legacyTransitionJournal.failed_step=[string]$legacyTransitionJournal.steps[@($legacyTransitionJournal.completed_steps).Count].id;$legacyTransitionJournal.error='legacy transition completed-prefix fault'
    Write-TestJson $legacyTransitionPath $legacyTransitionJournal
    $legacyTransitionReplay=Invoke-Cli $legacyTransitionWorkspace @('replay','-TransactionId',$legacyTransitionId,'-AsJson')
    $legacyTransitionTask=Get-Content -LiteralPath (Join-Path $legacyTransitionWorkspace '.assistant/runtime/tasks/legacy-transition-task/task.json') -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String
    Check ($legacyTransitionReplay.ExitCode-eq0-and(Read-Output $legacyTransitionReplay).result-ceq'recovered'-and[string]$legacyTransitionTask.status-ceq'running'-and[int64]$legacyTransitionTask.version-eq2) 'legacy transition journal resumes a partially published state change' 'legacy transition journal did not recover its versioned state change'
}else{
    Check $false 'legacy transition journal resumes a partially published state change' 'legacy transition fixture could not be prepared'
}

$legacyHybrid=New-LegacyCreateFixture $legacyHybridWorkspace 'legacy-hybrid-task' 'prepared'
$legacyHybridDocument=Get-Content -LiteralPath $legacyHybrid.Path -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String
$legacyHybridDocument.steps[0]['before_content_base64']=$null
Write-TestJson $legacyHybrid.Path $legacyHybridDocument
$legacyHybridSnap=Snapshot $legacyHybridWorkspace
$legacyHybridReplay=Invoke-Cli $legacyHybridWorkspace @('replay','-TransactionId',$legacyHybrid.TransactionId,'-AsJson')
Check ($legacyHybridReplay.ExitCode-eq2-and$legacyHybridReplay.StdErr-match'unknown or hybrid') 'mixed legacy/current journal shape fails closed' 'hybrid journal shape was accepted'
Same $legacyHybridSnap (Snapshot $legacyHybridWorkspace) 'hybrid journal rejection is zero-write' 'hybrid journal rejection wrote state'

$legacyOverlap=New-LegacyCreateFixture $legacyOverlapWorkspace 'legacy-overlap-old' 'prepared'
$legacyOverlapNewContract=Write-Contract $legacyOverlapWorkspace 'legacy-overlap-new' 'new-contract.json'
$legacyOverlapNew=Invoke-Cli $legacyOverlapWorkspace @('create','-TaskId','legacy-overlap-new','-Contract',$legacyOverlapNewContract,'-AsJson')
$legacyOverlapReplay=Invoke-Cli $legacyOverlapWorkspace @('replay','-TransactionId',$legacyOverlap.TransactionId,'-AsJson')
Check ($legacyOverlapNew.ExitCode-eq0-and$legacyOverlapReplay.ExitCode-eq0-and(Read-Output $legacyOverlapReplay).result-ceq'recovered') 'new writer classifies a non-overlapping legacy pending journal without blocking' 'legacy pending journal broke global overlap scanning or later recovery'

$casTarget=Join-Path $casWorkspace 'target.txt';[IO.File]::WriteAllText($casTarget,"before`n",[Text.UTF8Encoding]::new($false));$before=Digest "before`n"
$casSteps=@(
    [ordered]@{id='cas-a';relative_path='target.txt';action='write';before_digest=$before;after_digest=(Digest "alpha`n");content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes("alpha`n"))},
    [ordered]@{id='cas-b';relative_path='target.txt';action='write';before_digest=$before;after_digest=(Digest "beta`n");content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes("beta`n"))}
)
$casHandles=[Collections.Generic.List[object]]::new();$casFixture=Join-Path $RepoRoot 'tests/fixtures/v2-task-state-atomic-step.ps1'
foreach($index in 0..1){$stepPath=Join-Path $casWorkspace "step-$index.json";[IO.File]::WriteAllText($stepPath,(($casSteps[$index]|ConvertTo-Json -Depth 10)+"`n"),[Text.UTF8Encoding]::new($false));$casHandles.Add((Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$casWorkspace,'-StepPath',$stepPath,'-TransactionId',('txn_'+([string]($index+1)*32)))))}
$casResults=@($casHandles|ForEach-Object{Complete-Cli $_});$casWinner=@($casResults|Where-Object ExitCode -eq 0);$casLoser=@($casResults|Where-Object ExitCode -eq 2);$casText=[IO.File]::ReadAllText($casTarget,[Text.UTF8Encoding]::new($false,$true))
Check ($casWinner.Count -eq 1 -and $casLoser.Count -eq 1 -and $casText -cin @("alpha`n","beta`n")) 'durable step claim permits one competing postimage' 'durable step claim allowed two competing postimages or lost the winner'
$claimTarget=Join-Path $claimWorkspace 'target.txt';[IO.File]::WriteAllText($claimTarget,"before`n",[Text.UTF8Encoding]::new($false));$claimStep=[ordered]@{id='claim-crash';relative_path='target.txt';action='write';before_digest=$before;after_digest=(Digest "gamma`n");content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes("gamma`n"))};$claimStepPath=Join-Path $claimWorkspace 'step.json';[IO.File]::WriteAllText($claimStepPath,(($claimStep|ConvertTo-Json -Depth 10)+"`n"),[Text.UTF8Encoding]::new($false));$claimTransaction='txn_'+('a'*32)
$claimCrash=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$claimStepPath,'-TransactionId',$claimTransaction,'-FailAfterPublish'));$claimFiles=@(Get-ChildItem -LiteralPath (Join-Path $claimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
Check ($claimCrash.ExitCode -eq 2 -and[IO.File]::ReadAllText($claimTarget)-ceq"gamma`n"-and$claimFiles.Count-eq1) 'publication fault retains the owning durable claim' 'publication fault lost the postimage or its durable claim'
$claimOwnerWithoutReplay=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$claimStepPath,'-TransactionId',$claimTransaction));Check ($claimOwnerWithoutReplay.ExitCode-eq2) 'ordinary execution cannot reuse its own pending publication claim' 'ordinary execution reused a pending claim without replay authorization'
$claimBlocked=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$claimStepPath,'-TransactionId',('txn_'+('b'*32))));Check ($claimBlocked.ExitCode-eq2) 'another transaction cannot adopt a published step claim' 'another transaction adopted a published step claim'
$claimPath=$claimFiles[0].FullName;$claimBytes=[IO.File]::ReadAllBytes($claimPath);[IO.File]::WriteAllText($claimPath,"{}`n",[Text.UTF8Encoding]::new($false));$claimSnap=Snapshot $claimWorkspace;$claimMalformed=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$claimStepPath,'-TransactionId',$claimTransaction,'-Replay'));Check ($claimMalformed.ExitCode-eq2) 'malformed publication claim fails closed' 'malformed publication claim was accepted';Same $claimSnap (Snapshot $claimWorkspace) 'malformed publication claim rejection is zero-write' 'malformed publication claim rejection wrote state';[IO.File]::WriteAllBytes($claimPath,$claimBytes)
$claimDocument=Get-Content -LiteralPath $claimPath -Raw -Encoding utf8|ConvertFrom-Json -AsHashtable -DateKind String;$claimDocument.task_id='other-task';[IO.File]::WriteAllText($claimPath,(($claimDocument|ConvertTo-Json -Depth 20)+"`n"),[Text.UTF8Encoding]::new($false));$claimSnap=Snapshot $claimWorkspace;$claimIntentMismatch=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$claimStepPath,'-TransactionId',$claimTransaction,'-Replay'));Check ($claimIntentMismatch.ExitCode-eq2-and$claimIntentMismatch.StdErr-match'held by another transaction') 'publication claim binds task and immutable transaction intent' 'publication claim accepted a different task intent';Same $claimSnap (Snapshot $claimWorkspace) 'claim intent rejection is zero-write' 'claim intent rejection wrote state';[IO.File]::WriteAllBytes($claimPath,$claimBytes)
$claimReplay=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$claimStepPath,'-TransactionId',$claimTransaction,'-Replay'));$claimFiles=@(Get-ChildItem -LiteralPath (Join-Path $claimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
Check ($claimReplay.ExitCode-eq0-and$claimFiles.Count-eq0-and[IO.File]::ReadAllText($claimTarget)-ceq"gamma`n") 'owning transaction replays a published step and clears its claim' 'publication claim recovery did not preserve the postimage and clear the claim'
$missingStep=[ordered]@{id='claim-missing';relative_path='missing.txt';action='write';before_digest=$null;after_digest=(Digest "created`n");content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes("created`n"))};$missingStepPath=Join-Path $claimWorkspace 'missing-step.json';[IO.File]::WriteAllText($missingStepPath,(($missingStep|ConvertTo-Json -Depth 10)+"`n"),[Text.UTF8Encoding]::new($false));$missingResult=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$missingStepPath,'-TransactionId',('txn_'+('c'*32))));Check ($missingResult.ExitCode-eq0-and[IO.File]::ReadAllText((Join-Path $claimWorkspace 'missing.txt'))-ceq"created`n") 'missing-preimage publication is claimed and created atomically' 'missing-preimage publication failed'
$deleteTarget=Join-Path $claimWorkspace 'delete.txt';[IO.File]::WriteAllText($deleteTarget,"delete-me`n",[Text.UTF8Encoding]::new($false));$deleteStep=[ordered]@{id='claim-delete';relative_path='delete.txt';action='delete';before_digest=(Digest "delete-me`n");after_digest=$null;content_base64=$null};$deleteStepPath=Join-Path $claimWorkspace 'delete-step.json';[IO.File]::WriteAllText($deleteStepPath,(($deleteStep|ConvertTo-Json -Depth 10)+"`n"),[Text.UTF8Encoding]::new($false));$deleteTransaction='txn_'+('d'*32);$deleteCrash=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$deleteStepPath,'-TransactionId',$deleteTransaction,'-FailAfterPublish'));$deleteClaims=@(Get-ChildItem -LiteralPath (Join-Path $claimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);Check ($deleteCrash.ExitCode-eq2-and-not(Test-Path $deleteTarget)-and$deleteClaims.Count-eq1) 'delete publication fault retains its owning claim' 'delete publication fault lost its claim or restored the target'
$deleteReplay=Complete-Cli (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $casFixture -Arguments @('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$claimWorkspace,'-StepPath',$deleteStepPath,'-TransactionId',$deleteTransaction,'-Replay'));$deleteClaims=@(Get-ChildItem -LiteralPath (Join-Path $claimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);Check ($deleteReplay.ExitCode-eq0-and-not(Test-Path $deleteTarget)-and$deleteClaims.Count-eq0) 'owning transaction replays a delete and clears its claim' 'delete claim recovery failed'
$journalClaimContract=Write-Contract $journalClaimWorkspace 'journal-claim-task' 'contract.json';$journalClaimCrash=Invoke-Cli $journalClaimWorkspace @('create','-TaskId','journal-claim-task','-Contract',$journalClaimContract,'-AsJson') 'v2' '' '1';$journalClaimMatch=[regex]::Match($journalClaimCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$journalClaimId=$(if($journalClaimMatch.Success){$journalClaimMatch.Groups[1].Value}else{''});$journalClaimPath=Join-Path $journalClaimWorkspace ".assistant/runtime/failed-writes/$journalClaimId.json";$journalClaimTaskPath=Join-Path $journalClaimWorkspace '.assistant/runtime/tasks/journal-claim-task/task.json';$journalClaimFiles=@(Get-ChildItem -LiteralPath (Join-Path $journalClaimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
Check ($journalClaimCrash.ExitCode-eq2-and$journalClaimMatch.Success-and(Test-Path $journalClaimPath)-and(Test-Path $journalClaimTaskPath)-and$journalClaimFiles.Count-eq1) 'journal-completed publication fault retains its claim and pending journal' 'journal-completed publication fault lost the claim, journal, or postimage'
$journalClaimBytes=[IO.File]::ReadAllBytes($journalClaimTaskPath);[IO.File]::WriteAllText($journalClaimTaskPath,"tampered`n",[Text.UTF8Encoding]::new($false));$journalClaimSnap=Snapshot $journalClaimWorkspace;$journalClaimTampered=Invoke-Cli $journalClaimWorkspace @('replay','-TransactionId',$journalClaimId,'-AsJson');Check ($journalClaimTampered.ExitCode-eq2-and$journalClaimTampered.StdErr-match'postcondition changed') 'completed replay rejects a changed postimage' 'completed replay accepted a changed postimage';Same $journalClaimSnap (Snapshot $journalClaimWorkspace) 'changed completed postimage rejection is zero-write' 'changed completed postimage rejection wrote state';[IO.File]::WriteAllBytes($journalClaimTaskPath,$journalClaimBytes)
$journalClaimContractPath=Join-Path $journalClaimWorkspace $journalClaimContract;$journalClaimContractBytes=[IO.File]::ReadAllBytes($journalClaimContractPath);[void](Write-Contract $journalClaimWorkspace 'journal-claim-task' $journalClaimContract 'two');$journalClaimInputSnap=Snapshot $journalClaimWorkspace;$journalClaimInputReplay=Invoke-Cli $journalClaimWorkspace @('replay','-TransactionId',$journalClaimId,'-AsJson');Check ($journalClaimInputReplay.ExitCode-eq2-and$journalClaimInputReplay.StdErr-match'Requirement Contract is stale') 'own claims do not bypass replay input revalidation' 'own claim bypassed stale Contract revalidation';Same $journalClaimInputSnap (Snapshot $journalClaimWorkspace) 'own-claim input rejection is zero-write' 'own-claim input rejection wrote state';[IO.File]::WriteAllBytes($journalClaimContractPath,$journalClaimContractBytes)
$journalClaimReplay=Invoke-Cli $journalClaimWorkspace @('replay','-TransactionId',$journalClaimId,'-AsJson');$journalClaimFiles=@(Get-ChildItem -LiteralPath (Join-Path $journalClaimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);Check ($journalClaimReplay.ExitCode-eq0-and(Read-Output $journalClaimReplay).result-ceq'recovered'-and$journalClaimFiles.Count-eq0) 'journal-completed replay verifies the postimage before clearing its claim' 'journal-completed replay did not verify and clear its claim'
$claimBlockOld=Write-Contract $claimBlockWorkspace 'claim-block-old' 'old.json';$claimBlockNew=Write-Contract $claimBlockWorkspace 'claim-block-new' 'new.json';$claimBlockCreate=Invoke-Cli $claimBlockWorkspace @('create','-TaskId','claim-block-old','-Contract',$claimBlockOld,'-ActivateCurrent','-AsJson');$claimBlockCrash=Invoke-Cli $claimBlockWorkspace @('transition','-TaskId','claim-block-old','-ExpectedVersion','1','-To','cancelled','-AsJson') 'v2' '' '3';$claimBlockMatch=[regex]::Match($claimBlockCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$claimBlockId=$(if($claimBlockMatch.Success){$claimBlockMatch.Groups[1].Value}else{''});$claimBlockClaims=@(Get-ChildItem -LiteralPath (Join-Path $claimBlockWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
Check ($claimBlockCreate.ExitCode-eq0-and$claimBlockCrash.ExitCode-eq2-and$claimBlockMatch.Success-and$claimBlockClaims.Count-eq3-and-not(Test-Path (Join-Path $claimBlockWorkspace '.assistant/runtime/current.json'))) 'cross-task current-pointer crash retains every transaction claim through recovery' 'cross-task claim fixture did not retain the complete transaction claim set'
$claimBlockSnap=Snapshot $claimBlockWorkspace;$claimBlockAttempt=Invoke-Cli $claimBlockWorkspace @('create','-TaskId','claim-block-new','-Contract',$claimBlockNew,'-ActivateCurrent','-AsJson');Check ($claimBlockAttempt.ExitCode-eq2-and$claimBlockAttempt.StdErr-match'reserved by pending transaction|pending publication claim') 'new transaction preflights every pending target before publication' 'new transaction ignored a retained transaction target';Same $claimBlockSnap (Snapshot $claimBlockWorkspace) 'target-claim preflight rejection is zero-write' 'target-claim preflight rejection published partial state'
$claimBlockReplay=Invoke-Cli $claimBlockWorkspace @('replay','-TransactionId',$claimBlockId,'-AsJson');$claimBlockCreateNew=Invoke-Cli $claimBlockWorkspace @('create','-TaskId','claim-block-new','-Contract',$claimBlockNew,'-ActivateCurrent','-AsJson');Check ($claimBlockReplay.ExitCode-eq0-and$claimBlockCreateNew.ExitCode-eq0-and(Read-Output $claimBlockCreateNew).task.task_id-ceq'claim-block-new') 'claim owner replay unblocks the later transaction' 'claim owner replay did not unblock the later transaction'
$pendingOld=Write-Contract $pendingBlockWorkspace 'pending-old' 'old.json';$pendingNew=Write-Contract $pendingBlockWorkspace 'pending-new' 'new.json';$pendingCrash=Invoke-Cli $pendingBlockWorkspace @('create','-TaskId','pending-old','-Contract',$pendingOld,'-ActivateCurrent','-AsJson') 'v2' '2';$pendingMatch=[regex]::Match($pendingCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$pendingId=$(if($pendingMatch.Success){$pendingMatch.Groups[1].Value}else{''});$pendingClaims=@(Get-ChildItem -LiteralPath (Join-Path $pendingBlockWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
Check ($pendingCrash.ExitCode-eq2-and$pendingMatch.Success-and$pendingClaims.Count-eq2-and-not(Test-Path (Join-Path $pendingBlockWorkspace '.assistant/runtime/current.json'))) 'early crash retains completed-prefix claims and reserves the unfinished current-pointer target' 'pending-overlap fixture lost completed claims or published current'
$pendingSnap=Snapshot $pendingBlockWorkspace;$pendingAttempt=Invoke-Cli $pendingBlockWorkspace @('create','-TaskId','pending-new','-Contract',$pendingNew,'-ActivateCurrent','-AsJson');Check ($pendingAttempt.ExitCode-eq2-and$pendingAttempt.StdErr-match'reserved by pending transaction') 'pending journal reserves every unfinished target before it has a claim' 'new transaction ignored an unfinished unclaimed target';Same $pendingSnap (Snapshot $pendingBlockWorkspace) 'pending-target rejection is zero-write' 'pending-target rejection wrote state'
$pendingReplay=Invoke-Cli $pendingBlockWorkspace @('replay','-TransactionId',$pendingId,'-AsJson');Check ($pendingReplay.ExitCode-eq0-and(Read-Output $pendingReplay).result-ceq'recovered') 'pending target owner remains replayable after overlap rejection' 'pending target owner could not replay'
$writerContract=Write-Contract $writerReplayWorkspace 'writer-race' 'contract.json';$writerHandle=Start-Cli $writerReplayWorkspace @('create','-TaskId','writer-race','-Contract',$writerContract,'-ActivateCurrent','-AsJson') 'v2' '' '' '1500';$writerPending=$null;$writerDeadline=[datetime]::UtcNow.AddSeconds(10);while($null-eq$writerPending-and[datetime]::UtcNow-lt$writerDeadline){$writerPending=Get-ChildItem -LiteralPath (Join-Path $writerReplayWorkspace '.assistant/runtime/failed-writes') -Filter 'txn_*.json' -File -ErrorAction SilentlyContinue|Select-Object -First 1;if($null-eq$writerPending){Start-Sleep -Milliseconds 25}};$writerTransaction=$(if($null-ne$writerPending){$writerPending.BaseName}else{''});$writerReplayHandle=$(if($writerTransaction){Start-Cli $writerReplayWorkspace @('replay','-TransactionId',$writerTransaction,'-AsJson')}else{$null});$writerResult=Complete-Cli $writerHandle;$writerReplayResult=$(if($null-ne$writerReplayHandle){Complete-Cli $writerReplayHandle}else{[pscustomobject]@{ExitCode=2;StdOut='';StdErr='pending journal was not observed'}});$writerReplayAgain=$(if($writerTransaction){Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$writerTransaction,'-AsJson')}else{$writerReplayResult});$writerEvents=@(Get-Content -LiteralPath (Join-Path $writerReplayWorkspace '.assistant/runtime/tasks/writer-race/events.jsonl') -ErrorAction SilentlyContinue);$writerClaims=@(Get-ChildItem -LiteralPath (Join-Path $writerReplayWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$writerArchivePath=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/archive/$writerTransaction.json";$writerArchive=$(if(Test-Path $writerArchivePath){Get-Content $writerArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String}else{$null})
$writerReplayValue=Read-Output $writerReplayResult;$writerReplayAgainValue=Read-Output $writerReplayAgain;$writerReplayName=$(if($null-ne$writerReplayValue){[string]$writerReplayValue.result}else{''});$writerReplayAgainName=$(if($null-ne$writerReplayAgainValue){[string]$writerReplayAgainValue.result}else{''});$writerPendingExists=Test-Path (Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/$writerTransaction.json");$writerArchiveStatus=$(if($null-ne$writerArchive){[string]$writerArchive.status}else{'missing'});$writerArchiveCompleted=$(if($null-ne$writerArchive){@($writerArchive.completed_steps).Count}else{-1});$writerArchiveSteps=$(if($null-ne$writerArchive){@($writerArchive.steps).Count}else{-1});$writerRaceFailure="normal writer/replay race failed: writer_exit=$($writerResult.ExitCode) writer_error=[$($writerResult.StdErr)] replay_exit=$($writerReplayResult.ExitCode) replay_result=[$writerReplayName] replay_error=[$($writerReplayResult.StdErr)] again_exit=$($writerReplayAgain.ExitCode) again_result=[$writerReplayAgainName] again_error=[$($writerReplayAgain.StdErr)] events=$($writerEvents.Count) claims=$($writerClaims.Count) pending=$writerPendingExists archive_status=$writerArchiveStatus archive_completed=$writerArchiveCompleted archive_steps=$writerArchiveSteps"
Check ($writerResult.ExitCode-eq0-and$writerReplayResult.ExitCode-eq0-and$writerReplayName-ceq'already-recovered'-and$writerReplayAgain.ExitCode-eq0-and$writerReplayAgainName-ceq'already-recovered'-and$writerEvents.Count-eq1-and$writerClaims.Count-eq0-and-not$writerPendingExists-and$null-ne$writerArchive-and$writerArchiveStatus-ceq'committed'-and$writerArchiveCompleted-eq$writerArchiveSteps) 'normal writer publishes a complete commit marker and waiting replay converges idempotently' $writerRaceFailure
$foreignCrash=Invoke-Cli $writerReplayWorkspace @('transition','-TaskId','writer-race','-ExpectedVersion','1','-To','running','-AsJson') 'v2' '1';$foreignMatch=[regex]::Match($foreignCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$foreignTransaction=$(if($foreignMatch.Success){$foreignMatch.Groups[1].Value}else{''});$foreignPending=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/$foreignTransaction.json";$foreignClaimsBefore=@(Get-ChildItem -LiteralPath (Join-Path $writerReplayWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$foreignPendingBefore=Test-Path $foreignPending;$foreignSnap=Snapshot $writerReplayWorkspace;$oldArchiveReplay=Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$writerTransaction,'-AsJson');Same $foreignSnap (Snapshot $writerReplayWorkspace) 'old archive replay preserves a later transaction and its foreign claim' 'old archive replay changed a later transaction or foreign claim';$foreignRecovery=$(if($foreignTransaction){Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$foreignTransaction,'-AsJson')}else{$foreignCrash})
Check ($foreignCrash.ExitCode-eq2-and$foreignMatch.Success-and$foreignPendingBefore-and$foreignClaimsBefore.Count-eq1-and$oldArchiveReplay.ExitCode-eq0-and(Read-Output $oldArchiveReplay).result-ceq'already-recovered'-and$foreignRecovery.ExitCode-eq0-and(Read-Output $foreignRecovery).result-ceq'recovered') 'committed archive ignores but never removes a later foreign claim' 'old archive rejected, adopted, or removed a later transaction claim'
$foreignArchivePath=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/archive/$foreignTransaction.json"
$pointerStepOmittedId='txn_'+('e'*31)+'1';$pointerStepOmittedPath=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/$pointerStepOmittedId.json";$pointerStepOmitted=Get-Content $foreignArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$pointerStepOmitted.steps=@($pointerStepOmitted.steps|Where-Object{[string]$_.id-cne'current-pointer'});Prepare-JournalFixture $pointerStepOmitted $pointerStepOmittedId $writerReplayWorkspace;[IO.File]::WriteAllText($pointerStepOmittedPath,(($pointerStepOmitted|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$pointerStepOmittedSnap=Snapshot $writerReplayWorkspace;$pointerStepOmittedReplay=Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$pointerStepOmittedId,'-AsJson');Check ($pointerStepOmittedReplay.ExitCode-eq2-and$pointerStepOmittedReplay.StdErr-match'pointer_action does not match') 'pointer_action requires the declared current-pointer step' 'journal omitted its declared current-pointer mutation';Same $pointerStepOmittedSnap (Snapshot $writerReplayWorkspace) 'declared pointer-step omission rejection is zero-write' 'declared pointer-step omission rejection wrote state';Remove-Item -LiteralPath $pointerStepOmittedPath -Force
$pointerIntentOmittedId='txn_'+('e'*31)+'2';$pointerIntentOmittedPath=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/$pointerIntentOmittedId.json";$pointerIntentOmitted=Get-Content $foreignArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$pointerIntentOmitted.steps=@($pointerIntentOmitted.steps|Where-Object{[string]$_.id-cne'current-pointer'});$pointerIntentOmitted.operation_context.pointer_action='unchanged';Prepare-JournalFixture $pointerIntentOmitted $pointerIntentOmittedId $writerReplayWorkspace;[IO.File]::WriteAllText($pointerIntentOmittedPath,(($pointerIntentOmitted|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$pointerIntentOmittedSnap=Snapshot $writerReplayWorkspace;$pointerIntentOmittedReplay=Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$pointerIntentOmittedId,'-AsJson');Check ($pointerIntentOmittedReplay.ExitCode-eq2-and$pointerIntentOmittedReplay.StdErr-match'omitted the current-pointer mutation') 'live replay rejects a self-consistent current-pointer omission' 'replay accepted a self-consistent pointer omission for the current task';Same $pointerIntentOmittedSnap (Snapshot $writerReplayWorkspace) 'live pointer-omission rejection is zero-write' 'live pointer-omission rejection wrote state';Remove-Item -LiteralPath $pointerIntentOmittedPath -Force

$pointerOmissionContract=Write-Contract $pointerOmissionWorkspace 'pointer-omission-task' 'contract.json';$pointerOmissionCurrentPath=Join-Path $pointerOmissionWorkspace '.assistant/runtime/current.json';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $pointerOmissionCurrentPath));$pointerOmissionCurrent=[ordered]@{schema_version='current-pointer/v1';task_id='pointer-omission-task';task_version=7;activated_at=[datetimeoffset]::UtcNow.ToString('o')};[IO.File]::WriteAllText($pointerOmissionCurrentPath,(($pointerOmissionCurrent|ConvertTo-Json -Depth 10)+"`n"),[Text.UTF8Encoding]::new($false));$pointerOmissionCurrentBytes=[IO.File]::ReadAllBytes($pointerOmissionCurrentPath)
$pointerOmissionCreate=Invoke-Cli $pointerOmissionWorkspace @('create','-TaskId','pointer-omission-task','-Contract',$pointerOmissionContract,'-AsJson');$pointerOmissionTaskPath=Join-Path $pointerOmissionWorkspace '.assistant/runtime/tasks/pointer-omission-task/task.json';$pointerOmissionEventsPath=Join-Path $pointerOmissionWorkspace '.assistant/runtime/tasks/pointer-omission-task/events.jsonl';$pointerOmissionPlanPath=Join-Path $pointerOmissionWorkspace 'docs/tasks/pointer-omission-task/plan.md';$pointerOmissionClaims=@(Get-ChildItem -LiteralPath (Join-Path $pointerOmissionWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue)
Check ($pointerOmissionCreate.ExitCode-eq2-and$pointerOmissionCreate.StdErr-match'omitted the current-pointer mutation') 'normal writer revalidates a live same-task pointer before its first publication claim' 'normal writer published a background task that was already named by current'
Check (([IO.File]::ReadAllBytes($pointerOmissionCurrentPath)-join',')-ceq($pointerOmissionCurrentBytes-join',')-and-not(Test-Path $pointerOmissionTaskPath)-and-not(Test-Path $pointerOmissionEventsPath)-and-not(Test-Path $pointerOmissionPlanPath)-and$pointerOmissionClaims.Count-eq0) 'same-task pointer rejection publishes no task target or claim' 'same-task pointer rejection changed current or published a task target'
$pointerActivationId='txn_'+('e'*31)+'3';$pointerActivationPath=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/$pointerActivationId.json";$pointerActivation=Get-Content $foreignArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$pointerActivationDocument=Get-JournalStepJson $pointerActivation 'current-pointer';$pointerActivationDocument.activated_at=[datetimeoffset]::UtcNow.AddDays(1).ToString('o');Set-JournalStepContent $pointerActivation 'current-pointer' (($pointerActivationDocument|ConvertTo-Json -Depth 20)+"`n");Prepare-JournalFixture $pointerActivation $pointerActivationId $writerReplayWorkspace;[IO.File]::WriteAllText($pointerActivationPath,(($pointerActivation|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$pointerActivationSnap=Snapshot $writerReplayWorkspace;$pointerActivationReplay=Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$pointerActivationId,'-AsJson');Check ($pointerActivationReplay.ExitCode-eq2-and$pointerActivationReplay.StdErr-match'activation identity changed') 'pointer update preserves the original activation identity' 'journal rewrote current-pointer activated_at';Same $pointerActivationSnap (Snapshot $writerReplayWorkspace) 'activation-identity rejection is zero-write' 'activation-identity rejection wrote state';Remove-Item -LiteralPath $pointerActivationPath -Force
$outOfOrderClaimId='txn_'+('e'*31)+'4';$outOfOrderClaimPath=Join-Path $writerReplayWorkspace ".assistant/runtime/failed-writes/$outOfOrderClaimId.json";$outOfOrderClaimJournal=Get-Content $foreignArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;Prepare-JournalFixture $outOfOrderClaimJournal $outOfOrderClaimId $writerReplayWorkspace;[IO.File]::WriteAllText($outOfOrderClaimPath,(($outOfOrderClaimJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$outOfOrderStep=@($outOfOrderClaimJournal.steps)[1];$outOfOrderClaim=& $taskStateModule {param($Root,$Id,$Task,$Intent,$Step)Enter-TransactionStepClaim -WorkspaceRoot $Root -TransactionId $Id -TaskId $Task -IntentDigest $Intent -Step $Step} $writerReplayWorkspace $outOfOrderClaimId $outOfOrderClaimJournal.task_id $outOfOrderClaimJournal.intent_digest $outOfOrderStep;$outOfOrderClaimSnap=Snapshot $writerReplayWorkspace;$outOfOrderClaimReplay=Invoke-Cli $writerReplayWorkspace @('replay','-TransactionId',$outOfOrderClaimId,'-AsJson');Check ($outOfOrderClaimReplay.ExitCode-eq2-and$outOfOrderClaimReplay.StdErr-match'out-of-order publication claim') 'replay rejects an own claim beyond the first unfinished step' 'later suffix claim forged publication authorization';Same $outOfOrderClaimSnap (Snapshot $writerReplayWorkspace) 'out-of-order claim rejection is zero-write' 'out-of-order claim rejection wrote state';& $taskStateModule {param($Root,$Id,$Task,$Intent,$Step,$Claim)Remove-TransactionStepClaim -WorkspaceRoot $Root -TransactionId $Id -TaskId $Task -IntentDigest $Intent -Step $Step -Claim $Claim} $writerReplayWorkspace $outOfOrderClaimId $outOfOrderClaimJournal.task_id $outOfOrderClaimJournal.intent_digest $outOfOrderStep $outOfOrderClaim;Remove-Item -LiteralPath $outOfOrderClaimPath -Force
$releasedOld=Write-Contract $releasedClaimWorkspace 'released-old' 'old.json';$releasedNew=Write-Contract $releasedClaimWorkspace 'released-new' 'new.json';$releasedCreate=Invoke-Cli $releasedClaimWorkspace @('create','-TaskId','released-old','-Contract',$releasedOld,'-ActivateCurrent','-AsJson');$releasedCrash=Invoke-Cli $releasedClaimWorkspace @('transition','-TaskId','released-old','-ExpectedVersion','1','-To','cancelled','-AsJson') 'v2' '3';$releasedMatch=[regex]::Match($releasedCrash.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$releasedId=$(if($releasedMatch.Success){$releasedMatch.Groups[1].Value}else{''});$releasedClaims=@(Get-ChildItem -LiteralPath (Join-Path $releasedClaimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$releasedSnap=Snapshot $releasedClaimWorkspace;$releasedBlocked=Invoke-Cli $releasedClaimWorkspace @('create','-TaskId','released-new','-Contract',$releasedNew,'-ActivateCurrent','-AsJson');Same $releasedSnap (Snapshot $releasedClaimWorkspace) 'retained transaction blocks later current-pointer mutation with zero writes' 'blocked later transaction wrote state';$releasedReplay=Invoke-Cli $releasedClaimWorkspace @('replay','-TransactionId',$releasedId,'-AsJson');$releasedClaimsAfter=@(Get-ChildItem -LiteralPath (Join-Path $releasedClaimWorkspace '.assistant/runtime/locks') -Filter 'step_*.json' -File -ErrorAction SilentlyContinue);$releasedCreateNew=Invoke-Cli $releasedClaimWorkspace @('create','-TaskId','released-new','-Contract',$releasedNew,'-ActivateCurrent','-AsJson')
Check ($releasedCreate.ExitCode-eq0-and$releasedCrash.ExitCode-eq2-and$releasedMatch.Success-and$releasedClaims.Count-eq3-and$releasedBlocked.ExitCode-eq2-and$releasedReplay.ExitCode-eq0-and(Read-Output $releasedReplay).result-ceq'recovered'-and$releasedClaimsAfter.Count-eq0-and(Test-Path (Join-Path $releasedClaimWorkspace ".assistant/runtime/failed-writes/archive/$releasedId.json"))-and$releasedCreateNew.ExitCode-eq0) 'whole-transaction claims block later writes until replay publishes an archive and releases them' 'transaction claims were released early or replay did not unblock the later write'
$releasedArchivePath=Join-Path $releasedClaimWorkspace ".assistant/runtime/failed-writes/archive/$releasedId.json"
$deltaId='txn_'+('b'*31)+'1';$deltaPath=Join-Path $releasedClaimWorkspace ".assistant/runtime/failed-writes/$deltaId.json";$deltaJournal=Get-Content $releasedArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$deltaTask=Get-JournalStepJson $deltaJournal 'task-state';$deltaTask.execution_profile='critical';foreach($flag in @('plan_required','approval_required','rollback_required','independent_review_required','verification_required')){$deltaTask.policies[$flag]=$true};Set-JournalStepContent $deltaJournal 'task-state' (($deltaTask|ConvertTo-Json -Depth 50)+"`n");Prepare-JournalFixture $deltaJournal $deltaId $releasedClaimWorkspace;[IO.File]::WriteAllText($deltaPath,(($deltaJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$deltaSnap=Snapshot $releasedClaimWorkspace;$deltaReplay=Invoke-Cli $releasedClaimWorkspace @('replay','-TransactionId',$deltaId,'-AsJson');Check ($deltaReplay.ExitCode-eq2-and$deltaReplay.StdErr-match'unauthorized task-state field') 'non-create journal rejects a self-consistent execution-profile and policy change' 'non-create journal accepted an unauthorized task-state delta';Same $deltaSnap (Snapshot $releasedClaimWorkspace) 'unauthorized task-state delta rejection is zero-write' 'unauthorized task-state delta rejection wrote state';Remove-Item -LiteralPath $deltaPath -Force
$eventPrefixId='txn_'+('b'*31)+'2';$eventPrefixPath=Join-Path $releasedClaimWorkspace ".assistant/runtime/failed-writes/$eventPrefixId.json";$eventPrefixJournal=Get-Content $releasedArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$eventPrefixStep=@($eventPrefixJournal.steps|Where-Object{[string]$_.id-ceq'event-log'})[0];$eventPrefixText=[Text.UTF8Encoding]::new($false,$true).GetString([Convert]::FromBase64String([string]$eventPrefixStep.content_base64));$eventPrefixLines=@($eventPrefixText.Substring(0,$eventPrefixText.Length-1)-split"`n");$priorEvent=$eventPrefixLines[0]|ConvertFrom-Json -AsHashtable -DateKind String;$priorEvent.actor.model='tampered-history';$eventPrefixLines[0]=$priorEvent|ConvertTo-Json -Depth 50 -Compress;Set-JournalStepContent $eventPrefixJournal 'event-log' (($eventPrefixLines-join"`n")+"`n");Prepare-JournalFixture $eventPrefixJournal $eventPrefixId $releasedClaimWorkspace;[IO.File]::WriteAllText($eventPrefixPath,(($eventPrefixJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$eventPrefixSnap=Snapshot $releasedClaimWorkspace;$eventPrefixReplay=Invoke-Cli $releasedClaimWorkspace @('replay','-TransactionId',$eventPrefixId,'-AsJson');Check ($eventPrefixReplay.ExitCode-eq2-and$eventPrefixReplay.StdErr-match'exact preimage prefix') 'journal cannot replace an earlier event while recomputing its own digests' 'journal accepted rewritten event history';Same $eventPrefixSnap (Snapshot $releasedClaimWorkspace) 'event-history replacement rejection is zero-write' 'event-history replacement rejection wrote state';Remove-Item -LiteralPath $eventPrefixPath -Force
$pointerBeforeId='txn_'+('b'*31)+'3';$pointerBeforePath=Join-Path $releasedClaimWorkspace ".assistant/runtime/failed-writes/$pointerBeforeId.json";$pointerBeforeJournal=Get-Content $releasedArchivePath -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$pointerBeforeStep=@($pointerBeforeJournal.steps|Where-Object{[string]$_.id-ceq'current-pointer'})[0];$pointerBeforeText=[Text.UTF8Encoding]::new($false,$true).GetString([Convert]::FromBase64String([string]$pointerBeforeStep.before_content_base64));$pointerBeforeDocument=$pointerBeforeText|ConvertFrom-Json -AsHashtable -DateKind String;$pointerBeforeDocument.task_id='foreign-task';$pointerBeforeTampered=($pointerBeforeDocument|ConvertTo-Json -Depth 20)+"`n";$pointerBeforeStep.before_content_base64=[Convert]::ToBase64String([Text.UTF8Encoding]::new($false).GetBytes($pointerBeforeTampered));$pointerBeforeStep.before_digest=Digest $pointerBeforeTampered;Prepare-JournalFixture $pointerBeforeJournal $pointerBeforeId $releasedClaimWorkspace;[IO.File]::WriteAllText($pointerBeforePath,(($pointerBeforeJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$pointerBeforeSnap=Snapshot $releasedClaimWorkspace;$pointerBeforeReplay=Invoke-Cli $releasedClaimWorkspace @('replay','-TransactionId',$pointerBeforeId,'-AsJson');Check ($pointerBeforeReplay.ExitCode-eq2-and$pointerBeforeReplay.StdErr-match'current-pointer preimage') 'journal current-pointer preimage is bound to the same task and version' 'journal accepted a foreign current-pointer preimage';Same $pointerBeforeSnap (Snapshot $releasedClaimWorkspace) 'foreign current-pointer preimage rejection is zero-write' 'foreign current-pointer preimage rejection wrote state';Remove-Item -LiteralPath $pointerBeforePath -Force
$architecturePath=Join-Path $RepoRoot 'docs/architecture/task-state-v2.md';$architecture=Get-Content -LiteralPath $architecturePath -Raw -Encoding utf8
Check ($architecture-match'task-state/v2'-and$architecture-match'ExpectedVersion'-and$architecture-match'current\.json'-and$architecture-match'failed-writes'-and$architecture-match'\.migration-<task-id>'-and$architecture-match'done or cancelled'-and$architecture-match'HARNESS_PROTOCOL=v1'-and$architecture-match'Non-Windows'-and$architecture-match'ordered prefix'-and$architecture-match'operation_context'-and$architecture-match'approval_input_path'-and$architecture-match'evidence_input_path'-and$architecture-match'whole-transaction'-and$architecture-match'commit marker'-and$architecture-match'claim-free replay'-and$architecture-match'own claim'-and$architecture-match'foreign claim'-and$architecture-match'exact event-log preimage prefix'-and$architecture-match'current-pointer.*preimage'-and$architecture-match'committed'-and$architecture-match'recovered'-and$architecture-notmatch'unfinished suffix'-and$architecture-notmatch'claim was already released') 'task state architecture documents state, transaction, recovery, terminal pointer, and rollback contracts' 'task state architecture artifact is missing or contradicts implementation'

$owner=Write-Contract $workspace 'owner-task' 'contracts/owner.json'
$snap=Snapshot $workspace;$r=Invoke-Cli $workspace @('create','-TaskId','owner-task','-Contract',$owner,'-AsJson') $null
Check ($r.ExitCode -eq 2 -and -not $r.StdOut -and $r.StdErr -match 'HARNESS_PROTOCOL=v2') 'writes require explicit v2' 'write ran without v2';Same $snap (Snapshot $workspace) 'protocol rejection is zero-write' 'protocol rejection wrote state'
$r=Invoke-Cli $workspace @('create','-TaskId','owner-task','-Contract',$owner,'-ActivateCurrent','-AsJson');$created=Read-Output $r
Check ($r.ExitCode -eq 0 -and $created.task.status -ceq 'ready' -and $created.pointer_action -ceq 'activated') 'active create succeeds' 'active create failed'
$taskPath=Join-Path $workspace '.assistant/runtime/tasks/owner-task/task.json';$eventsPath=Join-Path $workspace '.assistant/runtime/tasks/owner-task/events.jsonl';$currentPath=Join-Path $workspace '.assistant/runtime/current.json'
Check ((Test-Path $taskPath)-and(Test-Path $eventsPath)-and(Test-Path $currentPath)-and(Test-Path (Join-Path $workspace '.assistant/runtime/locks'))) 'runtime layout is complete' 'runtime layout is incomplete'
Check (-not(Test-Path (Join-Path $workspace '.assistant/运行时'))-and-not(Test-Path (Join-Path $workspace 'docs/tasks'))) 'v1 and artifacts stay untouched' 'v2 wrote v1 or artifacts'

$snap=Snapshot $workspace;$r=Invoke-Cli $workspace @('status','-TaskId','owner-task','-AsJson') $null;$status=Read-Output $r
Check ($r.ExitCode -eq 0 -and $status.event_count -eq 1 -and $status.is_current -eq $true -and $status.side_effects.runtime_writes -eq 0) 'status is read-only' 'status output is invalid';Same $snap (Snapshot $workspace) 'status is zero-write' 'status wrote state'
$taskBytes=[IO.File]::ReadAllBytes($taskPath);$taskIdentity=[Text.UTF8Encoding]::new($false,$true).GetString($taskBytes)|ConvertFrom-Json -AsHashtable -DateKind String;$taskIdentity.task_id='background-task';[IO.File]::WriteAllText($taskPath,(($taskIdentity|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$identitySnap=Snapshot $workspace;$identityStatus=Invoke-Cli $workspace @('status','-TaskId','owner-task','-AsJson') $null;$identityTransition=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','1','-To','running','-AsJson');Check ($identityStatus.ExitCode-eq2-and$identityStatus.StdErr-match'task_id does not match (?:TaskId|its canonical path)'-and$identityTransition.ExitCode-eq2-and$identityTransition.StdErr-match'task_id does not match (?:TaskId|its canonical path)') 'status and mutation reject task state stored under another TaskId' 'task state identity was trusted from the wrong path';Same $identitySnap (Snapshot $workspace) 'task identity rejection is zero-write' 'task identity rejection wrote state';[IO.File]::WriteAllBytes($taskPath,$taskBytes)
$snap=Snapshot $workspace;$r=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','9','-To','running','-AsJson')
Check ($r.ExitCode -eq 2 -and -not $r.StdOut -and $r.StdErr -match 'ExpectedVersion mismatch') 'CAS mismatch fails closed' 'CAS mismatch accepted';Same $snap (Snapshot $workspace) 'CAS mismatch is zero-write' 'CAS mismatch wrote state'
$snap=Snapshot $workspace;$r=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','1','-To','verifying','-AsJson')
Check ($r.ExitCode -eq 2 -and $r.StdErr -match 'illegal task transition') 'illegal transition fails closed' 'illegal transition accepted';Same $snap (Snapshot $workspace) 'illegal transition is zero-write' 'illegal transition wrote state'

$background=Write-Contract $workspace 'background-task' 'contracts/background.json';$currentBefore=[IO.File]::ReadAllText($currentPath)
$r=Invoke-Cli $workspace @('create','-TaskId','background-task','-Contract',$background,'-AsJson')
Check ($r.ExitCode -eq 0 -and (Read-Output $r).pointer_action -ceq 'unchanged' -and [IO.File]::ReadAllText($currentPath) -ceq $currentBefore) 'background create preserves current' 'background create took current'
$backgroundEvents=Join-Path $workspace '.assistant/runtime/tasks/background-task/events.jsonl';$prefix=[IO.File]::ReadAllText($backgroundEvents)
$one=Start-Cli $workspace @('transition','-TaskId','background-task','-ExpectedVersion','1','-To','running','-AsJson');$two=Start-Cli $workspace @('transition','-TaskId','background-task','-ExpectedVersion','1','-To','running','-AsJson')
$race=@((Complete-Cli $one),(Complete-Cli $two));$win=@($race|? ExitCode -eq 0);$lose=@($race|? ExitCode -eq 2)
$status=Read-Output (Invoke-Cli $workspace @('status','-TaskId','background-task','-AsJson') $null)
Check ($win.Count -eq 1 -and $lose.Count -eq 1 -and $status.task.version -eq 2 -and $status.event_count -eq 2) 'concurrent CAS has one winner' 'concurrent CAS failed';Check ([IO.File]::ReadAllText($backgroundEvents).StartsWith($prefix,[StringComparison]::Ordinal)) 'events are append-only' 'event prefix changed';Check ([IO.File]::ReadAllText($currentPath) -ceq $currentBefore) 'background transition preserves current' 'background transition changed current'

$blocked=Invoke-Cli $workspace @('transition','-TaskId','background-task','-ExpectedVersion','2','-To','blocked','-Reason','ambiguity','-AsJson')
$same=Invoke-Cli $workspace @('transition','-TaskId','background-task','-ExpectedVersion','3','-To','ready','-Contract',$background,'-AsJson')
$revised=Write-Contract $workspace 'background-task' 'contracts/background-v2.json' 'two';$resolved=Invoke-Cli $workspace @('transition','-TaskId','background-task','-ExpectedVersion','3','-To','ready','-Contract',$revised,'-AsJson')
Check ($blocked.ExitCode -eq 0 -and $same.ExitCode -eq 2 -and $same.StdErr -match 'revised Contract digest' -and $resolved.ExitCode -eq 0) 'blocked task requires revised Contract' 'blocked task accepted stale Contract'
$running=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','1','-To','running','-AsJson');$verifying=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','2','-To','verifying','-AsJson');$snap=Snapshot $workspace;$done=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','3','-To','done','-EvidenceSatisfied','-AsJson')
Check ($running.ExitCode -eq 0 -and $verifying.ExitCode -eq 0 -and $done.ExitCode -eq 2 -and $done.StdErr -match 'use verify -Evidence' -and (Test-Path $currentPath)) 'done rejects the removed EvidenceSatisfied shortcut' 'done accepted the EvidenceSatisfied shortcut';Same $snap (Snapshot $workspace) 'rejected done is zero-write' 'rejected done wrote state'
$paused=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','3','-To','paused','-AsJson');$cancelled=Invoke-Cli $workspace @('transition','-TaskId','owner-task','-ExpectedVersion','4','-To','cancelled','-AsJson');$recovery=Read-Output (Invoke-Cli $workspace @('status','-AsJson') $null)
Check ($paused.ExitCode-eq0-and$cancelled.ExitCode-eq0-and(Read-Output $cancelled).pointer_action-ceq'cleared'-and-not(Test-Path $currentPath)-and$recovery.current-eq$null-and$recovery.terminal_task_count-eq1) 'active cancellation clears current and keeps recovery usable' 'active cancellation left a terminal current pointer'

$crashContract=Write-Contract $crashWorkspace 'crash-task' 'contract.json';$r=Invoke-Cli $crashWorkspace @('create','-TaskId','crash-task','-Contract',$crashContract,'-ActivateCurrent','-AsJson') 'v2' '1'
$match=[regex]::Match($r.StdErr,'TransactionId=(txn_[0-9a-f]{32})');$transactionId=if($match.Success){$match.Groups[1].Value}else{''};$journal=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$transactionId.json"
Check ($r.ExitCode -eq 2 -and -not $r.StdOut -and $match.Success -and $r.StdErr -match '-WorkspaceRoot' -and (Test-Path $journal)) 'crash leaves workspace-bound journal' 'crash journal missing'
$replayOne=Start-Cli $crashWorkspace @('replay','-TransactionId',$transactionId,'-AsJson');$replayTwo=Start-Cli $crashWorkspace @('replay','-TransactionId',$transactionId,'-AsJson');$replays=@((Complete-Cli $replayOne),(Complete-Cli $replayTwo));$replayResults=@($replays|ForEach-Object{if($_.ExitCode-eq0){(Read-Output $_).result}else{'failed'}});$lines=@(Get-Content (Join-Path $crashWorkspace '.assistant/runtime/tasks/crash-task/events.jsonl'))
Check (@($replays|Where-Object ExitCode -ne 0).Count-eq0-and@($replayResults|Where-Object{$_-ceq'recovered'}).Count-eq1-and@($replayResults|Where-Object{$_-ceq'already-recovered'}).Count-eq1-and$lines.Count-eq1-and-not(Test-Path $journal)) 'concurrent crash replay is idempotent' 'concurrent crash replay failed'

$archive=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/archive/$transactionId.json";$archivedDocument=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$archiveClaim=& $taskStateModule {param($Root,$Id,$Task,$Intent,$Step)Enter-TransactionStepClaim -WorkspaceRoot $Root -TransactionId $Id -TaskId $Task -IntentDigest $Intent -Step $Step} $crashWorkspace $transactionId $archivedDocument.task_id $archivedDocument.intent_digest $archivedDocument.steps[0];$archiveClaimReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$transactionId,'-AsJson');Check ($archiveClaimReplay.ExitCode-eq2-and$archiveClaimReplay.StdErr-match'retains a publication claim') 'archive-only replay rejects a retained own claim' 'archive-only replay ignored a retained own claim';& $taskStateModule {param($Root,$Id,$Task,$Intent,$Step,$Claim)Remove-TransactionStepClaim -WorkspaceRoot $Root -TransactionId $Id -TaskId $Task -IntentDigest $Intent -Step $Step -Claim $Claim} $crashWorkspace $transactionId $archivedDocument.task_id $archivedDocument.intent_digest $archivedDocument.steps[0] $archiveClaim;$archiveCleanReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$transactionId,'-AsJson');Check ($archiveCleanReplay.ExitCode-eq0-and(Read-Output $archiveCleanReplay).result-ceq'already-recovered') 'already-recovered replay succeeds after exact claim cleanup' 'already-recovered replay did not recover after claim cleanup'
$unsetProtocolReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$transactionId,'-AsJson') $null;Check ($unsetProtocolReplay.ExitCode-eq0-and(Read-Output $unsetProtocolReplay).result-ceq'already-recovered') 'task CLI replay explicitly enters v2 recovery without a caller environment override' 'journal replay still requires the caller to set HARNESS_PROTOCOL'
$forgedProgressId='txn_'+('c'*31)+'1';$forgedProgressPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$forgedProgressId.json";$forgedProgress=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$forgedProgress.status='recovered';$forgedProgress.completed_steps=@($forgedProgress.steps|ForEach-Object{[string]$_.id});$forgedProgress.failed_step='';$forgedProgress.error='';Set-JournalIdentity $forgedProgress $forgedProgressId $crashWorkspace;[IO.File]::WriteAllText($forgedProgressPath,(($forgedProgress|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$forgedProgressSnap=Snapshot $crashWorkspace;$forgedProgressReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$forgedProgressId,'-AsJson');Check ($forgedProgressReplay.ExitCode-eq2-and$forgedProgressReplay.StdErr-match'lacks its own publication claim') 'completed_steps cannot forge transaction completion without own claims' 'forged completed_steps bypassed replay';Same $forgedProgressSnap (Snapshot $crashWorkspace) 'forged completion rejection is zero-write' 'forged completion rejection wrote state';Remove-Item -LiteralPath $forgedProgressPath -Force
$commandInjectionId='txn_'+('c'*31)+'2';$commandInjectionPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$commandInjectionId.json";$commandInjection=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;Prepare-JournalFixture $commandInjection $commandInjectionId $crashWorkspace;$commandInjection.replay_command="pwsh -File scripts/task.ps1 replay -TransactionId $commandInjectionId -WorkspaceRoot 'D:\safe'; Write-Output injected; ''";Refresh-JournalIntent $commandInjection;[IO.File]::WriteAllText($commandInjectionPath,(($commandInjection|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$commandInjectionSnap=Snapshot $crashWorkspace;$commandInjectionReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$commandInjectionId,'-AsJson');Check ($commandInjectionReplay.ExitCode-eq2-and$commandInjectionReplay.StdErr-match'replay command is invalid') 'replay command is restricted to one quoted WorkspaceRoot argument' 'replay command accepted injected syntax';Same $commandInjectionSnap (Snapshot $crashWorkspace) 'replay-command injection rejection is zero-write' 'replay-command injection rejection wrote state';Remove-Item -LiteralPath $commandInjectionPath -Force
$commandWorkspaceId='txn_'+('c'*31)+'5';$commandWorkspacePath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$commandWorkspaceId.json";$commandWorkspace=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;Prepare-JournalFixture $commandWorkspace $commandWorkspaceId $crashWorkspace;$quotedOutside=$outside-replace"'","''";$commandWorkspace.replay_command="pwsh -File scripts/task.ps1 replay -TransactionId $commandWorkspaceId -WorkspaceRoot '$quotedOutside'";Refresh-JournalIntent $commandWorkspace;[IO.File]::WriteAllText($commandWorkspacePath,(($commandWorkspace|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$commandWorkspaceSnap=Snapshot $crashWorkspace;$commandWorkspaceReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$commandWorkspaceId,'-AsJson');Check ($commandWorkspaceReplay.ExitCode-eq2-and$commandWorkspaceReplay.StdErr-match'replay command workspace is invalid') 'current journal binds its displayed replay command to the physical workspace' 'current journal accepted a replay command for another workspace';Same $commandWorkspaceSnap (Snapshot $crashWorkspace) 'foreign replay workspace rejection is zero-write' 'foreign replay workspace rejection wrote state';Remove-Item -LiteralPath $commandWorkspacePath -Force
$createPolicyId='txn_'+('c'*31)+'3';$createPolicyPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$createPolicyId.json";$createPolicy=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$createPolicyTask=Get-JournalStepJson $createPolicy 'task-state';$createPolicyTask.execution_profile='critical';foreach($flag in @('plan_required','approval_required','rollback_required','independent_review_required')){$createPolicyTask.policies[$flag]=$false};Set-JournalStepContent $createPolicy 'task-state' (($createPolicyTask|ConvertTo-Json -Depth 50)+"`n");Prepare-JournalFixture $createPolicy $createPolicyId $crashWorkspace;[IO.File]::WriteAllText($createPolicyPath,(($createPolicy|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$createPolicySnap=Snapshot $crashWorkspace;$createPolicyReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$createPolicyId,'-AsJson');Check ($createPolicyReplay.ExitCode-eq2-and$createPolicyReplay.StdErr-match'policies do not match') 'create journal enforces the complete profile-derived policy invariant' 'create journal accepted weakened critical policies';Same $createPolicySnap (Snapshot $crashWorkspace) 'weakened policy rejection is zero-write' 'weakened policy rejection wrote state';Remove-Item -LiteralPath $createPolicyPath -Force
$createContractId='txn_'+('c'*31)+'4';$createContractPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$createContractId.json";$createContract=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$createContractTask=Get-JournalStepJson $createContract 'task-state';$createContractTask.contract_path='missing-contract.json';$createContractTask.contract_digest='sha256:'+('0'*64);Set-JournalStepContent $createContract 'task-state' (($createContractTask|ConvertTo-Json -Depth 50)+"`n");$createContractEvent=Get-JournalStepJson $createContract 'event-log';$createContractEvent.payload.contract_digest=[string]$createContractTask.contract_digest;Set-JournalStepContent $createContract 'event-log' (($createContractEvent|ConvertTo-Json -Depth 50 -Compress)+"`n");Prepare-JournalFixture $createContract $createContractId $crashWorkspace;[IO.File]::WriteAllText($createContractPath,(($createContract|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$createContractSnap=Snapshot $crashWorkspace;$createContractReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$createContractId,'-AsJson');Check ($createContractReplay.ExitCode-eq2-and$createContractReplay.StdErr-match'Requirement Contract|does not exist') 'claim-free replay revalidates a self-consistent Requirement Contract intent' 'claim-free replay accepted a forged Contract binding';Same $createContractSnap (Snapshot $crashWorkspace) 'forged Contract rejection is zero-write' 'forged Contract rejection wrote state';Remove-Item -LiteralPath $createContractPath -Force
$nonPrefixId='txn_eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee';$nonPrefixPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$nonPrefixId.json";$nonPrefix=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$nonPrefix.status='failed';$nonPrefix.completed_steps=@('event-log');$nonPrefix.failed_step='task-state';$nonPrefix.error='tampered progress';Set-JournalIdentity $nonPrefix $nonPrefixId $crashWorkspace;[IO.File]::WriteAllText($nonPrefixPath,(($nonPrefix|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$nonPrefixReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$nonPrefixId,'-AsJson')
Check ($nonPrefixReplay.ExitCode-eq2-and$nonPrefixReplay.StdErr-match'ordered prefix') 'journal completed_steps must be an exact ordered prefix' 'journal accepted non-prefix completed_steps';Same $snap (Snapshot $crashWorkspace) 'non-prefix journal rejection is zero-write' 'non-prefix journal rejection wrote state';Remove-Item -LiteralPath $nonPrefixPath -Force
$duplicateTargetId='txn_dddddddddddddddddddddddddddddddd';$duplicateTargetPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$duplicateTargetId.json";$duplicateTarget=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$duplicateTarget.status='failed';$duplicateTarget.completed_steps=@();$duplicateTarget.failed_step=[string]$duplicateTarget.steps[0].id;$duplicateTarget.error='tampered target';$duplicateTarget.steps[1].relative_path=[string]$duplicateTarget.steps[0].relative_path;Set-JournalIdentity $duplicateTarget $duplicateTargetId $crashWorkspace;[IO.File]::WriteAllText($duplicateTargetPath,(($duplicateTarget|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$duplicateTargetReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$duplicateTargetId,'-AsJson')
Check ($duplicateTargetReplay.ExitCode-eq2-and$duplicateTargetReplay.StdErr-match'duplicate target path') 'journal rejects duplicate normalized target paths' 'journal accepted duplicate normalized target paths';Same $snap (Snapshot $crashWorkspace) 'duplicate-target journal rejection is zero-write' 'duplicate-target journal rejection wrote state';Remove-Item -LiteralPath $duplicateTargetPath -Force
$tamperId='txn_ffffffffffffffffffffffffffffffff';$tamperPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$tamperId.json"
$mismatched=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;[IO.File]::WriteAllText($tamperPath,(($mismatched|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$r=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$tamperId,'-AsJson')
Check ($r.ExitCode-eq2-and$r.StdErr-match'identity does not match') 'pending journal filename and document identity must match' 'pending journal replay trusted a different document identity';Same $snap (Snapshot $crashWorkspace) 'mismatched pending journal rejection is zero-write' 'mismatched pending journal rejection wrote state';Remove-Item -LiteralPath $tamperPath -Force
$tampered=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$tampered.steps[0].relative_path='.assistant/runtime/../escaped.json';Set-JournalIdentity $tampered $tamperId $crashWorkspace
[IO.File]::WriteAllText($tamperPath,(($tampered|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$r=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$tamperId,'-AsJson')
Check ($r.ExitCode -eq 2 -and $r.StdErr -match 'path or action is invalid') 'tampered journal fails closed' 'tampered journal replayed';Same $snap (Snapshot $crashWorkspace) 'tampered replay is zero-write' 'tampered replay wrote state'
$operationId='txn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1';$operationPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$operationId.json";$operationJournal=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$operationJournal.operation='approve';$operationJournal.expected_version=[int64]1;$operationJournal.operation_context=[ordered]@{approval_input_path='approval.json';pointer_action='updated'};Prepare-JournalFixture $operationJournal $operationId $crashWorkspace;[IO.File]::WriteAllText($operationPath,(($operationJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$operationReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$operationId,'-AsJson');Check ($operationReplay.ExitCode-eq2-and$operationReplay.StdErr-match'operation step contract|task-state preimage') 'journal operation binds an exact step sequence and required preimage' 'journal accepted steps from another operation';Same $snap (Snapshot $crashWorkspace) 'operation-contract rejection is zero-write' 'operation-contract rejection wrote state';Remove-Item -LiteralPath $operationPath -Force
$versionId='txn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa2';$versionPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$versionId.json";$versionJournal=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$versionJournal.operation='transition';$versionJournal.expected_version='1';Prepare-JournalFixture $versionJournal $versionId $crashWorkspace;[IO.File]::WriteAllText($versionPath,(($versionJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$versionReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$versionId,'-AsJson');Check ($versionReplay.ExitCode-eq2-and$versionReplay.StdErr-match'positive integer') 'journal expected_version rejects numeric strings' 'journal coerced a string expected_version';Same $snap (Snapshot $crashWorkspace) 'expected-version rejection is zero-write' 'expected-version rejection wrote state';Remove-Item -LiteralPath $versionPath -Force
$taskIntentId='txn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa3';$taskIntentPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$taskIntentId.json";$taskIntentJournal=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$taskIntentDocument=Get-JournalStepJson $taskIntentJournal 'task-state';$taskIntentDocument.task_id='other-task';Set-JournalStepContent $taskIntentJournal 'task-state' (($taskIntentDocument|ConvertTo-Json -Depth 50)+"`n");Prepare-JournalFixture $taskIntentJournal $taskIntentId $crashWorkspace;[IO.File]::WriteAllText($taskIntentPath,(($taskIntentJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$taskIntentReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$taskIntentId,'-AsJson');Check ($taskIntentReplay.ExitCode-eq2-and$taskIntentReplay.StdErr-match'task-state payload') 'journal task payload binds task_id and target version' 'journal accepted a foreign task payload';Same $snap (Snapshot $crashWorkspace) 'task-payload rejection is zero-write' 'task-payload rejection wrote state';Remove-Item -LiteralPath $taskIntentPath -Force
$eventIntentId='txn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4';$eventIntentPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$eventIntentId.json";$eventIntentJournal=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$eventIntentDocument=Get-JournalStepJson $eventIntentJournal 'event-log';$eventIntentDocument.task_id='other-task';Set-JournalStepContent $eventIntentJournal 'event-log' (($eventIntentDocument|ConvertTo-Json -Depth 50 -Compress)+"`n");Prepare-JournalFixture $eventIntentJournal $eventIntentId $crashWorkspace;[IO.File]::WriteAllText($eventIntentPath,(($eventIntentJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$eventIntentReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$eventIntentId,'-AsJson');Check ($eventIntentReplay.ExitCode-eq2-and$eventIntentReplay.StdErr-match'event-log payload') 'journal event payload binds every event to its task' 'journal accepted a foreign event payload';Same $snap (Snapshot $crashWorkspace) 'event-payload rejection is zero-write' 'event-payload rejection wrote state';Remove-Item -LiteralPath $eventIntentPath -Force
$pointerIntentId='txn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa5';$pointerIntentPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$pointerIntentId.json";$pointerIntentJournal=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;$pointerIntentDocument=Get-JournalStepJson $pointerIntentJournal 'current-pointer';$pointerIntentDocument.task_id='other-task';Set-JournalStepContent $pointerIntentJournal 'current-pointer' (($pointerIntentDocument|ConvertTo-Json -Depth 50)+"`n");Prepare-JournalFixture $pointerIntentJournal $pointerIntentId $crashWorkspace;[IO.File]::WriteAllText($pointerIntentPath,(($pointerIntentJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$pointerIntentReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$pointerIntentId,'-AsJson');Check ($pointerIntentReplay.ExitCode-eq2-and$pointerIntentReplay.StdErr-match'current-pointer payload') 'journal current pointer binds task_id and target version' 'journal accepted a foreign current pointer';Same $snap (Snapshot $crashWorkspace) 'current-payload rejection is zero-write' 'current-payload rejection wrote state';Remove-Item -LiteralPath $pointerIntentPath -Force
$digestIntentId='txn_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa6';$digestIntentPath=Join-Path $crashWorkspace ".assistant/runtime/failed-writes/$digestIntentId.json";$digestIntentJournal=Get-Content $archive -Raw|ConvertFrom-Json -AsHashtable -DateKind String;Prepare-JournalFixture $digestIntentJournal $digestIntentId $crashWorkspace;$digestIntentJournal.created_at=[datetimeoffset]::UtcNow.AddMinutes(1).ToString('o');[IO.File]::WriteAllText($digestIntentPath,(($digestIntentJournal|ConvertTo-Json -Depth 50)+"`n"),[Text.UTF8Encoding]::new($false));$snap=Snapshot $crashWorkspace;$digestIntentReplay=Invoke-Cli $crashWorkspace @('replay','-TransactionId',$digestIntentId,'-AsJson');Check ($digestIntentReplay.ExitCode-eq2-and$digestIntentReplay.StdErr-match'intent digest') 'journal immutable intent is digest-bound' 'journal accepted a changed immutable intent';Same $snap (Snapshot $crashWorkspace) 'intent-digest rejection is zero-write' 'intent-digest rejection wrote state';Remove-Item -LiteralPath $digestIntentPath -Force
$outsideContract=Write-Contract $outside 'escape-task' 'contract.json';$snap=Snapshot $workspace;$r=Invoke-Cli $workspace @('create','-TaskId','escape-task','-Contract',(Join-Path $outside $outsideContract),'-AsJson')
Check ($r.ExitCode -eq 2 -and $r.StdErr -match 'escapes WorkspaceRoot') 'path escape fails closed' 'path escape accepted';Same $snap (Snapshot $workspace) 'path escape is zero-write' 'path escape wrote state'

try{
    [void](New-Item -ItemType Junction -Path (Join-Path $workspace 'contract-link') -Target $outside -ErrorAction Stop);$snap=Snapshot $workspace
    $r=Invoke-Cli $workspace @('create','-TaskId','escape-task','-Contract','contract-link/contract.json','-AsJson')
    Check ($r.ExitCode -eq 2 -and $r.StdErr -match 'reparse point') 'reparse path fails closed' 'reparse path accepted';Same $snap (Snapshot $workspace) 'reparse rejection is zero-write' 'reparse rejection wrote state'
}catch{$script:unavailable.Add('reparse fixture unavailable: '+$_.Exception.Message)}
try{
    $ancestorTarget=Join-Path $temp 'ancestor-target';$ancestorWorkspace=Join-Path $ancestorTarget 'workspace';$ancestorLink=Join-Path $temp 'ancestor-link';[void][IO.Directory]::CreateDirectory($ancestorWorkspace);[void](New-Item -ItemType Junction -Path $ancestorLink -Target $ancestorTarget -ErrorAction Stop);$ancestorRejected=$false
    $ancestorAliasWorkspace=Join-Path $ancestorLink 'workspace';$resolvedAncestor=& $pathModule {param($Path)Resolve-HarnessWorkspaceRoot -WorkspaceRoot $Path} $ancestorAliasWorkspace
    $ancestorPlan=Join-Path $ancestorWorkspace 'docs/tasks/ancestor-v1/plan.md';[void][IO.Directory]::CreateDirectory((Split-Path -Parent $ancestorPlan));[IO.File]::WriteAllText($ancestorPlan,"---`ntask_id: ancestor-v1`nstage: PLAN`ntool: codex`nupdated: 2026-07-16`n---`n",[Text.UTF8Encoding]::new($false));$ancestorSnap=Snapshot $ancestorWorkspace;$ancestorProtocol=Invoke-Cli $ancestorAliasWorkspace @('protocol','-TaskId','ancestor-v1','-AsJson') $null
    try{[void](& $pathModule {param($Path)Get-HarnessPhysicalPathIdentity -Path $Path} $resolvedAncestor)}catch{$ancestorRejected=$_.Exception.Message-match'reparse point'}
    Check ($ancestorProtocol.ExitCode-eq0-and(Read-Output $ancestorProtocol).selected_protocol-ceq'v1') 'v1 protocol remains usable when only a WorkspaceRoot ancestor is a reparse point' 'shared root resolution blocked v1 under a reparse ancestor';Same $ancestorSnap (Snapshot $ancestorWorkspace) 'v1 protocol under a reparse ancestor is zero-write' 'v1 protocol under a reparse ancestor wrote state'
    Check $ancestorRejected 'v2 physical identity with a reparse ancestor fails closed' 'v2 physical identity accepted a reparse ancestor'
}catch{$script:unavailable.Add('WorkspaceRoot ancestor reparse fixture unavailable: '+$_.Exception.Message)}
if(Test-Path $temp){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}
$repoAfter=@(& git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count -eq 0) 'verifier performs no repository writes' 'verifier changed repository state'
foreach($item in $script:passes){"[PASS] $item"};foreach($item in $script:unavailable){"[UNAVAILABLE] $item"};foreach($item in $script:failures){"[FAIL] $item"}
if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:passes.Count) checks, $($script:unavailable.Count) unavailable)";exit 0
