[CmdletBinding()]
param([string]$RepoRoot='')

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
if(!$RepoRoot){$RepoRoot=Split-Path -Parent $PSScriptRoot};$RepoRoot=(Resolve-Path $RepoRoot).Path
. (Join-Path $RepoRoot 'tests/fixture-test-common.ps1')
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.ProtectedAction.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Evidence.psm1') -Force
Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.AtomicWrite.psm1') -Force
$taskScript=Join-Path $RepoRoot 'scripts/task.ps1';$hookScript=Join-Path $RepoRoot 'runtime-hooks/core/pretooluse.ps1';$script:passes=[Collections.Generic.List[string]]::new();$script:failures=[Collections.Generic.List[string]]::new()
function Check($Condition,$Pass,$Fail){if($Condition){$script:passes.Add($Pass)}else{$script:failures.Add($Fail)}}
function Snapshot($Root){return @(Get-ChildItem $Root -Force -Recurse|%{if($_.PSIsContainer){'D|'+$_.FullName}else{'F|'+$_.FullName+'|'+(Get-FileHash $_.FullName).Hash}}|Sort-Object)}
function Same($Before,$After,$Pass,$Fail){Check (@(Compare-Object @($Before) @($After)).Count-eq0) $Pass $Fail}
function Digest($Text){$hash=[Security.Cryptography.SHA256]::Create();try{return 'sha256:'+([BitConverter]::ToString($hash.ComputeHash([Text.UTF8Encoding]::new($false).GetBytes($Text))).Replace('-','').ToLowerInvariant())}finally{$hash.Dispose()}}
function Complete-Process($Handle){if(-not$Handle.Process.WaitForExit(30000)){$Handle.Process.Kill($true);throw 'process timeout'};$result=[pscustomobject]@{ExitCode=$Handle.Process.ExitCode;StdOut=$Handle.StdOut.GetAwaiter().GetResult().Trim();StdErr=$Handle.StdErr.GetAwaiter().GetResult().Trim()};$Handle.Process.Dispose();return $result}
function Invoke-Cli($Workspace,[string[]]$Arguments){$old=$env:HARNESS_PROTOCOL;try{$env:HARNESS_PROTOCOL='v2';return Complete-Process (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $taskScript -Arguments ($Arguments+@('-RepoRoot',$RepoRoot,'-WorkspaceRoot',$Workspace)))}finally{if($null-eq$old){Remove-Item Env:HARNESS_PROTOCOL -ErrorAction Ignore}else{$env:HARNESS_PROTOCOL=$old}}}
function Invoke-Hook($Workspace,[string[]]$Arguments,$HookRepo=$RepoRoot,$HookPath=$hookScript){return Complete-Process (Start-RepoProcess -UserProfile $env:USERPROFILE -ScriptPath $HookPath -Arguments ($Arguments+@('-RepoRoot',$HookRepo,'-WorkspaceRoot',$Workspace,'-AsJson')))}
function Read-Output($Result){if($Result.StdOut){return $Result.StdOut|ConvertFrom-Json -Depth 50 -DateKind String};return $null}
function Write-JsonFile($Workspace,$Relative,$Value){$path=Join-Path $Workspace $Relative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $path));[IO.File]::WriteAllText($path,(($Value|ConvertTo-Json -Depth 40)+"`n"),[Text.UTF8Encoding]::new($false))}
function Write-Contract($Workspace,$TaskId){$body=[ordered]@{schema_version='requirement-contract/v1';task_id=$TaskId;goal="Protect $TaskId.";acceptance=@('Protected action remains gated.');in_scope=@('v2 safety');out_of_scope=@('production execution');product_constraints=@('No prompt bypass.');product_decisions=@();unresolved_product_decisions=@();source_authority=@('current-user-message')};$contract=[ordered]@{};foreach($key in $body.Keys){$contract[$key]=$body[$key]};$contract.digest=Digest ($body|ConvertTo-Json -Depth 30 -Compress);$relative="contracts/$TaskId.json";Write-JsonFile $Workspace $relative $contract;return [pscustomobject]@{Path=$relative;Digest=$contract.digest}}
function Write-Approval($Workspace,$TaskId,$TaskVersion,$ContractDigest,$ApprovalId,$Type,[string[]]$Scopes,$Status='granted',$Expires=$null){$approval=[ordered]@{schema_version='approval/v1';approval_id=$ApprovalId;task_id=$TaskId;task_version=$TaskVersion;contract_digest=$ContractDigest;approval_type=$Type;approved_scope=$Scopes;approver='fixture-user';approved_at=[DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o');expires_at=$Expires;status=$Status};$relative="approval-inputs/$ApprovalId.json";Write-JsonFile $Workspace $relative $approval;return $relative}
function New-PassEvidence($Workspace,$TaskId,$TaskVersion,$ContractDigest){$recordRelative=".harness/evidence/$TaskId.txt";$recordPath=Join-Path $Workspace $recordRelative;[void][IO.Directory]::CreateDirectory((Split-Path -Parent $recordPath));[IO.File]::WriteAllText($recordPath,"pass`n",[Text.UTF8Encoding]::new($false));$recordDigest='sha256:'+((Get-FileHash $recordPath).Hash.ToLowerInvariant());$record=[ordered]@{type='command';command='pwsh -File tests/approval.ps1';cwd='.';exit_code=0;executed_at=[DateTimeOffset]::UtcNow.ToString('o');evidence_path=$recordRelative;digest=$recordDigest;covers=@('AC-1')};$document=[ordered]@{schema_version='evidence/v1';task_id=$TaskId;task_version=$TaskVersion;contract_digest=$ContractDigest;revision=('dirty:'+'0'*64);records=@($record);coverage=[ordered]@{satisfied=@('AC-1');not_verified=@();blocked=@()};gaps=@();conclusion='pass'};$relative="evidence-inputs/$TaskId.json";Write-JsonFile $Workspace $relative $document;$document.revision=Get-HarnessEvidenceRevision -WorkspaceRoot $Workspace -ContractDigest $ContractDigest -Evidence $document -EvidenceInputPath $relative -EvidenceOutputPath "docs/tasks/$TaskId/evidence.json";Write-JsonFile $Workspace $relative $document;return $relative}
function Start-Task($Workspace,$TaskId,$Contract,$Profile='governed',[string[]]$Capabilities=@()){$args=@('create','-TaskId',$TaskId,'-Contract',$Contract.Path,'-Profile',$Profile,'-AsJson');if($Capabilities.Count){$args+=@('-Capabilities')+$Capabilities};$result=Invoke-Cli $Workspace $args;if($result.ExitCode){throw "create failed: $TaskId $($result.StdErr)"};return Read-Output $result}

$repoBefore=@(&git -C $RepoRoot status --porcelain --untracked-files=all);$temp=Join-Path ([IO.Path]::GetTempPath()) ('v2-approval-'+[guid]::NewGuid().ToString('N'));$workspace=Join-Path $temp 'workspace';[void][IO.Directory]::CreateDirectory($workspace)
try{
    [IO.File]::WriteAllText((Join-Path $workspace '.gitignore'),".assistant/runtime/`n.harness/evidence/`nevidence-inputs/`napproval-inputs/`ndocs/tasks/*/evidence.json`ndocs/tasks/*/plan.md`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $workspace 'source.txt'),"baseline`n",[Text.UTF8Encoding]::new($false));git -C $workspace init -q;git -C $workspace config user.email harness@example.invalid;git -C $workspace config user.name Harness;git -C $workspace config core.autocrlf false;git -C $workspace add .;git -C $workspace commit -qm baseline
    foreach($file in @('scripts/lib/Harness.Approval.psm1','scripts/lib/Harness.ProtectedAction.psm1','scripts/lib/Harness.Governance.psm1','scripts/lib/Harness.TaskState.psm1','runtime-hooks/core/pretooluse.ps1','scripts/task.ps1','tests/verify-v2-approval.ps1')){$path=Join-Path $RepoRoot $file;$tokens=$null;$errors=$null;[Management.Automation.Language.Parser]::ParseFile($path,[ref]$tokens,[ref]$errors)|Out-Null;Check (@($errors).Count-eq0) "$file parses" "$file parse failed";Check (Test-FileHasUtf8Bom $path) "$file has UTF-8 BOM" "$file lacks UTF-8 BOM"}
    Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.Approval.psm1') -Force;$approvalExports=@(Get-Command -Module Harness.Approval|Select-Object -ExpandProperty Name|Sort-Object);Check (@(Compare-Object @('Assert-HarnessTaskApproval','Resolve-HarnessApprovalInput') $approvalExports).Count-eq0) 'Approval exports are exact' 'Approval exports drifted';Import-Module (Join-Path $RepoRoot 'scripts/lib/Harness.ProtectedAction.psm1') -Force;$guardExports=@(Get-Command -Module Harness.ProtectedAction|Select-Object -ExpandProperty Name);Check ($guardExports.Count-eq1-and$guardExports[0]-ceq'Assert-HarnessProtectedAction') 'protected action export is exact' 'protected action exports drifted'
    $contracts=@{};foreach($id in @('critical-task','approval-task','review-task','no-review-task')){$contracts[$id]=Write-Contract $workspace $id}
    [void](Start-Task $workspace 'critical-task' $contracts['critical-task'] 'critical');$snap=Snapshot $workspace;$blocked=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','1','-CommandText','DELETE FROM customer','-Environment','production','-DryRun','-UserInstruction','direct execute')
    Check ($blocked.ExitCode-eq2-and-not$blocked.StdOut-and$blocked.StdErr-match'no current granted Approval') 'unapproved Critical action fails closed despite direct instruction' 'unapproved Critical action was allowed';Same $snap (Snapshot $workspace) 'Critical rejection is zero-write' 'Critical rejection wrote state'
    $scopes=@('rule:production-database-destructive',('command_digest:'+(Digest 'DELETE FROM customer')),'environment:production','dry-run:true');$input=Write-Approval $workspace 'critical-task' 2 $contracts['critical-task'].Digest 'apr_production' 'production' $scopes;$approved=Invoke-Cli $workspace @('approve','-TaskId','critical-task','-ExpectedVersion','1','-Approval',$input,'-AsJson');$approvedValue=Read-Output $approved
    Check ($approved.ExitCode-eq0-and$approvedValue.task.version-eq2-and$approvedValue.task.approvals[0]-ceq'apr_production'-and(Test-Path (Join-Path $workspace $approvedValue.approval_path))) 'external Approval import is transactional and version-bound' 'Approval import failed'
    $allowed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DELETE FROM customer','-Environment','production','-DryRun','-UserInstruction','direct execute');$allowedValue=Read-Output $allowed;$storedApproval=Get-Content -LiteralPath (Join-Path $workspace $approvedValue.approval_path) -Raw -Encoding utf8|ConvertFrom-Json;Check ($allowed.ExitCode-eq0-and$allowedValue.protected-and$allowedValue.approval_id-ceq'apr_production') 'exact approved Critical dry-run is allowed' ("approved Critical dry-run was rejected: exit={0} stderr=[{1}] approved_scopes=[{2}]" -f $allowed.ExitCode,$allowed.StdErr,(@($storedApproval.approved_scope)-join ','))
    $changed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DROP TABLE customer','-Environment','production','-DryRun');Check ($changed.ExitCode-eq2-and$changed.StdErr-match'no current granted Approval') 'expanded command scope invalidates Approval' 'expanded command scope reused stale Approval'
    $noDryRun=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DELETE FROM customer','-Environment','production');Check ($noDryRun.ExitCode-eq2-and$noDryRun.StdErr-match'dry-run') 'Critical destructive command requires dry-run' 'Critical command bypassed dry-run'
    $contractPath=Join-Path $workspace $contracts['critical-task'].Path;$contractText=[IO.File]::ReadAllText($contractPath,[Text.Encoding]::UTF8);$changedContract=$contractText|ConvertFrom-Json -AsHashtable -DateKind String;$changedContract.goal='Changed after approval.';Write-JsonFile $workspace $contracts['critical-task'].Path $changedContract;try{$changedContractResult=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','2','-CommandText','DELETE FROM customer','-Environment','production','-DryRun')}finally{[IO.File]::WriteAllText($contractPath,$contractText,[Text.UTF8Encoding]::new($false))};Check ($changedContractResult.ExitCode-eq2-and$changedContractResult.StdErr-match'Contract digest is stale') 'changed Contract content invalidates Approval' 'changed Contract content reused Approval'
    $transition=Invoke-Cli $workspace @('transition','-TaskId','critical-task','-ExpectedVersion','2','-To','running','-AsJson');$stale=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','critical-task','-ExpectedVersion','3','-CommandText','DELETE FROM customer','-Environment','production','-DryRun');Check ($transition.ExitCode-eq0-and$stale.ExitCode-eq2-and$stale.StdErr-match'no current granted Approval') 'task version change invalidates Approval' 'stale version Approval remained usable'
    $readOnlySnap=Snapshot $workspace;$readOnly=Invoke-Hook $workspace @('-SessionMode','read-only','-ActionMode','write','-ChangedPaths','src/view.ps1','-UserInstruction','direct execute');Check ($readOnly.ExitCode-eq2-and$readOnly.StdErr-match'read-only session') 'read-only session cannot invoke write tool' 'read-only session invoked write tool';Same $readOnlySnap (Snapshot $workspace) 'read-only denial is zero-write' 'read-only denial wrote state'
    $escape=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','../outside.ps1');Check ($escape.ExitCode-eq2-and$escape.StdErr-match'escapes WorkspaceRoot') 'write path escape is rejected' 'write path escape was allowed'
    $ordinary=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','src/view.ps1');Check ($ordinary.ExitCode-eq0-and-not(Read-Output $ordinary).protected) 'ordinary contained write has no protected ceremony' 'ordinary write was over-gated'
    [void](Start-Task $workspace 'no-review-task' $contracts['no-review-task']);$missingReview=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','no-review-task','-ExpectedVersion','1','-ChangedPaths','src/auth/authorize.ps1');Check ($missingReview.ExitCode-eq2-and$missingReview.StdErr-match'independent review policy') 'authorization path requires independent review capability' 'authorization path bypassed review policy'
    [void](Start-Task $workspace 'review-task' $contracts['review-task'] 'governed' @('independent_review_required'));$reviewAllowed=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-TaskId','review-task','-ExpectedVersion','1','-ChangedPaths','src/auth/authorize.ps1');Check ($reviewAllowed.ExitCode-eq0-and(Read-Output $reviewAllowed).protected) 'governed authorization write with required review policy passes preflight' 'valid authorization preflight failed'
    $badRepo=Join-Path $temp 'bad-repo';[void][IO.Directory]::CreateDirectory((Join-Path $badRepo 'policies'));$badPolicyPath=Join-Path $badRepo 'policies/protected-actions.json';[IO.File]::WriteAllText($badPolicyPath,'{"broken":', [Text.UTF8Encoding]::new($false));$badPolicy=$false;try{Assert-HarnessProtectedAction -RepoRoot $badRepo -WorkspaceRoot $workspace -SessionMode write -ActionMode write -ChangedPaths @('src/view.ps1')|Out-Null}catch{$badPolicy=$_.Exception.Message-match'policy is invalid'};Check $badPolicy 'malformed protected policy fails closed' 'malformed protected policy allowed write';Remove-Item $badPolicyPath;$missingPolicy=$false;try{Assert-HarnessProtectedAction -RepoRoot $badRepo -WorkspaceRoot $workspace -SessionMode write -ActionMode write -ChangedPaths @('src/view.ps1')|Out-Null}catch{$missingPolicy=$_.Exception.Message-match'policy is unavailable'};Check $missingPolicy 'unavailable protected policy fails closed for write' 'unavailable protected policy allowed write';$readWithoutPolicy=Assert-HarnessProtectedAction -RepoRoot $badRepo -WorkspaceRoot $workspace -SessionMode read-only -ActionMode read;Check $readWithoutPolicy.allowed 'ordinary read continues without protected policy' 'ordinary read required protected policy'
    $hookOnly=Join-Path $temp 'hook-only';[void][IO.Directory]::CreateDirectory((Join-Path $hookOnly 'runtime-hooks/core'));Copy-Item $hookScript (Join-Path $hookOnly 'runtime-hooks/core/pretooluse.ps1');$missingHookModule=Invoke-Hook $workspace @('-SessionMode','write','-ActionMode','write','-ChangedPaths','src/view.ps1') $hookOnly (Join-Path $hookOnly 'runtime-hooks/core/pretooluse.ps1');Check ($missingHookModule.ExitCode-eq2-and$missingHookModule.StdErr-match'module is unavailable') 'unavailable safety module fails closed for write' 'unavailable safety module allowed write';$readWithoutModule=Invoke-Hook $workspace @('-SessionMode','read-only','-ActionMode','read') $hookOnly (Join-Path $hookOnly 'runtime-hooks/core/pretooluse.ps1');Check ($readWithoutModule.ExitCode-eq0-and(Read-Output $readWithoutModule).allowed) 'ordinary read continues without safety module' 'ordinary read required safety module'
    [void](Start-Task $workspace 'approval-task' $contracts['approval-task'] 'governed' @('approval_required'));[void](Invoke-Cli $workspace @('transition','-TaskId','approval-task','-ExpectedVersion','1','-To','running','-AsJson'));[void](Invoke-Cli $workspace @('transition','-TaskId','approval-task','-ExpectedVersion','2','-To','verifying','-AsJson'));$evidence=New-PassEvidence $workspace 'approval-task' 3 $contracts['approval-task'].Digest;$snap=Snapshot $workspace;$missing=Invoke-Cli $workspace @('verify','-TaskId','approval-task','-ExpectedVersion','3','-Evidence',$evidence,'-AsJson');Check ($missing.ExitCode-eq2-and$missing.StdErr-match'no current granted Approval') 'approval_required task cannot complete without Approval' 'approval_required task completed without Approval';Same $snap (Snapshot $workspace) 'missing completion Approval is zero-write' 'missing completion Approval wrote state'
    $revokedInput=Write-Approval $workspace 'approval-task' 4 $contracts['approval-task'].Digest 'apr_revoked' 'product' @('task:complete') 'revoked';$snap=Snapshot $workspace;$revoked=Invoke-Cli $workspace @('approve','-TaskId','approval-task','-ExpectedVersion','3','-Approval',$revokedInput,'-AsJson');Check ($revoked.ExitCode-eq2-and$revoked.StdErr-match'only a granted') 'revoked Approval cannot be imported' 'revoked Approval was imported';Same $snap (Snapshot $workspace) 'revoked Approval rejection is zero-write' 'revoked Approval rejection wrote state';$expiredInput=Write-Approval $workspace 'approval-task' 4 $contracts['approval-task'].Digest 'apr_expired' 'product' @('task:complete') 'granted' ([DateTimeOffset]::UtcNow.AddMinutes(-1).ToString('o'));$snap=Snapshot $workspace;$expired=Invoke-Cli $workspace @('approve','-TaskId','approval-task','-ExpectedVersion','3','-Approval',$expiredInput,'-AsJson');Check ($expired.ExitCode-eq2-and$expired.StdErr-match'Approval is expired') 'expired Approval cannot be imported' 'expired Approval was imported';Same $snap (Snapshot $workspace) 'expired Approval rejection is zero-write' 'expired Approval rejection wrote state'
    $validInput=Write-Approval $workspace 'approval-task' 4 $contracts['approval-task'].Digest 'apr_complete' 'product' @('task:complete');$grant=Invoke-Cli $workspace @('approve','-TaskId','approval-task','-ExpectedVersion','3','-Approval',$validInput,'-AsJson');$evidence=New-PassEvidence $workspace 'approval-task' 4 $contracts['approval-task'].Digest;$verified=Invoke-Cli $workspace @('verify','-TaskId','approval-task','-ExpectedVersion','4','-Evidence',$evidence,'-AsJson');$verifiedValue=Read-Output $verified;Check ($grant.ExitCode-eq0-and$verified.ExitCode-eq0-and$verifiedValue.task.status-ceq'done') 'current granted Approval permits policy-complete Evidence' 'valid completion Approval did not permit done'
}finally{if(Test-Path $temp){Remove-DirectoryWithRetry -Path $temp}}
$repoAfter=@(&git -C $RepoRoot status --porcelain --untracked-files=all);Check (@(Compare-Object $repoBefore $repoAfter).Count-eq0) 'Approval verifier performs no repository writes' 'Approval verifier changed repository state'
foreach($item in $script:passes){"[PASS] $item"};foreach($item in $script:failures){"[FAIL] $item"};if($script:failures.Count){"STATUS: FAIL ($($script:failures.Count) failed)";exit 1};"STATUS: PASS ($($script:passes.Count) checks)";exit 0
