[CmdletBinding()]
param(
    [string]$RepoRoot = '',
    [string]$ManifestRoot = 'modules',
    [string]$OutputPath = 'module-manifest-catalog.json',
    [string]$CapabilitySourceOutputPath = 'capability-source-catalog.json',
    [switch]$Check,
    [switch]$AsJson
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

try {
    if ([string]::IsNullOrWhiteSpace($RepoRoot)) { $RepoRoot = Split-Path -Parent $PSScriptRoot }
    $RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
    if ($Check -and $AsJson) { throw '-Check and -AsJson are mutually exclusive' }
    Import-Module (Join-Path $PSScriptRoot 'lib\Harness.Path.psm1') -Force -ErrorAction Stop
    $outputFullPath = Resolve-HarnessContainedPath -WorkspaceRoot $RepoRoot -Path $OutputPath -Label 'Module Manifest catalog output' -AllowMissing
    $capabilitySourceOutputFullPath = Resolve-HarnessContainedPath -WorkspaceRoot $RepoRoot -Path $CapabilitySourceOutputPath -Label 'Capability source catalog output' -AllowMissing
    Import-Module (Join-Path $PSScriptRoot 'lib\Harness.ModuleManifest.psm1') -Force -ErrorAction Stop
    $result = Get-HarnessModuleManifestCatalog -RepoRoot $RepoRoot -ManifestRoot $ManifestRoot
    if ($Check) {
        if (-not (Test-Path -LiteralPath $outputFullPath -PathType Leaf)) { throw 'Module Manifest catalog output does not exist' }
        $before = [System.IO.File]::ReadAllBytes($outputFullPath)
        if ($before.Length -ne $result.Bytes.Length -or [Convert]::ToBase64String($before) -cne [Convert]::ToBase64String($result.Bytes)) {
            throw 'Module Manifest catalog does not match generated bytes'
        }
        if ($null -ne $result.CapabilitySourceBytes) {
            if (-not (Test-Path -LiteralPath $capabilitySourceOutputFullPath -PathType Leaf)) { throw 'Capability source catalog output does not exist' }
            $capabilitySourceBefore = [System.IO.File]::ReadAllBytes($capabilitySourceOutputFullPath)
            if ($capabilitySourceBefore.Length -ne $result.CapabilitySourceBytes.Length -or [Convert]::ToBase64String($capabilitySourceBefore) -cne [Convert]::ToBase64String($result.CapabilitySourceBytes)) {
                throw 'Capability source catalog does not match generated bytes'
            }
        }
        Write-Output "STATUS: PASS"
        Write-Output "Module Manifest catalog matches tracked bytes; modules=$($result.Catalog.totals.module_count); capability_sources=$(if($null-eq$result.CapabilitySourceCatalog){0}else{$result.CapabilitySourceCatalog.totals.module_count}); owners=$($result.Catalog.totals.owner_test_count); unresolved=0"
    } elseif ($AsJson) {
        [Console]::Out.Write($result.CanonicalText)
    } else {
        $parent = Split-Path -Parent $outputFullPath
        if (-not (Test-Path -LiteralPath $parent -PathType Container)) { throw 'Module Manifest catalog output parent does not exist' }
        [System.IO.File]::WriteAllBytes($outputFullPath,[byte[]]$result.Bytes)
        Write-Output "WROTE: $OutputPath"
        if ($null -ne $result.CapabilitySourceBytes) {
            $capabilitySourceParent = Split-Path -Parent $capabilitySourceOutputFullPath
            if (-not (Test-Path -LiteralPath $capabilitySourceParent -PathType Container)) { throw 'Capability source catalog output parent does not exist' }
            [System.IO.File]::WriteAllBytes($capabilitySourceOutputFullPath,[byte[]]$result.CapabilitySourceBytes)
            Write-Output "WROTE: $CapabilitySourceOutputPath"
        }
    }
    exit 0
} catch {
    [Console]::Error.WriteLine($_.Exception.Message)
    exit 2
}
